<?php echo $this->form()->openTag($this->form); ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Registro de Adicional de Establecimiento</h4>
    </div>
    <div class="panel-body">
        <div class="form-group">
            <label for="descripcion_tipo" class="col-lg-3 control-label">Descripción de Adicional :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('descripcion_adicionales')); ?>
                <?php echo $this->formRow($this->form->get('id_adicionales')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="id_tipo_adicional" class="col-lg-3 control-label">Tipo Adicional :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('id_tipo_adicional')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-7">
                <?php echo $this->formRow($this->form->get('submit')); ?>&nbsp;&nbsp;&nbsp;&nbsp;
                <?php echo $this->formRow($this->form->get('btn-regresar')); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function () {

        // Delete button popover confirmation
        $('#adicionalesForm').formValidation({
            message: 'El valor no es válido.',
            err: {
                container: 'tooltip'
            },
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh',
            },
            fields: {
                descripcion_adicionales: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre el Adicional.'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9ñáéíóúÑÁÉÍÓÚ& ,.-]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 150,
                            message: 'Este campo debe contener 150 caracteres como máximo.'
                        }
                    }
                },
                id_tipo_adicional: {
                    err: 'popover',
                    //icon: false,
                    validators: {
                        greaterThan: {
                            value: 1,
                            message: 'Por favor seleciione el Rol del Usuario.'
                        }
                    }
                }
            }
        }).on('success.form.fv', function (e) {
            $("#modalConfirmacion").modal('show');
        });

        $("#modal-confirmacion-si").click(
            function (e) {
                $('button').removeClass('fv-hidden-submit disabled').addClass('fv-hidden-submit');
                $('.fv-hidden-submit').removeAttr('disabled');
                $("#modalConfirmacion").modal('hide');
                $('.fv-hidden-submit').click();
            }
        );

        $("#modal-confirmacion-no").click(
            function (e) {
                $('#submit').removeClass('btn btn-primary disabled').addClass('btn btn-primary');
                $('#submit').removeAttr('disabled');
                $("#modalConfirmacion").modal('hide');
            }
        );

        $("#btn-regresar").click(
            function (e) {
                $("#modalCancelacion").modal('show');
            }
        );

        $("#modal-cancelacion-si").click(
            function (e) {
                $(location).attr('href','/dashboard/adicionales/list');
            }
        );

        $("#modal-cancelacion-no").click(
            function (e) {
                $("#modalCancelacion").modal('hide');
            }
        );
    });
</script>