<div class="container">
    <div class="box_center box_rebueno_information">
        <h2>¿Cómo funciona Rebueno?</h2>
        <hr class="medium">
        <section>
            <ol>
                <li>Cada día te ofrecemos <b>las mejores ofertas</b> para que puedas disfrutar de restaurantes, spas, planes de aventura, espectáculos, centros de belleza y salud y todo lo que te gusta a precios insuperables, con descuentos de hasta el 90%.<br>Para ser el primero en conocer nuestras ofertas debes suscribirte en rebueno.ec y te enviaremos boletines diarios.</li>
                <li>Si te gusta una oferta, no pierdas tiempo y haz click en “Comprar”, ya que estará disponible solo por 24 horas. <b>Elige el medio de pago de tu preferencia:</b> efectivo, tarjeta de crédito o transferencia bancaria.<br>Recibirás una confirmación de pago cuando éste se haya efectuado y cuando finalice la campaña, te enviaremos los cupones que hayas comprado para que puedas disfrutarlos.</li>
                <li>Como no existe nada mejor que compartir buenas noticias, <b>Rebueno</b> te da la posibilidad de que recomiendes la oferta a tus amigos a través de Facebook, Twitter y correo electrónico.</li>
                <li>Revisa las condiciones que aparecen en tu Rebueno, haz tu reserva y <b>disfruta de solo buenas experiencias.</b></li>
            </ol>
        </section>
    </div>
</div>
