<div class="box_center box_rebueno_information">
    <h2>Contáctanos</h2>
    <hr class="medium">
    <section>
        <p>Si tienes alguna duda sobre <b>Rebueno </b> puedes contactarnos: llamándonos al 311 - XXXX o escribiéndonos a los correos electrónicos de contacto:</p>
        <p>Si eres Cliente de Rebueno escríbenos a <a href="mailto:clientes@rebueno.ec" title="clientes@rebueno.ec">clientes@rebueno.ec</a>.</p>
        <p>Si eres Socio (o quieres serlo) escríbenos a <a href="mailto:socios@rebueno.ec" title="socios@rebueno.ec">socios@rebueno.ec</a>.</p>
    </section>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $(".carrusel-principal").css("display","none");
    });
</script>