<div class="box_center box_buenisimo_information">
    <h2>Contáctanos</h2>
    <hr class="medium">
    <section>
        <p>Si tienes alguna duda sobre <b>Buenisimo </b> puedes contactarnos: llamándonos al 311 - XXXX o escribiéndonos a los correos electrónicos de contacto:</p>
        <p>Si eres Cliente de Buenisimo escríbenos a <a href="mailto:clientes@buenisimo.ec" title="clientes@buenisimo.ec">clientes@buenisimo.ec</a>.</p>
        <p>Si eres Socio (o quieres serlo) escríbenos a <a href="mailto:socios@buenisimo.ec" title="socios@buenisimo.ec">socios@buenisimo.ec</a>.</p>
    </section>
</div>