<div class="box_center box_buenisimo_information">
    <h2>Sobre Buenisimo</h2>
    <hr class="medium">
    <section>
        <h3><b>¡Solo buenas experiencias!</b></h3>
        <p>Buenisimo es el sitio web de las Ofertas Diarias.</p>
        <p>Aquí vivirás solo buenas experiencias, con <span class="discount">descuentos de hasta 90%</span> en espectáculos, viajes, restaurantes, spas, aventura centros de belleza y salud, y mucho más. </p>
        <p>Si te suscribes a <strong>Buenisimo.ec</strong>, tendrás acceso a increíbles ofertas que podrás conocer a través de nuestros boletines diarios. Visita Buenisimo.ec y vivirás ¡solo buenas experiencias! Si tienes alguna pregunta no dudes en contactarte con nosotros.</p>
        <p>Puedes escribirnos a <a href="mailto:clientes@buenisimo.ec" title="clientes@buenisimo.ec">clientes@buenisimo.pe </a>o llamar a nuestro Call Center: <strong>311 - XXXX.</strong></p>
    </section>
</div>
