<div class="container">
    <div class="box_center ">
        <h2>Sobre Rebueno</h2>
        <hr class="medium">
        <section>
            <h3><b>¡Solo buenas experiencias!</b></h3>
            <br>
            <p>Rebueno es el sitio web de las Ofertas Diarias.</p>
            <br>
            <p>Aquí vivirás solo buenas experiencias, con <span class="discount">descuentos de hasta 90%</span> en espectáculos, viajes, restaurantes, spas, aventura centros de belleza y salud, y mucho más. </p>
            <br>
            <p>Si te suscribes a <strong>Rebueno.ec</strong>, tendrás acceso a increíbles ofertas que podrás conocer a través de nuestros boletines diarios. Visita Rebueno.ec y vivirás ¡solo buenas experiencias! Si tienes alguna pregunta no dudes en contactarte con nosotros.</p>
            <br>
            <p>Puedes escribirnos a <a href="mailto:clientes@rebueno.ec" title="clientes@rebueno.ec">clientes@rebueno.ec</a> o llamar a nuestro Call Center: <strong><?php echo $empresa['telefono'];?>.</strong></p>
            <br>
        </section>
    </div>
</div>