<div class="box_center box_sitemap">
    <h2>Mapa del sitio</h2>
    <hr class="medium">
            <ul class="circle">
            <li><span class="title">Acerca de Ofertop</span>
                <ul>
                                            <li><a href="http://ofertop.pe/interes">Sobre OferTOP</a></li>
                                            <li><a href="http://ofertop.pe/interes/como-funciona">¿Cómo funciona?</a></li>
                                            <li><a href="http://ofertop.pe/interes/preguntas-frecuentes">Preguntas frecuentes</a></li>
                                            <li><a href="http://ofertop.pe/interes/acerca-pago-efectivo">Acerca de Pago Efectivo</a></li>
                                            <li><a href="http://ofertop.pe/interes/terminos-y-condiciones">Términos y Condiciones</a></li>
                                            <li><a href="http://ofertop.pe/interes/contactanos">Contáctanos</a></li>
                                            <li><a href="http://gec.pe/LibroReclamaciones/reclamo/p/ofertop.pe">Libro de reclamaciones</a></li>
                                            <li><a href="http://ofertop.pe/interes/politicas-de-privacidad">Políticas de Privacidad</a></li>
                                    </ul>
            </li>
        </ul>
            <ul class="circle">
            <li><span class="title">Categorías en Ofertop</span>
                <ul>
                                            <li><a href="http://ofertop.pe/ofertas/lima/belleza-salud">Belleza & Salud</a></li>
                                            <li><a href="http://ofertop.pe/ofertas/lima/viajes">Viajes</a></li>
                                            <li><a href="http://ofertop.pe/ofertas/lima/restaurantes">Restaurantes</a></li>
                                            <li><a href="http://ofertop.pe/ofertas/lima/entretenimiento">Entretenimiento</a></li>
                                            <li><a href="http://ofertop.pe/ofertas/lima/productos">Productos</a></li>
                                            <li><a href="http://ofertop.pe/ofertas/lima/servicios">Servicios</a></li>
                                            <li><a href="http://ofertop.pe/ofertas/lima/megaplaza">MegaPlaza</a></li>
                                    </ul>
            </li>
        </ul>
            <ul class="circle">
            <li><span class="title">Usuarios Ofertop</span>
                <ul>
                                            <li><a href="http://ofertop.pe/registro">Registro de usuario</a></li>
                                            <li><a href="http://ofertop.pe/recuperar">Recuperar contraseña</a></li>
                                    </ul>
            </li>
        </ul>
            <ul class="circle">
            <li><span class="title">Socios Ofertop</span>
                <ul>
                                            <li><a href="http://retailer.ofertop.pe/">Ingresa a tu cuenta de socio</a></li>
                                            <li><a href="http://ofertop.pe/paginas/contacto-retailer">Contáctenos</a></li>
                                    </ul>
            </li>
        </ul>
            <ul class="circle">
            <li><span class="title">Métodos de pago</span>
                <ul>
                                            <li><a href="https://pagoefectivo.pe/">Pago Efectivo</a></li>
                                            <li><a href="http://www.visanet.com.pe">Visa</a></li>
                                            <li><a href="http://www.companiaperuanademediosdepago.pe/visa.htm">Verified by visa</a></li>
                                            <li><a href="http://www.visanet.com.pe/promovbv/bancos.html">Afiliate Verified by visa</a></li>
                                            <li><a href="http://www.mastercard.com/pe/consumidores/index.html">Master Card</a></li>
                                            <li><a href="http://www.mastercard.com/us/personal/es/servicios/codigodeseguridad/">Master Card Sercure Code</a></li>
                                    </ul>
            </li>
        </ul>
            <ul class="circle">
            <li><span class="title">Redes Sociales</span>
                <ul>
                                            <li><a href="https://www.facebook.com/OferTOPLima">Facebook Ofertop</a></li>
                                            <li><a href="https://twitter.com/OferTOPLima">Twitter Ofertop</a></li>
                                            <li><a href="https://plus.google.com/101107211628238000946">Google Plus Ofertop</a></li>
                                    </ul>
            </li>
        </ul>
    </div>