<div class="container">
    <div class="box_center box_rebueno_information">
        <h2>Políticas de Privacidad</h2>
        <hr class="medium">
        <section>
            <h3>Declaraciones de privacidad y confidencialidad</h3>
            <p>Las presentes Declaraciones, tienen por objeto poner en conocimiento de los usuarios los alcances de la protección integral de los datos personales asentados en archivos; registros; bancos o bases de datos; u otros medios técnicos de tratamiento de datos, en pos de un adecuado respeto al derecho a la intimidad de las personas, así como también al libre acceso a la información que sobre las mismas pueda eventualmente registrarse.</p>

            <p>En este sentido Rebueno, a la luz del objeto propuesto, garantiza que los datos recabados a través del sitio, serán tratados siempre de modo tal que quede resguardada la finalidad tuitiva que la protección de los datos personales consagra. </p>

            <p>La confidencialidad de las comunicaciones privadas entre Rebueno, y los usuarios implicará el mantenimiento de la información en archivos, bancos o bases de datos, de modo tal que el acceso por parte de usuarios o de simples terceros que no se encuentren autorizados a tal efecto, se encuentre restringido.</p>

            <h3>Voluntariedad en la entrega de datos</h3>
            <p>Las presentes declaraciones están destinadas a informar a los usuarios acerca del tratamiento de datos personales llevado adelante por Rebueno, con el objeto que libre y voluntariamente determinen la aprobación para ser incluidos dentro de las listas de envió de la empresa.</p>


            <h3>Finalidad de los datos recolectados</h3>
            <p>La recolección y tratamiento de datos de carácter personal tiene por finalidad la prestación, gestión, administración, personalización, actualización y mejora de los de los contenidos puestos a disposición a través de envíos de Comunicaciones (Newsletters) por parte de Rebueno. Asimismo los datos podrán ser utilizados para el envío personalizado de las comunicaciones a los usuarios, en lo referente a los servicios y contenidos brindados por la empresa.</p>

            <h3>Autorización de uso</h3>
            <p>El usuario que facilitara sus datos personales, autoriza expresamente a Rebueno para el uso de los datos aportados con los fines aquí expuestos.</p>

            <h3>Derechos de los titulares de los datos</h3>
            <p>A su vez, y como consecuencia de la garantía de los derechos amparados, se expresa también como finalidad, la de permitir en todo momento el acceso a la información por parte de las personas vinculadas a los datos registrados. De este modo, el usuario podrá ejercitar los derechos de acceso, rectificación o cancelación de datos.</p>

            <p>Efectuado el ingreso de los datos por los usuarios, Rebueno, procederá a la rectificación, supresión o actualización de los datos personales del afectado, cuando ello fuere procedente.</p>

            <p>La supresión de algún/nos datos no procederá cuando pudiese causar perjuicios a derechos o intereses legítimos de terceros, o cuando existiera una obligación legal de conservar los datos.</p>

            <h3>El derecho a exigir la rectificación de los datos:</h3>
            <p>En principio, el derecho a exigir la rectificación puede ser ejercido ante la falsedad, inexactitud, imprecisión o carácter erróneo que tengan los datos. Su reconocimiento implica el de la preservación de la veracidad de la información, condición que hace a la calidad de la misma.</p>

            <h3>El derecho a requerir la actualización de los datos:</h3>
            <p>La actualización estriba en preservar la vigencia del dato, esto es, la correspondencia de la fracción de información que representa con el ámbito temporal en que es proporcionado.</p>

            <h3>Sobre las Cookies</h3>
            <p>Eventualmente Rebueno puede utilizar cookies, que se instalaran en la computadora del usuario cuando este navegue por el sitio. Tienen por finalidad facilitar la navegación por el sitio al usuario, y proporcionar a Rebueno, información que le ayudara a mejorar los sus servicios y contenidos. En ningún caso las cookies utilizadas por Rebueno proporcionarán información de carácter personal de usuario, quien en relación a las mismas mantendrá pleno anonimato, aun frente a Rebueno, dado que tampoco suministran información tendiente a la individualización del usuario.</p>

            <h3>Medidas de seguridad adoptadas</h3>
            <p>Rebueno, en relación a sus archivos, bases o bancos de datos que contengan información personal de los usuarios, adopta todas las medidas de seguridad lógica y física exigidas por las reglamentaciones, y las que resultan de la adecuada prudencia y diligencia en la protección de terceros que han depositado su confianza en Rebueno.</p>

            <h3>Envíos de mensajes y comunicaciones </h3>
            <p>Serán enviados Comunicaciones por parte de Rebueno: comunicaciones para presentar un producto, servicio, información corporativa, contenidos que consideremos podría ser de interés, mensajes destinados a confirmar su inscripción, y/o bien para notificarlo respecto a los cambios de los términos y condiciones o de esta Política de Privacidad. Si usted decidiera dejar de recibir el servicio de envío de mensajes, podrá realizarlo en forma automática a través de un hipervínculo que se incorpora en todas nuestras comunicaciones, o bien a través de nuestra dirección unsuscribe@rebueno.ec.</p>

            <h3>Excepciones a nuestra reserva de la Información Personal y otras informaciones </h3>
            <p>En cumplimiento de nuestras obligaciones legales, su Información Personal y/o cualquier otro tipo de información específica sobre Ud. a la que podamos acceder, en forma intencional o casual, y/o sobre su cuenta, podrá ser revelada a terceros a efectos de cumplir con procedimientos legales tal como una orden de allanamiento, una citación judicial, una orden judicial, o bien a requerimientos de autoridades administrativas, que puedan ser considerados válidos bajo las leyes aplicables. Asimismo, para nuestra protección, la suya y las de otros usuarios, también podrá ser revelada su Información Personal en aquellos casos que impliquen la existencia de un intento de ruptura de la seguridad, o de peligro físico o amenaza en contra suyo, nuestro o de terceros.</p>

        </section>
    </div>
</div>