<div class="box_center box_buenisimo_information">
    <h2>Preguntas Frecuentes</h2>
    <hr class="medium">
    <section>
        <ol class="headings">
            <li>
                <h3>Suscribirte a Buenisimo</h3>
                <h4>¿Suscribirme tiene algún costo?</h4>
                <p>No tiene costo alguno. Suscribirte a Buenisimo es totalmente gratis.</p>
                <h4>¿Cómo me suscribo a Buenisimo?</h4>
                <p>Suscribirte a Buenisimo es muy sencillo. Tienes que inscribir tu correo electrónico en www.ofertop.pe, elegir la ciudad de la cual deseas recibir ofertas diarias y listo. Automáticamente, te llegará un correo de bienvenida. Desde entonces, recibirás ofertas únicas todos los días.</p>
                <h4>¿Cómo cancelo mi suscripción?</h4>
                <p>Cancela tu suscripción a nuestro boletín de ofertas diarias clickeando en el link “Haz click aquí para darte de baja la suscripción” y automáticamente dejarás de recibirlo.</p>
            </li>
            <li>
                <h3>Registrarte en Buenisimo</h3>
                <h4>¿Cómo accedo a mi cuenta de Buenisimo?</h4>
                <p>Ingresas a www.ofertop.pe y en la parte superior derecha, ingresas tu correo, contraseña y ¡listo! Una vez dentro podrás actualizar tus datos, ver las compras hechas y descargar tus Buenisimos comprados.</p>
                <h4>¿Qué hago si no recuerdo mi contraseña?</h4>
                <p>Debajo del campo de “contraseña”, encontrarás el  link "¿Olvidaste tu contraseña?" Hazle click e introduce tu dirección de correo electrónico. Recibirás un correo electrónico con un enlace para volver a crear una nueva contraseña.</p>
            </li>
            <li>
                <h3>Comprar una oferta en Buenisimo</h3>
                <h4>¿Cómo compro una oferta?</h4>
                <p>Para comprar una oferta en Buenisimo, solo tienes que darle click a la opción “Comprar”. Elige la forma de pago que prefieras, en efectivo, tarjeta de crédito o transferencia bancaria, y te llegará una confirmación de pago a tu correo electrónico. Al finalizar la campaña, los Buenisimos que hayas comprado llegarán a tu correo.</p>
                <h4>¿Debo utilizar mi OferTop el mismo día que lo compro?</h4>
                <p>No, tu Buenisimo se activará una vez que finalice la oferta y será válido hasta la fecha que indique la oferta que has elegido. Siempre intentaremos que el plazo para que disfrutes de tu Buenisimo sea lo más amplio posible.</p>
                <h4>Ya recibí mi Buenisimo por correo electrónico ¿y ahora qué?</h4>
                <p>Sólo te queda imprimirlo o llevarlo en tu smartphone al establecimiento y presentarlo. Recuerda que además de tenerlo en tu bandeja de entrada, también cuentas con la posibilidad de obtener el Buenisimo entrando en tu cuenta, en la sección “mis pedidos”. Solo tienes que hacer click en el enlace denominado “Tu Buenisimo” e imprimirlo o guardarlo. En él encontrarás toda la información que necesitas. En caso de no ser así, ponte en contacto con nosotros para poder solucionarlo.</p>
                <h4>¿Hasta cuándo puedo usar mis Buenisimos comprados?</h4>
                <p>Cada oferta que presentamos tiene un periodo de vigencia dentro del cual puedes hacer uso de tu Buenisimo y disfrutar del servicio o producto que hayas comprado. Además, en algunos casos, se te solicitará realizar una reserva o llamar por teléfono al establecimiento que brinda la oferta, antes de utilizarlo. </p>
                <h4>¿Puedo regalar Buenisimos?</h4>
                <p>Haz click en la opción “Regalar a un amigo” durante el proceso de compra y se te solicitarán los datos de tu amigo, así nosotros podremos enviarle el Buenisimo. Si deseas enviárselo tú mismo, entonces elige la opción “Comprar”, sigue el proceso regular de compra y el Buenisimo te llegará a tu correo.</p>
            </li>
            <li>
                <h3>Otras preguntas</h3>
                <h4>¿Cómo me hago socio de Buenisimo?</h4>
                <p>Ser socio de Buenisimo es muy fácil. Puedes llamarnos al teléfono: 311 - XXXX o escribirnos a socios@buenisimo.ec y uno de nuestros asesores comerciales se pondrá en contacto contigo cuanto antes.</p>
                <h4>¿Buenisimo es seguro?</h4>
                <p>Es totalmente seguro. Tus datos bancarios se transmiten directamente a las plataformas de cobro de los bancos sin que Buenisimo, ni terceros, accedan en ningún momento a dicha información.		</p>
            </li>
        </ol>
    </section>
</div>