<div class="container">
    <div class="box_center box_rebueno_information">
        <h2>Preguntas Frecuentes</h2>
        <hr class="medium">
        <section>
            <ol class="headings">
                <li>
                    <h3>Suscribirte a Rebueno</h3>
                    <h4>¿Suscribirme tiene algún costo?</h4>
                    <p class="justificado">No tiene costo alguno. Suscribirte a Rebueno es totalmente gratis.</p>
                    <h4>¿Cómo me suscribo a Rebueno?</h4>
                    <p class="justificado">Suscribirte a Rebueno es muy sencillo. Tienes que inscribir tu correo electrónico en www.rebueno.ec, elegir la ciudad de la cual deseas recibir ofertas diarias y ¡Listo!. Automáticamente, te llegará un correo de bienvenida. Desde entonces, recibirás ofertas únicas todos los días.</p>
                    <h4>¿Cómo cancelo mi suscripción?</h4>
                    <p class="justificado">Cancela tu suscripción a nuestro boletín de ofertas diarias clickeando en el link “Haz click aquí para darte de baja la suscripción” y automáticamente dejarás de recibirlo.</p>
                </li>
                <li>
                    <h3>Registrarte en Rebueno</h3>
                    <h4>¿Cómo accedo a mi cuenta de Rebueno?</h4>
                    <p class="justificado">Ingresas a www.rebueno.ec y en la parte superior derecha, ingresas tu correo, contraseña y ¡Listo! Una vez dentro podrás actualizar tus datos, ver las compras hechas y descargar tus Cupones Rebuenos comprados.</p>
                    <h4>¿Qué hago si no recuerdo mi contraseña?</h4>
                    <p class="justificado">Debajo del campo de “contraseña”, encontrarás el  link "¿Olvidaste tu contraseña?" Hazle click e introduce tu dirección de correo electrónico. Recibirás un correo electrónico con un enlace para volver a crear una nueva contraseña.</p>
                </li>
                <li>
                    <h3>Comprar una oferta en Rebueno</h3>
                    <h4>¿Cómo compro una oferta?</h4>
                    <p class="justificado">Para comprar una oferta en Rebueno, solo tienes que darle click a la opción “Comprar”. Elige la forma de pago que prefieras, en efectivo, tarjeta de crédito o transferencia bancaria, y te llegará una confirmación de pago a tu correo electrónico. Al finalizar la campaña, los Cupones Rebuenos que hayas comprado llegarán a tu correo.</p>
                    <h4>¿Debo utilizar mi Cup&oacute;n Rebueno el mismo día que lo compro?</h4>
                    <p class="justificado">No, tu Cup&oacute;n Rebueno se activará una vez que finalice la oferta y será válido hasta la fecha que indique la oferta que has elegido. Siempre intentaremos que el plazo para que disfrutes de tu Cup&oacute;n Rebueno sea lo más amplio posible.</p>
                    <h4>Ya recibí mi Cup&oacute;n Rebueno por correo electrónico ¿y ahora qué?</h4>
                    <p class="justificado">Sólo te queda imprimirlo o llevarlo en tu smartphone al establecimiento y presentarlo. Recuerda que además de tenerlo en tu bandeja de entrada, también cuentas con la posibilidad de obtener el Cup&oacute;n Rebueno entrando en tu cuenta, en la sección “mis pedidos”. Solo tienes que hacer click en el enlace denominado “Tu Cupón Rebueno” e imprimirlo o guardarlo. En él encontrarás toda la información que necesitas. En caso de no ser así, ponte en contacto con nosotros para poder solucionarlo.</p>
                    <h4>¿Hasta cuándo puedo usar mis Cupones Rebuenos comprados?</h4>
                    <p class="justificado">Cada oferta que presentamos tiene un periodo de vigencia dentro del cual puedes hacer uso de tu Cup&oacute;n Rebueno y disfrutar del servicio o producto que hayas comprado. Además, en algunos casos, se te solicitará realizar una reserva o llamar por teléfono al establecimiento que brinda la oferta, antes de utilizarlo. </p>
                </li>
                <li>
                    <h3>Otras preguntas</h3>
                    <h4>¿Cómo me hago socio de Rebueno?</h4>
                    <p class="justificado">Ser socio de Rebueno es muy fácil. Puedes llamarnos al teléfono: <?php echo $empresa['telefono'];?> o escribirnos a socios@rebueno.ec y uno de nuestros asesores comerciales se pondrá en contacto contigo cuanto antes.</p>
                    <h4>¿Rebueno es seguro?</h4>
                    <p class="justificado">Es totalmente seguro. Tus datos bancarios se transmiten directamente a las plataformas de cobro de los bancos sin que Rebueno, ni terceros, accedan en ningún momento a dicha información.		</p>
                </li>
            </ol>
        </section>
    </div>
</div>