<div class="container">
    <div class="box_center box_rebueno_information">
        <section>
            <div class="accordion">
                <div class="header">
                    <h2>Términos y condiciones generales</h2><span></span>
                </div>
                <hr class="medium">
            </div>
            <div class="container">
                <div class="content">
                    <!-- REEMPLAZAR -->
                    <p align="CENTER">
                        <strong>Términos y Condiciones de Uso</strong>
                    </p>
                    <p>
                        Este es el Portal <a href="http://www.rebueno.ec/">www.rebueno.ec</a> de propiedad de ECUADOR.COM, con domicilio en Jr. Gonzales Olaechea 446-448, San Isidro, Lima, (en adelante ECUADOR.COM), y los
                        siguientes son los Términos y Condiciones de Uso que regulan el acceso y uso de este Portal (en adelante “el sitio”) y, en general, la relación entre
                        ECUADOR.COM y los USUARIOS del sitio, sin perjuicio de otras condiciones e instrucciones particulares o específicas que ECUADOR.COM comunique adecuadamente a los
                        usuarios.
                    </p>
                    <p>
                        La utilización del sitio atribuye la condición de USUARIO del mismo, e implica la aceptación plena y sin reservas de todas y cada una de las disposiciones
                        incluidas en estos Términos y Condiciones, siendo obligación del USUARIO leer atentamente los Términos y Condiciones antes de hacer uso del sitio y de su
                        contenido.
                    </p>
                    <p>
                        Al comunicarte con este sitio Web, las políticas y normas detalladas a continuación, se consideran aceptadas.
                    </p>
                    <p>
                        <strong>1.</strong>
                        En la página web <a href="http://www.rebueno.ec/">www.rebueno.ec</a> se ofrecen cupones sobre prestaciones o sobre mercancías de otras empresas (“Los socios”). Emitentes de los cupones y
                        deudores de las prestaciones o mercancías indicadas en los cupones son exclusivamente los respectivos socios, los cuales realizan esas prestaciones con
                        arreglo a sus respectivas Condiciones Generales de Contratación. ECUADOR.COM misma no adeuda la realización de las prestaciones indicadas en los cupones ni la
                        entrega de las mercancías indicadas en los mismos, sino que el cupón le concede al usuario únicamente un derecho a que el socio o los socios realicen la
                        prestación. Para la utilización del servicio de ECUADOR.COM rigen única y exclusivamente los siguientes términos y condiciones de uso. Los cupones vendidos por
                        ECUADOR.COM no están dirigidos a una prestación concreta (cupón de acontecimiento) ni a una mercancía concreta (cupón de mercancía) ni a un valor de prestación
                        o mercancía concretos (cupón de valor). En caso que el socio o los socios hubieran fijado sus propios términos y condiciones para los actos y contratos que
                        realice en este sitio, ellas aparecerán en esta página señalada con un link o indicada como parte de la promoción de sus ofertas y promociones y se
                        entenderán como complementarias a estas.
                        <br/>
                        <br/>
                        <strong>2.</strong>
                        La página web <a href="http://www.rebueno.ec/">www.rebueno.ec</a> así como el sistema de venta de cupones en dicha página son gestionados por:
                    </p>
                    <p>
                        ECUADOR.COM
                        <br/>
                        xxxxxx
                        <br/>
                        Ecuador – Guayaquil
                        <br/>
                        Teléfono: 311 - XXXX
                        <br/>
                        E-mail: <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a>
                        <br/>
                        <br/>
                        <strong>3.</strong>
                        Ya sea mediante confirmación del correspondiente campo en el proceso de pedido, o bien si el usuario hace uso efectivo del servicio, quedarán aceptadas las
                        condiciones de uso de ECUADOR.COM. En tal caso, Usted reconoce que nosotros - ECUADOR.COM - consideremos el uso de nuestro servicio como reconocimiento de las
                        condiciones de uso. Estas condiciones de uso podrán ser consultadas, impresas o grabadas localmente en cualquier momento bajo
                        <a href="http://www.rebueno.ec/interes/terminos-y-condiciones">www.rebueno.ec/interes/terminos-y-condiciones</a>.
                    </p>
                    <p>
                        4. Los cupones sólo están disponibles para personas que tengan capacidad legal para contratar (mayores de 18 años de edad según la ley peruana). No podrán
                        adquirir los cupones las personas que no tengan esa capacidad y los menores de edad. Los actos que éstos realicen en el sitio serán responsabilidad de sus
                        padres, tutores, encargados o curadores, y por tanto se considerarán realizados por éstos en ejercicio de la representación legal con la que cuentan.
                        <br/>
                        <br/>
                        <strong>5. </strong>
                        Para adquirir los cupones ofrecidos en el sitio, los usuarios registrados deberán facilitar determinados datos de carácter personal. Su información
                        personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica.
                    </p>
                    <p>
                        ECUADOR.COM garantiza la confidencialidad de los datos suministrados por los usuarios de acuerdo con las normas legales aplicables e informa acerca del uso que
                        ECUADOR.COM hará de los datos de carácter personal que proporcionen los usuarios, para que los mismos determinen libre y voluntariamente si desean suministrar
                        a la ECUADOR.COM sus datos personales, en cualquier forma y a través de cualquier medio.
                    </p>
                    <p>
                        De conformidad con la Ley N° 29733, Ley de Protección de Datos Personales, desde el momento de su ingreso y/o utilización al sitio el usuario da
                        expresamente su consentimiento para el tratamiento de los datos personales que por el sean facilitados o que se faciliten a través de su ingreso al portal
                        o por cualquier medio. Asimismo, el usuario consiente expresamente que ECUADOR.COM pueda ceder los datos personales, a terceros en los términos y condiciones
                        señalados en esta página.
                    </p>
                    <p>
                        Los datos personales serán incorporados a la base de datos de titularidad de ECUADOR.COM. Estos datos serán utilizados en la gestión administrativa y comercial
                        de la petición de los usuarios.
                    </p>
                    <p>
                        Los datos se mantendrán en la base de datos mientras se consideren útiles con el fin que ECUADOR.COM pueda prestar y ofrecer sus servicios y darles trámite,
                        enviarle información y publicidad sobre las ofertas, promociones y recomendaciones de ECUADOR.COM.
                    </p>
                    <p>
                        En cuanto entre en vigencia las disposiciones pertinentes de la Ley de Protección de Datos Personales, al usuario le asiste de ejercer los derechos de
                        acceso, rectificación, oposición y cancelación de los datos personales, los cuales podrá ejercer mediante la opción de contacto que ponemos a su
                        disposición en esta página.
                    </p>
                    <p>
                        El titular de la cuenta es responsable de no mantener su sesión activa en un dispositivo al cual otro usuario podría tener acceso.
                        <br/>
                        <strong>
                            <br/>
                            6.
                        </strong>
                        ECUADOR.COM podrá modificar estos términos y condiciones de uso, por ejemplo, para poner en práctica cambios en la legislación peruana o tener en cuenta
                        modificaciones sobre su funcionamiento o sobre políticas de atención. El usuario encontrará las condiciones de uso vigentes en cada momento bajo
                        <a href="http://www.rebueno.ec/interes/terminos-y-condiciones">http://www.rebueno.ec/interes/terminos-y-condiciones</a>. En caso de que no estuviera de acuerdo con las modificaciones de nuestras condiciones de uso, el usuario
                        podrá optar por no hacer uso de nuestro servicio.
                        <br/>
                        <br/>
                        <strong>7.</strong>
                        Para la compra de un cupón en <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>, el usuario deberá:
                        <br/>
                        <br/>
                        <strong>7.1.</strong>
                        Confirmar el botón "comprar" en la página inicial.
                        <br/>
                        <strong>7.2.</strong>
                        Elija el número deseado de cupones.
                        <br/>
                        <strong>7.3.</strong>
                        Introduzca su nombre y su email, así como los datos de su tarjeta de crédito.
                        <br/>
                        <strong>7.4.</strong>
                        Su declaración de voluntad de compra queda emitida mediante la confirmación de las condiciones de uso y presión del botón "comprar". La aceptación del
                        contrato de compraventa por parte de ECUADOR.COM tiene lugar con la confirmación en forma de envío de un código del cupón.
                        <br/>
                        <strong>7.5. </strong>
                        Imprima el cupón y hágalo efectivo en el correspondiente establecimiento del socio o, en su caso, ante dicho socio.
                        <br/>
                        <strong>7.6.</strong>
                        El pago por parte del usuario será automático, así como la remisión del cupón adquirido, no siendo necesario que transcurra el período del descuento y/o se
                        alcance el número mínimo de participantes.
                        <br/>
                        <strong>7.7.</strong>
                        La venta del cupón no se produce hasta que ECUADOR.COM no haya registrado con éxito el cobro. En caso de no tener éxito con el primer intento de cobro (por ej.
                        porque no exista la cuenta indicada o no disponga de saldo suficiente, el número de la tarjeta de crédito sea erróneo o la misma esté al límite) tampoco se
                        producirá la venta del cupón.
                        <br/>
                        <strong>7.8.</strong>
                        Todos los cupones están dotados de un claro números de código, que deberá validarse en el sistema aprobado por ECUADOR.COM y del cual el socio dispone, cuando
                        se presentan los cupones para hacerlos efectivos. El cupón es transmisible. No se autoriza la reproducción, edición o manipulación de los cupones. En caso
                        de sospecha fundada de reproducción ilícita, ECUADOR.COM se reserva el derecho de transmitir los datos archivados al socio respectivo e iniciar las acciones
                        legales pertinentes.
                        <br/>
                        <strong>7.9.</strong>
                        En la medida en que no se indique lo contrario, el cupón no concede un derecho a hacer uso de prestaciones o a la adquisición de mercancías en un momento
                        concreto. Por ello, el usuario debe acordar individual y directamente con el socio el momento de realización de la prestación.
                        <br/>
                        <strong>7.10.</strong>
                        En caso de que en el cupón figure un período de vigencia, el cupón sólo podrá hacerse efectivo frente al socio dentro de ese período de vigencia. Una vez
                        transcurrido el período de vigencia, el cupón pierde su validez y no podrá hacerse efectivo bajo ninguna circunstancia.
                        <br/>
                        <strong>7.11</strong>
                        . El stock es limitado. Todo pago realizado luego de agotado el stock no se considerará válido y sera reembolsado al cliente en su totalidad. Ejemplo: Si
                        el stock es de 10 unidades y 20 personas han accedido a la promoción( hacen click en la opción de compra y son redirigidos a la pasarela de
                        Visa/MC/ScotiaBank), solamente los 10 primeros cobros serán considerados como beneficiarios de la oferta. A los 10 restantes, por haberse agotado el
                        stock, se les reembolsara su dinero.
                        <br/>
                        <br/>
                        <strong>8. </strong>
                        Información sobre el derecho de revocación
                        <br/>
                        <strong>8.1.</strong>
                        Si el usuario es consumidor, podrá revocar la declaración contractual de compra del cupón en el plazo de dos (2) semanas sin necesidad de indicar las
                        causas, comunicándolo por escrito (ej. carta o correo electrónico) o mediante el reenvío del cupón. El plazo comienza tras la recepción de cupón por el
                        destinatario, nunca antes de la recepción del mismo. Para que se considere cumplido el plazo de revocación bastará que el envío de la revocación y/o del
                        cupón haya tenido su salida puntualmente dentro de dicho plazo.
                        <br/>
                        <strong>8.2. </strong>
                        Una vez hecho efectivo el cupón frente al SOCIO, ya no es posible la revocación.
                        <br/>
                        <strong>8.3.</strong>
                        La revocación debe dirigirse a la dirección electrónica: <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a> o carta dirigida a ECUADOR.COM, a la dirección: Jr. Gonzales Olaechea 446-448, San
                        Isidro. Lima. Perú.
                        <br/>
                        <strong>8.4.</strong>
                        Consecuencias de la revocación:
                        <br/>
                        En el caso de una revocación eficaz, se han de restituir las prestaciones recibidas por ambas partes y, en su caso, entregar los frutos o utilidades
                        percibidos (ej. ventajas de uso). Las obligaciones de devolución de pagos han de cumplirse en el plazo máximo de treinta (30) días. El plazo comienza para
                        el usuario con la salida del envío de su declaración de revocación o de su vale, y para ECUADOR.COM, con su recepción.
                    </p>
                    <p>
                        Como una medida de protección a la seguridad de las transacciones, ECUADOR.COM se reserva el derecho de dejar sin efecto las compras que se realicen, en caso
                        los datos entregados por el cliente no coincidan con las bases de datos disponibles de ECUADOR.COM o aquellas en las que el Banco emisor registre como
                        transacción no reconocida por el dueño de la tarjeta de crédito. ECUADOR.COM podrá contactar al titular de la cuenta, y comunicar este hecho; en caso de no
                        obtener respuesta al respecto, se comunicará al Banco emisor sobre la tarjeta de crédito utilizada por el consumidor al momento de enviar su solicitud de
                        compra. El Banco emisor de la tarjeta de crédito que se utilizó para realizar la compra en el sitio, deberá proceder con la devolución del importe de
                        acuerdo con sus Políticas. ECUADOR.COM no se responsabiliza en ningún caso por la no devolución de dinero utilizado a través de tarjetas de crédito en las
                        situaciones antes mencionada.
                        <br/>
                        Adicionalmente, en cumplimiento a las normas de prevención del lavado de activos y cuando lo estime conveniente, ECUADOR.COM podrá solicitar al Usuario
                        diversos documentos e información adicional, respecto a su identificación y/o datos personales.
                    </p>
                    <p>
                        <strong>9. </strong>
                        Atención de reclamos
                        <br/>
                        Todo <strong>reclamo o queja</strong> será atendido dentro de los <strong>30 días calendario</strong> de presentado. Dicho plazo será extendido por otro
                        igual si el reclamo o queja lo justifican, previa comunicación al cliente antes de la culminación del plazo inicial. El reclamo o queja será presentado a
                        través del formulario del Libro de Reclamaciones ubicado en la página web de Rebueno: <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>
                    </p>
                    <p>
                        <strong>10. </strong>
                        Créditos
                        <br/>
                        El <strong>crédito a favor</strong> del cliente en Rebueno podrá utilizarse:
                    </p>
                    <ul>
                        <li>
                            <p>
                                Para compras de montos menores, quedando el saldo disponible para futuras compras.
                            </p>
                        </li>
                        <li>
                            <p>
                                Para compras de montos iguales.
                            </p>
                        </li>
                        <li>
                            <p>
                                Para compras de montos mayores, pagando la diferencia a través de cualquier medio de pago, salvo que este se encuentre fijado a ciertas condiciones
                                y restricciones que serán previamente comunicadas al cliente.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>11.</strong>
                        Reservas en los establecimientos:
                    </p>
                    <ul>
                        <li>
                            <p>
                                Los clientes deben sujetarse a las condiciones y restricciones de la promoción, sea de productos o servicios (paquetes turísticos, pasajes aéreos,
                                etc.) indicadas en el cupón.
                            </p>
                        </li>
                        <li>
                            <p>
                        <u>
                            Todo cambio o reprogramación de fechas, horarios, destinos, etc. de las reservaciones de paquetes turísticos y/o pasajes aéreos deberán
                            realizarse con la debida anticipación y coordinarse directamente con el establecimiento o empresa señalada en el cupón. Estos cambios serán de
                            entera responsabilidad de los clientes por lo que Rebueno no se responsabiliza por los cambios realizados al respecto.
                        </u>
                        </p>
                        </li>
                        <li>
                            <p>
                                La cancelación de las reservas deberán realizarse según las especificaciones de cada oferta en particular, caso contrario el establecimiento y
                                Rebueno se reservan el derecho de invalidar ese cupón para uso posterior. Rebueno no participa de los acuerdos futuros entre el cliente y el
                                establecimiento ni se responsabiliza por ello.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>12.</strong>
                        Sobre las <strong>devoluciones y compensación a los clientes</strong>:
                        <br/>
                        <br/>
                    </p>
                    <p>
                        <strong>Todas las devoluciones o compensaciones a los clientes se realizarán en créditos Ofertop </strong>
                        <em><strong>(revisar políticas de Ofertas Específicas).</strong></em>
                    </p>
                    <p>
                        La vigencia para utilizar estos créditos es de <u>90 días calendario</u> desde la fecha de su activación.
                    <br/>
                    <br/>
                    </p>
                    <p>
                        Las devoluciones y compensaciones se aplican en los siguientes casos:
                    </p>
                    <ul>
                        <li>
                            <p>
                                Por responsabilidad de Rebueno: devolución del 100% del monto pagado en crédito OFT.
                            </p>
                        </li>
                        <li>
                            <p>
                                Por responsabilidad del establecimiento: devolución del 100% del monto pagado en crédito OFT.
                            </p>
                        </li>
                        <li>
                            <p>
                                Por imposibilidad del cliente (cancelación del cupón): mientras el cupón esté vigente se devuelve el 50% en crédito OFT.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>
                            El cliente es responsable del uso del cupón dentro del plazo de vigencia indicado en el mismo.
                            <br/>
                            Después de la fecha de vencimiento del cupón no hay posibilidad de reclamo ni devolución alguna.
                        </strong>
                    </p>
                    <p>
                        <strong>13.</strong>
                        Ofertas específicas:
                    </p>
                    <p>
                        <strong>13.1</strong>
                        Cupones de Eventos: Las compras sobre ofertas de eventos (cine, teatro, espectáculos, conciertos, tours, etc.) no tienen derecho a devolución en ningún
                        caso. Todo cupón de eventos comprado será validado inmediatamente y el no uso del cupón por parte del cliente hace que pierda su dinero sin derecho a
                        reclamo.
                    </p>
                    <p>
                        <strong>13.2</strong>
                        Cupones de Viajes: Las compras sobre ofertas de viajes y/o paquetes turísticos no son reembolsables en caso de cancelación por parte del cliente. Todo
                        cambio o reprogramación de fechas, horarios, destinos, etc. de viajes y/o paquetes turísticos deberán realizarse con la debida anticipación y coordinarse
                        directamente con el establecimiento o empresa señalado en el cupón. Estos cambios serán de entera responsabilidad de los clientes por lo que Rebueno no se
                        responsabiliza por los cambios realizados al respecto.
                    </p>
                    <p>
                        <strong>13.3</strong>
                        Pagos extras al establecimiento: Todos aquellos pagos adicionales al cupón Rebueno que el cliente realice en el establecimiento, serán coordinados entre el
                        establecimiento y el cliente. Rebueno no se responsabilizará por estos pagos extras.
                    </p>
                    <p>
                        <strong>13.4</strong>
                        Ofertop Productos: Todas las compras de Ofertop Productos no están sujetas a devoluciones ni cancelaciones por parte del cliente.
                        <br/>
                        Los productos adquiridos a través de la web Ofertop se sujetarán a las condiciones de despacho y entrega estipuladas en el cupón (entre 4 a 10 días útiles
                        según corresponda).
                        <br/>
                        Tratándose de productos ECUADOR.COM los cuales por sus características tengan fecha de vencimiento, se entregarán sólo en el plazo de 30 días calendario desde
                        la fecha en que se estuvo publicada la oferta en <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>. Transcurrido dicho lapso de tiempo, el cliente
                        pierde el derecho a reclamar el producto y la devolución del dinero.
                        <br/>
                        Respecto a los demás productos, el cliente podrá recogerlo hasta la fecha de vencimiento estipulada en cada oferta. Caso contrario, al igual que en la
                        situación anterior, se perderá el derecho a reclamar y/o solicitar la devolución del dinero.
                        <br/>
                        Podrás gestionar la garantía del producto directamente con Rebueno, siempre y cuando sea dentro de los 07 días útiles después de haber recogido el producto
                        y previa evaluación de Rebueno. En este caso, nosotros nos encargaremos de contactar al proveedor y supervisar el cumplimiento de la misma, en caso se
                        requiera algún cambio o devolución. Para realizar la entrega de productos para la garantía es necesario dejar el mismo en su empaque original, incluyendo
                        todos los accesorios entregados en perfecto estado, con la boleta de venta y dentro del plazo fijado (hasta 07 días útiles después de haber recogido su
                        producto).
                        <br/>
                        Transcurrido este plazo, podrás gestionar la garantía directamente con el proveedor. Podrás solicitar los datos del mismo a Rebueno.
                        <br/>
                        Todo cambio de producto está sujeto a stock disponible. En caso no haya stock para el cambio, Rebueno te devolverá el íntegro de tu dinero, previa
                        evaluación de cada caso.
                        <br/>
                        Cuando existan productos ECUADOR.COM que incluyan delivery, la información del lugar de envío es de exclusiva responsabilidad del USUARIO. Los plazos elegidos
                        para el despacho y entrega, se cuentan desde que se ingresaron los datos a la web de delivery, y se consideran días hábiles(útiles) para el cumplimiento de
                        dicho plazo.
                    </p>
                    <p>
                        <strong>14.</strong>
                        La duración de la promoción de un cupón está limitada temporalmente, estableciéndose de forma individual para cada descuento por parte de ECUADOR.COM.
                        Transcurrido el período de duración y/o unidades disponibles ya no es posible la compra, dándose por concluida la promoción. En ese sentido, los usuarios
                        se sujetan a las condiciones y restricciones de cada promoción, sea de productos o servicios indicadas en el cupón respectivo.
                    </p>
                    <p>
                        <strong>15.</strong>
                        En la medida en que no se indique lo contrario, podrá hacerse uso de cada cupón una sola vez, haciéndolo efectivo frente al socio acudiendo al
                        establecimiento correspondiente o participando en cualquier otro acontecimiento (o percibiendo cualquier otra mercancía). En caso de que no se consumiera
                        totalmente el valor del cupón o no se hiciera uso de toda la prestación, dentro del plazo establecido, caduca la diferencia no utilizada. No es posible el
                        reembolso en estos casos.
                    </p>
                    <p>
                        <strong>16.</strong>
                        ECUADOR.COM garantiza que el socio realizará las prestaciones con arreglo a las condiciones certificadas en el cupón, siempre y cuando el usuario presente el
                        cupón conforme a los términos y condiciones indicadas en el mismo y antes del inicio de la realización de la prestación. ECUADOR.COM no está obligada a
                        realizar reembolsos y/o indemnizaciones por daños y perjuicios derivados de la negligencia del usuario para recibir las prestaciones del cupón. ECUADOR.COM no
                        asume garantía alguna por los productos o servicios del socio adquiridos por el usuario. El socio respectivo realiza la prestación certificada en el cupón
                        en nombre propio y por cuenta propia frente al usuario, por lo que ECUADOR.COM no responde frente al usuario por incumplimiento de obligaciones del socio en el
                        momento de realizar la prestación. En caso de que surgieran problemas a la hora de hacer efectivo el cupón o de realizar la prestación, ECUADOR.COM intervendrá
                        como conciliador entre el socio y el usuario para encontrar una solución. En tal caso, los usuarios deberán comunicarse al correo: <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a> o
                        contactarse con ECUADOR.COM por vía telefónica.
                        <br/>
                        <br/>
                        <strong>17.</strong>
                        ECUADOR.COM se reserva el derecho de modificar en cualquier momento el alcance y las funciones de su página web, o de limitarlas o cancelarlas. Aunque nos
                        esforzamos por ofrecer nuestro servicio sin molestias técnicas, en particular, los trabajos de mantenimiento, la continuación del desarrollo y/o fallas
                        técnicas pueden limitar y/o parcialmente interrumpir las posibilidades de uso. Bajo determinadas circunstancias se pueden producir aquí pérdidas de datos.
                        ECUADOR.COM no asume por ello garantía alguna sobre la disponibilidad del servicio o la presencia de fallas técnicas o pérdidas de datos y en particular, no
                        tiene responsabilidad por:
                    </p>
                    <p>
                        17.1 El uso o falta de acceso a la página, las fallas, errores, omisiones o continuidad en el funcionamiento, utilidad y fiabilidad de los servicios y de
                        la página; la alteración de la privacidad y seguridad en la utilización y contenidos de la página y de los servicios por terceros ajenos a los mismos de
                        acuerdo con el régimen legal vigente; la presencia de virus o a la presencia de otros elementos falsos en los servicios ofrecidos por terceros a través de
                        la página que puedan producir alteraciones en el sistema informático (hardware y software); la falta de veracidad, exactitud, exhaustividad y actualidad de
                        los contenidos ofrecidos en la página; la información, contenidos y servicios alojados fuera de la página, aunque fueran accesibles desde esta;
                        <br/>
                        17.2 La falta de disponibilidad y continuidad en el funcionamiento, utilidad y fiabilidad de los servicios y de la página de terceros colaboradores de
                        ECUADOR.COM.
                        <br/>
                        <br/>
                        <strong>18.</strong>
                        ECUADOR.COM y los socios se reservan todos los derechos de Propiedad Intelectual y demás derechos sobre el servicio así como sobre los contenidos publicados,
                        informaciones, imágenes, videos y bancos de datos (a continuación denominada "propiedad protegida"). Por ello, está expresamente prohibida cualquier
                        modificación, reproducción, publicación, transmisión a terceros y/o demás uso o explotación de la propiedad protegida sin el consentimiento previo por
                        escrito de ECUADOR.COM o del socio respectivamente afectado.
                        <br/>
                        <br/>
                        <strong>19.</strong>
                        No está permitida ninguna acción o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de ECUADOR.COM como
                        en las ofertas, descripciones, cuentas o bases de datos de ECUADOR.COM. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre
                        derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes,
                        así como lo hará responsable de indemnizar los daños ocasionados.
                        <br/>
                        <br/>
                        <strong>20.</strong>
                        En caso de que disposiciones concretas de estas Condiciones Generales de Contratación o del contrato concluido con la parte contratante fueran ineficaces
                        en todo o en parte, ello no afectará a la eficacia del resto del contrato.
                        <br/>
                        <br/>
                        <strong>21.</strong>
                        Estos Términos y Condiciones se rigen por la ley peruana, y cualquier divergencia o discrepancia derivada de su interpretación, aplicación y ejecución será
                        sometida a un arbitraje de derecho, llevada a cabo por árbitro único, siendo el respectivo laudo definitivo e inapelable. Dicho arbitraje será efectuado
                        por el Centro de Arbitraje de la Cámara de Comercio de Lima y se regirá por los reglamentos arbitrales de dicha institución, cuyas normas y condiciones las
                        partes declaran conocer y someterse de manera expresa e incondicional, para lo cual renuncian expresamente a su propio fuero. El árbitro único será
                        designado por las instancias competentes del Centro de Arbitraje de la Cámara de Comercio de Lima.
                        <br/>
                    </p>
                    <p align="CENTER">
                        <strong>POLITICAS ECUADOR.COM DELIVERY</strong>
                    </p>
                    <p>
                        1. Los horarios para el delivery de productos Ofertop son de lunes a viernes de 9:00 a.m. a 6:00 p.m.
                    </p>
                    <p>
                        No se efectuarán entregas los días feriados. Las entregas de campañas especiales tienen los siguientes horarios: de 8:00 a.m a 2:00 p.m. Estos horarios y las campañas para las que aplican se comunicarán oportunamente y se indicarán en cada una de las ofertas que participe en la campaña en cuestión.
                        <br/>
                        <br/>
                        2. Para acceder al servicio de delivery, el cliente deberá ingresar sus datos requeridos en el momento de comprar. De no ingresar los datos no permitirá realizar le servicio de manera correcta.
                        <br/>
                        <br/>
                        3. Para el servicio de delivery el cliente deberá facilitar la información necesaria para realizar la entrega. La dirección de envío y las referencias
                        registradas por el usuario <u>serán de exclusiva responsabilidad del mismo. </u>Cualquier error de ingreso de datos por parte del cliente, ocasionará que
                    el Delivery no pueda ser concretado.
                    <br/>
                    <br/>
                    4. Las entregas se realizarán dentro del área de Lima Metropolitana. Salvo, casos especiales que serán indicados dentro de las condiciones de la oferta. <br/><br/>
                    Las zonas establecidas son: Barranco, Bellavista, Breña, Callao, Carmen de la Legua, El Agustino, Jesús Maria, La Molina, La Perla, La Punta, La Victoria, Lima, Lince, Magdalena del Mar, Miraflores, Pueblo Libre, Rímac, San Borja, San Isidro, San Luis, San Miguel, Santiago de Surco y Surquillo; salvo zonas que tengan alguna restricción de ingreso.<br/><br/>
                    Zonas que consideramos alejadas y/o peligrosas: <br/><br/>
                    RIMAC: San Juan de Amancaes, Flor de Amancaes, Piedra Liza por el Cerro San Cristóbal<br><br/>
                    LA VICTORIA: Todo Manzanilla, cerro El Pino y aledaños, calle San Pablo<br><br/>
                    CALLAO: Barracones por José Gálvez, Vigil, Sarita Colonia, 200 Millas, Morales Duárez del 1 al 20 del Callao, Av. Buenos Aires


                    <br/>
                    <br/>
                    5.     La entrega del producto se realizará  de acuerdo al plazo establecido en la misma oferta, contando días útiles, a partir de que el cliente realice su compra y registre sus datos de Envío. De no haberse cumplido con el registro correcto de los datos del cliente, Ofertop se reserva el derecho de suspender el servicio de delivery. Si el cliente no logró acceder a registrar sus datos en un plazo no mayor a 48 horas deberá escribir a <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a> para reportar el hecho y recibir asistencia. Esto deberá realizarse en no más de 48 horas luego de haber realizado su compra.
                    <br/>
                    <br/>
                    6.   El envío no es nominativo y cualquier persona, mayor de 18 años y debidamente documentada (DNI), podrá recibirlo. Para recibir el producto es obligatorio contar con el cupón de Rebueno impreso y copia del DNI si no es el titular. Esta a su vez deberá firmar en señal de conformidad la Guía de Entrega correspondiente. No se entregará el producto a personas que se nieguen a firmar esta Guía o que no cuenten con su DNI al momento de la entrega. La recepción del producto indica conformidad del estado.
                    <br/>
                    <br/>
                    7.     El servicio de delivery se realizará en un solo intento. De no poder realizarse la entrega, el cliente deberá escribir un correo electrónico a <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a> y coordinar el recojo del producto en el almacén de Union Star, ubicado en Jr. Las Orquideas N° 2632 (altura cdra. 4 de Javier Prado Este) en los horarios de lunes a viernes de 9:00 a.m. a 7:00 p.m, sábados de 9:30 a.m. a 12:30 m. El producto estará sujeto a disponibilidad. En ningún caso el servicio de delivery podrá ser reprogramado y tampoco <u>se podrán aplicar devoluciones asociadas al pago del delivery.</u>
                    <br/>
                    <br/>
                    8.     Los productos Ofertop no están sujetos a devoluciones. En caso de fallas en el producto, el cliente deberá <u>(en un plazo de 07 días útiles desde la fecha en que se registra la entrega del producto)</u> comunicarse con Ofertop y hacer la solicitud del mismo. En ningún caso, la empresa de delivery realiza cambios de productos, este servicio sólo entregará el producto sellado y cerrado.
                    </p>

                    <!-- FIN -->
                </div>
            </div>

            <div class="accordion">
                <div class="header">
                    <h2>Campañas promocionales</h2><span></span>
                    <hr class="medium">
                </div>
            </div>
            <div class="container">
                <div class="content">
                    <!-- VACACIONES SOÑADAS -->
                    <p>
                        <strong>BASES DE LA PROMOCIÓN: 35% DE DEVOLUCIÓN PAGANDO A TRAVÉS DE PAGOEFECTIVO EN LOS SUMMER DAYS</strong>
                    </p>
                    <p>
                        La devolución aplica para todas las compras pagadas a través de Pago Efectivo durante los SUMMER DAYS, desde las 00:00 horas del 28 de enero hasta 23:59 horas del 29 de enero de 2015 o hasta agotar stock. 
                        <br/><br/>
                        Promoción válida hasta agotar el fondo de la promoción de S/. 10,000
                        <br/><br/>
                        Si la compra se realizó cuando la promoción u oferta se hubiese terminado, no procederá la devolución. 
                        <br/><br/>
                        La devolución del 35% en crédito Rebueno se efectuará sobre el importe pagado a través de Pago Efectivo. 
                        <br/><br/>
                        Participan solo compras pagadas al 100% a través de Pago Efectivo. 
                        <br/><br/>
                        No participan compras pagadas de forma mixta, ya sea con créditos Rebueno + Pago Efectivo, o con tarjetas de crédito o débito + Pago Efectivo.
                        <br/><br/>
                        Monto máximo de devolución por compra: S/. 50.00
                        <br/><br/>
                        El crédito Rebueno solo podrá ser usado para compras en la página www.Rebueno.pe dentro de los 30 días posteriores luego de realizado el abono de los mismos en la cuenta del cliente registrada en Rebueno.
                        <br/><br/>
                        Luego de pasados los 30 días, el crédito no consumido se eliminará automáticamente y no será sujeto a reposición ni devolución. 
                        <br/><br/>
                        El crédito Rebueno no podrá ser cambiado por dinero en efectivo. El crédito no aplica para comprar opciones de Me la Juego.
                        <br/><br/>
                        La devolución en crédito se depositará en la cuenta Rebueno del cliente dentro de los 10 días útiles después de realizada la compra. 
                        <br/><br/>
                        La devolución del 35% en crédito Rebueno no es acumulable con otras promociones. 
                        <br/><br/>
                        Rebueno y Pago Efectivo se reservan el derecho de darle de baja a la promoción en cualquier momento de la campaña. 
                        <br/><br/>
                        Para verificar la validación del crédito ingresa a tu cuenta en <a href="http://www.rebueno.ec">www.rebueno.ec</a>
                        <br/><br/>
                    </p>

                    <!-- VACACIONES SOÑADAS -->
                    <p>
                        <strong>PROMOCIÓN "VACACIONES SOÑADAS" CON PAGOEFECTIVO</strong>
                    </p>
                    <p>
                        Para participar en la presente promoción los participantes deberán realizar una compra con PAGOEFECTIVO en cualquiera de sus comercios afiliados. Al hacerlo y cumplir todos los pasos de compra, ingresarán al sorteo de tres (03) premios. Todas las compras realizadas desde 15 de Diciembre (00:00hrs) de 2014 al 31 de Enero (23:59hrs) de 2015 participan e ingresan al sorteo de la fecha indicada. Los códigos CIP que tengan fecha de pago Febrero 2015 no serán considerados. Participan todas las compras con PAGOEFECTIVO iguales o mayores a PEN s/. 80.00. Esta promoción es exclusiva para clientes que compren con PAGOEFECTIVO. Participan clientes nuevos, así como todos los que hicieron compras por primera vez. Una vez que el cliente ha finalizado la compra, ingresará automáticamente al sorteo con una opción de ganar. Cada compra/transacción con PAGOEFECTIVO es una opción más para ganar, a más compras, mayor oportunidad de ganar.
                        <br/><br/>
                        1er premio: Colombia para 2, hotel y pasajes, all included, Decameron San Andrés. 2do premio: Consola PlayStation4 500G. 3er premio: Vale de compra por S/.500 en Linio y Ofertop (S/.250 c/u).
                        <br/><br/>
                        El sorteo se realizará el día 04 de Febrero de 2015 a las 12:00 horas. El premio no es transferible, ni endosable. No esta sujeto a devolución en crédito ni en efectivo.
                        <br/><br/>
                    </p>
                    <!-- GRATI DAYS -->
                    <p>
                        <strong>BASES DE LA PROMOCIÓN: 35% DE DEVOLUCIÓN PAGANDO A TRAVÉS DE PAGO EFECTIVO EN LOS GRATI DAYS</strong>
                    </p>
                    <p>
                        La devolución aplica para todas las compras pagadas a través de Pago Efectivo durante los GRATI DAYS 2014, desde las 00:00 horas hasta 23:59 horas del 10 de diciembre de 2014 o hasta agotar stock.
                        <br/><br/>
                        Promoción válida hasta agotar el fondo de la promoción de S/. 5,000
                        <br/><br/>
                        Si la compra se realizó cuando la promoción u oferta se hubiese terminado, no procederá la devolución.
                        <br/><br/>
                        La devolución del 35% en crédito Rebueno se efectuará sobre el importe pagado a través de Pago Efectivo.
                        <br/><br/>
                        Participan solo compras pagadas al 100% a través de Pago Efectivo.
                        <br/><br/>
                        No participan compras pagadas de forma mixta, ya sea con créditos Rebueno + Pago Efectivo, o con tarjetas de crédito o débito + Pago Efectivo.
                    </p>
                    <p>
                        <strong>Monto máximo de devolución por compra: S/. 50.00</strong>
                    </p>
                    <p>
                        El crédito Rebueno solo podrá ser usado para compras en la página <a href="http://www.rebueno.ec">www.Rebueno.pe</a> dentro de los 30 días posteriores luego de realizado el abono de los mismos en la cuenta del cliente registrada en Rebueno.
                        <br/><br/>
                        Luego de pasados los 30 días, el crédito no consumido se eliminará automáticamente y no será sujeto a reposición ni devolución.
                        <br/><br/>
                        El crédito Rebueno no podrá ser cambiado por dinero en efectivo.
                        <br/><br/>
                        La devolución en crédito se depositará en la cuenta Rebueno del cliente dentro de los 10 días útiles después de realizada la compra.
                        <br/><br/>
                        La devolución del 35% en crédito Rebueno no es acumulable con otras promociones.
                        <br/><br/>
                        Rebueno y Pago Efectivo se reservan el derecho de darle de baja a la promoción en cualquier momento de la campaña.
                        <br/><br/>
                        Para verificar la validación del crédito ingresa a tu cuenta en <a href="http://www.rebueno.ec">www.rebueno.ec</a>
                        <br/><br/>
                    </p>
                    <!-- cyber monday 50%-->
                    <p>
                        <strong>BASES DE LA PROMOCIÓN: 50% DE DEVOLUCIÓN PAGANDO A TRAVÉS DE PAGO EFECTIVO EN EL BLACK FRIDAY 2014</strong>
                    </p>
                    <p>
                        La devolución aplica para todas las compras pagadas a través de Pago Efectivo durante EL BLACK FRIDAY 2014, desde las 00:00 horas hasta 23:59 horas del viernes 28 de noviembre de 2014 o hasta agotar stock.
                        <br/><br/>
                        Promoción válida solo hasta agotar el fondo de la promoción de S/. 5,000
                        <br/><br/>
                        Si la compra se realizó cuando la oferta se hubiese terminado, no procederá la devolución.
                        <br/><br/>
                        La devolución del 50% en crédito Rebueno se efectuará sobre el importe pagado a través de Pago Efectivo.
                        <br/><br/>
                        Participan solo compras pagadas al 100% a través de Pago Efectivo.
                        <br/><br/>
                        No participan compras pagadas de forma mixta, ya sea con créditos Rebueno + Pago Efectivo, o con tarjetas de crédito o débito + Pago Efectivo.
                        <br/><br/>
                        <strong>Monto máximo de devolución: S/. 50.00</strong>
                        <br/><br/>
                        El crédito Rebueno solo podrá ser usado para compras en la página <a href="http://www.rebueno.ec">www.Rebueno.pe</a> dentro de los 30 días posteriores luego de realizado el abono de los mismos en la cuenta del cliente registrada en Rebueno.
                        <br/><br/>
                        Luego de pasados los 30 días, el crédito no consumido se eliminará automáticamente y no será sujeto a reposición ni devolución.
                        <br/><br/>
                        El crédito Rebueno no podrá ser cambiado por dinero en efectivo.
                        <br/><br/>
                        La devolución en crédito se depositará en la cuenta Rebueno del cliente dentro de los 10 días útiles después de realizada la compra.
                        <br/><br/>
                        La devolución del 50% en crédito Rebueno para pagos con Pago Efectivo no es acumulable con otras promociones.
                        <br/><br/>
                        Rebueno y Pago Efectivo se reservan el derecho de darle de baja a la promoción en cualquier momento de la campaña.
                        <br/><br/>
                        Para verificar la validación del crédito ingresa a tu cuenta en <a href="http://www.rebueno.ec">www.rebueno.ec</a>

                    </p>
                    <!-- cyber monday 35%-->
                    <p>
                        <strong>BASES DE LA PROMOCIÓN: 35% DE DEVOLUCIÓN PAGANDO A TRAVÉS DE PAGO EFECTIVO EN EL CYBER MONDAY 2014</strong>
                    </p>
                    <p>
                        La devolución aplica para todas las compras pagadas a través de Pago Efectivo durante el CYBER MONDAY 2014, del martes 25 de noviembre desde las 00:00 horas hasta la medianoche del martes 25 de noviembre de 2014 o hasta agotar stock.<br/><br/>
                        Promoción válida solo hasta agotar el fondo de la promoción de S/. 5,000<br/><br/>
                        Si la compra se realizó cuando la oferta se hubiese terminado, no procederá la devolución. <br/><br/>
                        La devolución del 35% en crédito Rebueno se efectuará sobre el importe pagado a través de Pago Efectivo.<br/><br/>
                        Participan solo compras pagadas al 100% a través de Pago Efectivo.<br/><br/>
                        No participan compras pagadas de forma mixta, ya sea con créditos Rebueno + Pago Efectivo, o con tarjetas de crédito o débito + Pago Efectivo.<br/><br/>
                        Monto máximo de devolución: S/. 50.00<br/><br/>
                        El crédito Rebueno solo podrá ser usado para compras en la página <a href="http://rebueno.ec">www.Rebueno.pe</a> dentro de los 30 días posteriores luego de realizado el abono de los mismos en la cuenta del cliente registrada en Rebueno.<br/><br/>
                        Luego de pasados los 30 días, el crédito no consumido se eliminará automáticamente y no será sujeto a reposición ni devolución.<br/><br/>
                        El crédito Rebueno no podrá ser cambiado por dinero en efectivo.<br/><br/>
                        La devolución en crédito se depositará en la cuenta Rebueno del cliente dentro de los 10 días útiles después de realizada la compra.<br/><br/>
                        La devolución del 35% en crédito Rebueno para pagos con Pago Efectivo no es acumulable con otras promociones.<br/><br/>
                        Rebueno y Pago Efectivo se reservan el derecho de darle de baja a la promoción en cualquier momento de la campaña.<br/><br/>
                        Para verificar la validación del crédito ingresa a tu cuenta en <a href="http://rebueno.ec">www.rebueno.ec</a>
                    </p>
                    <!--REEMPLAZAR -->

                    <p>
                        <strong>PROMOCIÓN DEVOLUCIÓN 30% SHOPIN-PAGOEFECTIVO</strong>
                    </p>
                    <p>
                        La devolución aplica para todas las compras pagadas a través de Pago Efectivo del lunes 29 de setiembre desde la 00:00hrs. hasta el martes 30 de setiembre
                        de 2014 a las 23:59:59hrs o hasta agotar fondo promoción S/.20,000, lo que ocurra primero
                        <br/>
                        Participan solo compras pagadas al 100% a través de PAGOEFECTIVO.
                        <br/>
                        La devolución del 30% se efectuará sobre el importe a pagar utilizando
                    </p>

                    <p>
                        <strong>PAGOEFECTIVO</strong>
                    </p>
                    <p>
                        La devolución máxima por transacción utilizando PAGOEFECTIVO será de <strong>PEN S/. 50.00</strong>
                    </p>
                    <p>
                        No participan compras pagadas de forma mixta, ya sea con créditos Rebueno + Pago Efectivo, o con tarjetas de crédito o débito + Pago Efectivo.
                        <br/>
                        La devolución del 30% en crédito Rebueno para pagos con Pago Efectivo no es acumulable con otras promociones.
                        <br/>
                        El crédito Rebueno solo podrá ser usado para compras en la página www.Rebueno.pe dentro de los 30 días posteriores luego de realizado el abono de los mismos en la cuenta del cliente registrada en Rebueno.
                        <br/>
                        Luego de pasados los 30 días, el crédito no consumido se eliminará automáticamente y no será sujeto a reposición ni devolución.
                        <br/>
                        El crédito Rebueno no podrá ser cambiado por dinero en efectivo.
                        <br/>
                        La devolución en crédito se depositará en la cuenta Rebueno del cliente dentro de los 10 días útiles después de realizada la compra.
                        <br/>
                        Rebueno y Pago Efectivo se reservan el derecho de darle de baja a la promoción en cualquier momento de la campaña.
                        <br/>
                        Para verificar la validación del crédito ingresa a tu cuenta en <a href="http://www.rebueno.ec">http://www.rebueno.ec</a>
                        <br/>
                        Para verificar la validez de la promoción ingresa a <a href="http://www.rebueno.ec">http://www.rebueno.ec</a>
                    </p>

                    <p>
                        <strong>Oferta Express / Días de Locura:</strong>
                    </p>
                    <p>
                        Las compras efectuadas a través de Ofertas Express y Días de Locura no son rembolsables en caso de cancelación por parte del cliente. Salvo, casos
                        especiales, previa evaluación por Rebueno.
                        <br/>
                        Cualquier Oferta Express estará disponible para comprar solo por 60 minutos o hasta agotar stock. Se inicia a las 10:00 a.m., y finaliza a las 11:00 a.m.
                        <br/>
                        Compra máxima: 1 ECUADOR.COM por persona.
                        <br/>
                        Stock limitado.
                    </p>

                    <p>
                        El horario y el stock señalado son los únicos fijados para acceder a la presente promoción; en tal sentido, todo acceso, compra o pago realizado fuera del
                        horario señalado y/o en caso se haya agotado el stock, no será considerado válido. En este último caso, se devolverá el dinero dentro de los 5 días útiles
                        de realizada la transacción. Sobre el particular, por ejemplo, si el stock de un determinado producto en Oferta Express es de diez (10) unidades y veinte
                        (20) personas han accedido a la promoción (hacen click incluso simultáneamente en la opción de compra y son redirigidos a la pasarela de Visa), solamente
                        las (diez) 10 primeras serán consideradas como beneficiarias con la oferta. Por ello, las compras restantes, por haberse agotado el stock, se les devolverá
                        el dinero dentro del plazo antes referido.
                    </p>
                    <p align="CENTER">
                    <u><strong>BASES – PROMOCIÓN “TU DÍA DE SUERTE”</strong></u>
                    </p>
                    <p>
                        <strong>1. OBJETO</strong>
                    </p>
                    <p>
                        La presente promoción denominada TU DÍA DE SUERTE, organizada por ECUADOR.COM (“ECUADOR.COM”) tiene por objeto otorgar crédito ECUADOR.COM a los participantes que
                        realicen compras exactamente igual al valor de la compra de productos o servicios en la página web de ECUADOR.COM (    <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>) de acuerdo a lo señalado en las presentes bases.
                    </p>
                    <p>
                        La presente promoción se rige por lo establecido en las presentes bases por lo que los participantes se someten y aceptan íntegramente las mismas para su
                        participación.
                    </p>
                    <p>
                        <strong>2. ÁMBITO TERRITORIAL</strong>
                    </p>
                    <p>
                        El ámbito territorial de la presente promoción es nacional.
                    </p>
                    <p>
                        <strong>3. DURACIÓN</strong>
                    </p>
                    <p>
                        La presente promoción tiene una duración de marzo de 2014 a diciembre de 2014.
                    </p>
                    <p>
                        <strong>4. MECÁNICA y CONDICIONES DE PARTICIPACIÓN</strong>
                    </p>
                    <ul>
                        <li>
                            <p>
                                Para participar en la presente promoción los participantes deberán ingresar, registrarse en la página web de ECUADOR.COM,            <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>, y efectuar una compra de productos o servicios desde el 29 de marzo de 2014 hasta el 25
                                de mayo de 2014 de acuerdo a los plazos de las compras indicados. Al hacerlo podrán entrar al sorteo por el premio en crédito ECUADOR.COM por el mismo
                                valor de su compra ganadora.
                            </p>
                        </li>
                        <li>
                            <p>
                                No hay monto mínimo de compra. Todas las compras realizadas desde el 29 de marzo de 2014 hasta el 25 de mayo de 2014 participan e ingresan al
                                sorteo de la fecha indicada.
                            </p>
                        </li>
                        <li>
                            <p>
                                No son válidas las acumulaciones de compras para varios sorteos en caso de no resultar favorecidos.
                            </p>
                        </li>
                        <li>
                            <p>
                                Cada compra representa 1 opción de ganar, así que a mayor número de compras, el participante obtendrá mayor número de opciones para ganar.
                            </p>
                        </li>
                        <li>
                            <p>
                                Los datos de todos los compradores que hayan realizado sus compras en los períodos de tiempo comprendidos en las fechas señaladas serán
                                incorporados automáticamente a una base de datos administrada por el organizador.
                            </p>
                        </li>
                        <li>
                            <p>
                                Los usuarios ya registrados en ECUADOR.COM previo al inicio del concurso, también podrán participar, con solo realizar una compra dentro de los plazos
                                de vigencia señalados.
                            </p>
                        </li>
                        <li>
                            <p>
                        <u><strong>Se elegirá un (1) ganador en cada uno de los sorteos.</strong></u>
                        </p>
                        </li>
                    </ul>
                    <p>
                        Los usuarios y visitantes a la página web de ECUADOR.COM (<a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>) podrán participar en el sorteo
                        registrándose en dicha página <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a> y realizando una compra de cualquier oferta en los períodos
                        señalados anteriormente.
                    </p>
                    <p>
                        Los participantes deberán ingresar sus datos personales (nombres y apellidos, DNI, dirección, distrito, correo electrónico y teléfono) al momento de hacer
                        la compra.
                    </p>
                    <p>
                        No se aceptarán nuevos participantes una vez finalizados los períodos de compra.
                    </p>
                    <p>
                        Los datos de todos los compradores que hayan realizado sus compras en el periodo de tiempo comprendido entre las fechas señaladas serán incorporados
                        automáticamente a una base de datos administrada por ECUADOR.COM.
                    </p>
                    <p>
                        Los ganadores serán elegidos vía un proceso aleatorio mediante software de ECUADOR.COM en la fecha del evento, para el respectivo sorteo.
                    </p>
                    <p>
                        ECUADOR.COM publicará el nombre de los ganadores en la página web <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>, mediante envío de un email a la
                        base de datos de ECUADOR.COM y en las cuentas de Facebook (<a href="http://www.facebook.com/RebuenoLima?fref=ts" target="_blank"><u>http://www.facebook.com/RebuenoLima?fref=ts</u></a>) y Twitter (    <a href="http://twitter.com/rebuenolima" target="_blank"><u>http://twitter.com/rebuenolima</u></a>) de ECUADOR.COM. Asimismo, los ganadores serán notificados mediante correo
                        electrónico y/o llamada telefónica de ECUADOR.COM.
                    </p>
                    <p>
                        Todas las dudas o inconvenientes no contempladas en las presentes bases, que se generen en el momento del evento serán resueltas por el Notario Público, el
                        representante del Ministerio del Interior y el representante de ECUADOR.COM y su fallo será inapelable.
                    </p>
                    <p>
                        <strong>5. PREMIOS</strong>
                    </p>
                    <p>
                        El ganador de cada sorteo recibirá un (1) premio equivalente al mismo valor de su compra ganadora en crédito ECUADOR.COM, para realizar futuras compras
                        exclusivamente en <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>.
                    </p>
                    <p>
                        El monto máximo de crédito otorgado a cada ganador por su compra ascenderá a S/. 100,00 (Cien y 00/100 Nuevos Soles). Las compras ganadoras con un monto
                        mayor a S/. 100,00 recibirán este monto máximo. No se otorgarán créditos máximos de S/. 100,00 como premios.
                    </p>
                    <p>
                        El premio será abonado en crédito ECUADOR.COM directamente en la cuenta que el ganador tenga registrada en    <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a> y desde la cual realizó la compra con la participó y ganó en el sorteo.
                        <br/>
                        El premio será abonado en crédito ECUADOR.COM inmediatamente, previa notificación al ganador.
                        <br/>
                        Cada ganador tendrá un plazo máximo de noventa (90) días calendario siguientes a la fecha del sorteo para reclamar el premio, previa coordinación en las
                        oficinas de ECUADOR.COM, ubicadas en Calle Gonzáles Olaechea N° 446-448, San Isidro, Lima; portando su DNI (original), pasaporte u otro documento que lo
                        acredite.
                    </p>
                    <p>
                        <strong>6. PARTICIPACIÓN</strong>
                    </p>
                    <p>
                        Pueden participar en la presente promoción, todos los peruanos y extranjeros residentes en el Perú con excepción de:
                    </p>
                    <ul>
                        <li>
                            <p>
                                Personas Jurídicas en general.
                            </p>
                        </li>
                        <li>
                            <p>
                                Menores de edad.
                            </p>
                        </li>
                        <li>
                            <p>
                                Trabajadores y sus familiares de línea directa (padres, cónyuge e hijos) de ECUADOR.COM.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>7. CONSIDERACIONES IMPORTANTES</strong>
                    </p>
                    <ul>
                        <li>
                            <p>
                                El premio no es acumulable, ni transferible, ni endosable. No está sujeto a devolución en efectivo.
                            </p>
                        </li>
                        <li>
                            <p>
                                El premio abonado en crédito ECUADOR.COM podrá hacerse efectivo dentro los 30 días calendarios posteriores a la fecha del abono al ganador. Pasado el
                                plazo señalado, y si el crédito no es utilizado, será puesto a disposición de la Dirección General de Gobierno Interior del Ministerio del
                                Interior.
                            </p>
                        </li>
                        <li>
                            <p>
                                Las compras realizadas en <a href="http://www.rebueno.ec">www.rebueno.ec</a> con crédito del premio no podrán ser vendidas, ni canjeadas a terceros. En ningún caso estarán sujetas a
                                devolución ni en crédito, ni en efectivo.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>8. RESPONSABILIDAD</strong>
                    </p>
                    <p>
                        ECUADOR.COM declara expresamente que actúa como intermediario por lo que no tendrá responsabilidad legal por cualquier daño o perjuicio que pudiera derivarse
                        de los servicios que ofrece el establecimiento proveedor (restaurantes, bares y/o discotecas) que participan de la presente promoción.
                    </p>
                    <p>
                        <strong>9. IMPUESTOS</strong>
                    </p>
                    <p>
                        ECUADOR.COM se compromete a asumir el pago de los impuestos de ley que le pudiera corresponder respecto a los premios ofrecidos, con excepción de los impuestos
                        del Sistema Financiero que son de cargo de cada ganador.
                    </p>
                    <p>
                        <strong>10. LEYES APLICABLES</strong>
                    </p>
                    <p>
                        Las presentes bases están sujetas a las leyes de la República del Perú.
                    </p>
                    <p>
                        <strong>
                            LISTADO DE GANADORES PROMOCIÓN TU DÍA DE SUERTE
                            <br/>
                        </strong>
                        Para ver el listado completo de ganadores a la fecha haz click <a href="http://rebueno.e3.pe/ganadores_tds_2014.html?uniqueid=201406020346"><u>aquí</u></a>
                    </p>
                    <p align="CENTER">
                        <strong>BASES DE LA PROMOCIÓN COMERCIAL "ME LA JUEGO"</strong>
                    </p>
                    <p>
                        <strong>1. OBJETO</strong>
                    </p>
                    <p>
                        La presente promoción denominada ME LA JUEGO, organizada por ECUADOR.COM (ECUADOR.COM) tiene por objeto premiar a los participantes que realicen compras en la
                        página web de ECUADOR.COM (<a href="http://www.rebueno.ec">www.rebueno.ec</a>) de acuerdo a lo señalado en las presentes bases.
                    </p>
                    <p>
                        La presente promoción se rige por lo establecido en las presentes bases por lo que los participantes se someten y aceptan íntegramente las mismas para su
                        participación.
                    </p>
                    <p>
                        <strong>2. ÁMBITO TERRITORIAL</strong>
                    </p>
                    <p>
                        El ámbito territorial de la presente promoción es nacional.
                    </p>
                    <p>
                        <strong>3. DURACIÓN</strong>
                    </p>
                    <p>
                        La presente promoción tiene una duración hasta diciembre de 2014.
                    </p>
                    <p>
                        <strong>4. MECÁNICA y CONDICIONES DE PARTICIPACIÓN</strong>
                    </p>
                    <p>
                        • Para participar en la presente promoción los participantes deben ingresar a <a href="http://www.rebueno.ec">www.rebueno.ec</a>, registrarse con su correo electrónico y efectuar como mínimo
                        una
                    </p>
                    <p>
                        (1) compra de la promoción con el logo de ME LA JUEGO.
                    </p>
                    <p>
                        • Pagando S/. 4.90 reciben una (1) opción de ganar, pagando S/. 9.90 reciben diez (10) opciones de ganar y pagando S/. 19.90 reciben treinta (30) opciones
                        de ganar. Pueden comprar cuantas opciones deseen, no hay límite máximo de compra por persona.
                    </p>
                    <p>
                        • Inmediatamente después de realizada la compra ya estarán participando.
                    </p>
                    <p>
                        • Las compras de las opciones de ME LA JUEGO estarán disponibles para comprar solo por 72 horas.
                    </p>
                    <p>
                        • Finalizada la campaña, ECUADOR.COM le devolverá a todos los participantes el monto de su compra (S/. 4.90, S/. 9.90 o S/. 19.90) en crédito ECUADOR.COM, según
                        corresponda. Este crédito se depositará en la cuenta registrada por el participante en Rebueno dentro de los 10 días útiles luego de la participación.
                        Dicho crédito tendrá vigencia de 90 días a partir del día del depósito en la cuenta del cliente.
                    </p>
                    <p>
                        • No son válidas las acumulaciones de compras para varios sorteos en caso de no resultar favorecidos.
                    </p>
                    <p>
                        • Los participantes podrán comprar las opciones por los montos señalados (S/. 4.90; S/. 9.90 y S/. 19.90) con sus tarjetas de crédito, tarjetas de débito o
                        en efectivo.
                    </p>
                    <p>
                        • Los datos de todos los compradores que hayan participado en el periodo de tiempo comprendido entre las fechas señaladas antes de los sorteos serán
                        incorporados automáticamente a una base de datos administrada por ECUADOR.COM.
                    </p>
                    <p>
                        • Los usuarios ya registrados en ECUADOR.COM previo al inicio de cada sorteo, también podrán participar, con solo realizar una compra de la promoción con el
                        logo de ME LA JUEGO.
                    </p>
                    <p>
                        • Se elegirá un (1) ganador en cada sorteo.
                    </p>
                    <p>
                        • Procedimiento para obtener al ganador:
                    </p>
                    <p>
                        Todos los participantes que se hayan registrado con sus datos personales (nombres y apellidos, DNI, dirección, distrito, correo electrónico y teléfono) en
                        la página web de ECUADOR.COM, <a href="http://www.rebueno.ec">www.rebueno.ec</a>, y hayan realizado una compra de las diferentes opciones de la promoción con el logo de ME LA JUEGO durante los
                        períodos de compra señalados, entran a los sorteos.
                    </p>
                    <p>
                        No se aceptarán nuevos participantes una vez finalizados los períodos de compra. Los clientes ya registrados en ECUADOR.COM, previo al inicio de cada sorteo,
                        también podrán participar, con efectuar la compra de opciones de la promoción con el logo de ME LA JUEGO.
                    </p>
                    <p>
                        Los ganadores de los sorteos serán elegidos entre todos los compradores vía un proceso aleatorio informático (software) de ECUADOR.COM en presencia del Notario
                        Público y representante de ECUADOR.COM.
                    </p>
                    <p>
                        ECUADOR.COM publicará el nombre de los ganadores en las cuentas de: Facebook (<a href="https://www.facebook.com/RebuenoLima?fref=ts">http://www.facebook.com/RebuenoLima?fref=ts</a>) y Twitter
                        (<a href="http://twitter.com/rebuenolima">http://twitter.com/rebuenolima</a>) de ECUADOR.COM y enviará un correo electrónico a base de datos de ECUADOR.COM. Asimismo, los ganadores serán notificados mediante
                        correo electrónico y/o llamada telefónica de ECUADOR.COM.
                    </p>
                    <p>
                        Todas las dudas o inconvenientes no contempladas en las presentes bases, que se generen en el momento del evento serán resueltas por el Notario Público y
                        representante de ECUADOR.COM y su fallo será inapelable.
                    </p>
                    <p>
                        <strong>5. PREMIOS</strong>
                    </p>
                    <p>
                        Cada ganador tendrá un plazo máximo de noventa (90) días calendario siguientes a la fecha del sorteo para reclamar el premio, previa coordinación en las
                        oficinas de ECUADOR.COM, ubicadas en Calle Gonzáles Olaechea N° 446-448, San Isidro, Lima; portando su DNI (original), pasaporte u otro documento que lo
                        acredite.
                    </p>
                    <p>
                        <strong>6. PARTICIPACIÓN</strong>
                    </p>
                    <p>
                        Pueden participar en la presente promoción, todos los peruanos y residentes en el Perú con excepción de:
                    </p>
                    <p>
                        • Personas Jurídicas en general.
                    </p>
                    <p>
                        • Menores de edad.
                    </p>
                    <p>
                        • Trabajadores y sus familiares de línea directa (padres, cónyuge e hijos) de ECUADOR.COM.
                    </p>
                    <p>
                        <strong>7. CONSIDERACIONES IMPORTANTES</strong>
                    </p>
                    <p>
                        • El premio no es acumulable, ni transferible, ni endosable. No está sujeto a devolución en efectivo.
                    </p>
                    <p>
                        <strong>8. IMPUESTOS</strong>
                    </p>
                    <p>
                        ECUADOR.COM se compromete a asumir el pago de los impuestos de ley que le pudiera corresponder respecto a los premios ofrecidos, con excepción de los impuestos
                        del Sistema Financiero que son de cargo de cada ganador.
                    </p>
                    <p>
                        <strong>9. LEYES APLICABLES</strong>
                    </p>
                    <p>
                        Las presentes bases están sujetas a las leyes de la República del Perú.
                    </p>
                    <p align="CENTER">
                        <strong>BASES DE LA PROMOCIÓN HAPPY HOURS</strong>
                    </p>
                    <p>
                        <strong>MECÁNICA y CONDICIONES DE PARTICIPACIÓN</strong>
                    </p>
                    <ul>
                        <li>
                            <p>
                                Promoción válida para pagos realizados 100% con PagoEfectivo.
                            </p>
                        </li>
                        <li>
                            <p>
                                Los participantes deben ingresar a <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>, registrarse con su correo electrónico y participar
                                en la presente promoción dando click al botón COMPRAR de las ofertas con el logo de HAPPY HOURS que aparecerán los días comunicados de forma masiva
                                a través de nuestro newsletter.
                            </p>
                        </li>
                        <li>
                            <p>
                                Comprando un cupón de la oferta con el logo de Happy Hours y pagando con la opción PagoEfectivo recibirán un cupón exactamente igual completamente
                                gratis.
                            </p>
                        </li>
                        <li>
                            <p>
                                Esta promoción estará disponible para comprar solo por la cantidad de horas indicada en la misma oferta, o hasta agotar stock.
                            </p>
                        </li>
                        <li>
                            <p>
                                Dentro de los 5 días hábiles desde la fecha en que se realiza cada compra, ECUADOR.COM le enviará un aviso a los compradores que adquirieron el cupón
                                de la oferta marcada con el logo Happy Hours, comunicándoles que recibirán un premio de exactamente igual valor al cupón del producto adquirido.
                            </p>
                        </li>
                        <li>
                            <p>
                                No hay sorteos, ni concursos. El único requisito para obtener el segundo cupón gratis es pagar la oferta con PagoEfectivo.
                            </p>
                        </li>
                        <li>
                            <p>
                                ECUADOR.COM solo otorgará 1 crédito (premio) por cada compra. Si el cliente compra más de un cupón cumpliendo con el requisito antes mencionado
                                solamente recibirá 1 segundo cupón gratis.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>CONSIDERACIONES IMPORTANTES</strong>
                    </p>
                    <ul>
                        <li>
                            <p>
                                La promoción no aplica para pagos realizados directamente en nuestra plataforma seleccionando la opción de pago VISA o MASTERCARD.
                            </p>
                        </li>
                        <li>
                            <p>
                                El cupón no podrá ser cambiado por dinero en efectivo. No está sujeto a devolución ni reembolso.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>RESPONSABILIDAD</strong>
                        <br/>
                        <br/>
                        ECUADOR.COM declara expresamente que actúa como intermediario por lo que no tendrá responsabilidad legal por cualquier daño o perjuicio que pudiera derivarse
                        de la idoneidad de los servicios que ofrece el establecimiento proveedor (restaurantes, bares y/o discotecas) que participan de la presente promoción.
                    </p>
                    <p align="CENTER">
                        <strong>BASES DE LA PROMOCIÓN 35% de devolución pagando a través de PAGO EFECTIVO - CYBER PERÚ DAY 2014</strong>
                    </p>
                    <p>
                        La devolución aplica exclusivamente en las ofertas seleccionadas con el logo de la promoción, pagadas a través de Pago Efectivo durante el Cyber Perú Day
                        2014 en Rebueno, desde el 15 de julio de 2014 a las 0:00 horas, hasta el 16 de julio de 2014 a las 23:59 horas.
                    </p>
                    <p>
                        Promoción válida solo hasta agotar el fondo de la promoción de S/. 15,000.
                    </p>
                    <p>
                        i la compra se realizó cuando la oferta se hubiese terminado, no procederá la devolución.
                    </p>
                    <p>
                        La devolución del 35% en crédito Rebueno se efectuará sobre el importe pagado a través de Pago Efectivo.
                    </p>
                    <p>
                        Participan solo compras pagadas al 100% a través de Pago Efectivo.
                    </p>
                    <p>
                        No participan compras pagadas de forma mixta, ya sea con créditos Rebueno + Pago Efectivo, o con tarjetas de crédito o débito + Pago Efectivo.
                    </p>
                    <p>
                        Monto máximo de devolución: S/. 50.00
                    </p>
                    <p>
                        El crédito Rebueno solo podrá ser usado para compras en la página <a href="http://www.rebueno.ec">www.rebueno.ec</a> dentro de los 30 días posteriores luego de realizado el abono de los
                        mismos en la cuenta del cliente registrada en Rebueno.
                    </p>
                    <p>
                        Luego de pasados los 30 días, el crédito no consumido se eliminará automáticamente y no será sujeto a reposición ni devolución.
                    </p>
                    <p>
                        El crédito Rebueno no podrá ser cambiado por dinero en efectivo.
                    </p>
                    <p>
                        La devolución en crédito se depositará en la cuenta Rebueno del cliente dentro de los 10 días útiles después de realizada la compra.
                    </p>
                    <p>
                        La devolución del 35% en crédito Rebueno para pagos con Pago Efectivo no es acumulable con otras promociones.
                    </p>
                    <p>
                        Rebueno y Pago Efectivo se reservan el derecho de darle de baja a la promoción en cualquier momento de la campaña.
                    </p>
                    <p>
                        Para verificar la validación del crédito ingresa a tu cuenta en <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>
                    </p>
                    <p>
                        <strong>CAMPAÑA: ME LA JUEGO - OCTUBRE 2013</strong>
                    </p>
                    <p>
                        Para revisar las condiciones de esta promoción ingresa a este link:    <a href="http://rebueno.e3.pe/legal/201309_melajuego.html"><u>http://rebueno.e3.pe/legal/201309_melajuego.html</u></a>
                    </p>
                    <p>
                        <strong>BASES DE LA PROMOCIÓN</strong>
                        <br/>
                        <strong>35% de devolución pagando a través de PAGO EFECTIVO VENTA NOCTURNA</strong>
                    </p>
                    <p>
                        La devolución aplica exclusivamente en las ofertas seleccionadas con el logo de la promoción, pagadas a través de Pago Efectivo durante la Venta Nocturna
                        Rebueno, desde el 15 de mayo de 2014 a las 18 horas, hasta el 16 de mayo de 2014 a las 12 horas.
                    </p>
                    <p>
                        Promoción válida solo hasta agotar el fondo de la promoción de S/. 5,000
                    </p>
                    <p>
                        Si la compra se realizó cuando la oferta se hubiese terminado, no procederá la devolución.
                    </p>
                    <p>
                        La devolución del 35% en crédito Rebueno se efectuará sobre el importe pagado a través de Pago Efectivo.
                    </p>
                    <p>
                        Participan solo compras pagadas al 100% a través de Pago Efectivo.
                    </p>
                    <p>
                        No participan compras pagadas de forma mixta, ya sea con créditos Rebueno + Pago Efectivo, o con tarjetas de crédito o débito + Pago Efectivo.
                    </p>
                    <p>
                        Monto máximo de devolución: S/. 100.00
                    </p>
                    <p>
                        El crédito Rebueno solo podrá ser usado para compras en la página <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a> dentro de los 30 días
                        posteriores luego de realizado el abono de los mismos en la cuenta del cliente registrada en Rebueno.
                    </p>
                    <p>
                        Luego de pasados los 30 días, el crédito no consumido se eliminará automáticamente y no será sujeto a reposición ni devolución.
                    </p>
                    <p>
                        El crédito Rebueno no podrá ser cambiado por dinero en efectivo.
                    </p>
                    <p>
                        La devolución en crédito se depositará en la cuenta Rebueno del cliente dentro de los 10 días útiles después de realizada la compra.
                    </p>
                    <p>
                        La devolución del 35% en crédito Rebueno para pagos con Pago Efectivo no es acumulable con otras promociones.
                    </p>
                    <p>
                        Rebueno y Pago Efectivo se reservan el derecho de darle de baja a la promoción en cualquier momento de la campaña.
                    </p>
                    <p>
                        Para verificar la validación del crédito ingresa a tu cuenta en <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>
                    </p>
                    <p>
                        <strong>CAMPAÑA: 35% de devolución PAGO EFECTIVO - VENTA NOCTURNA MARZO 2014</strong>
                    </p>
                    <p>
                        Para revisar las condiciones de esta promoción ingresa a este link:    <a href="http://rebueno.e3.pe/legal/20140331_pe_ventanocturna.html"><u>http://rebueno.e3.pe/legal/20140331_pe_ventanocturna.html</u></a>
                    </p>
                    <p>
                        <strong>CAMPAÑA: DEVOLUCIÓN BBVA - CYBERMAMI 2014</strong>
                    </p>
                    <p>
                        <strong>Tarjeta de Crédito: 30 % de devolución con un monto máximo de S/. 100</strong>
                    </p>
                    <p>
                        Términos y condiciones:
                    </p>
                    <p>
                        Promoción del 30% de devolución, válida sólo para compras por Internet del 29/04/14 hasta el 30/04/14, siempre que se realice el pago total con Tarjetas de
                        Crédito del BBVA Continental y que la compra se haya hecho efectiva (no válida para compras rechazadas por el establecimiento) y que la transacción se haya
                        realizado en su totalidad por internet en la misma página de los comercios señalados en el presente anuncio (no válida para reservas por internet, pagos en
                        la banca por internet ni compras por teléfono).
                    </p>
                    <p>
                        Promoción exclusiva para las Tarjetas de Crédito del BBVA Continental Visa: Nacional, Zero, Repsol, Clásica, Oro, Platinum, Signature; y, MasterCard:
                        Clásica, Oro, Platinum y Black. No participan Tarjetas de Crédito Capital de Trabajo, Empresariales.
                    </p>
                    <p>
                        El monto máximo de devolución es de S/. 100 por cliente durante toda la promoción, así haya realizado sus compras con más de una tarjeta de crédito.
                    </p>
                    <p>
                        Para participar de la campaña debes inscribirte en <a href="https://www.bbvacontinental.pe" target="_blank">www.bbvacontinental.pe</a>. La inscripción puede ser realizada como máximo hasta el 30/04/2014, aún después
                        de haber realizado los consumos. Se habilitará una opción en banca por teléfono para cualquier consulta acerca de las campañas o afiliación a Verified by
                        Visa, llamar al (01) 595-0000 opción 2,7.
                    </p>
                    <p>
                        No participan Tarjetas que se encuentren bloqueadas por mora o sobregiro, al momento de realizar la devolución. No válido para disposición de efectivo,
                        subrogación de deuda, consumos en casinos, compras en páginas web de juegos de azar, ni pagos SUNAT, SAT o universidades.
                    </p>
                    <p>
                        Sólo se realizará la devolución a una Tarjeta de Crédito por cliente titular. El porcentaje de devolución no es aplicado en el comercio al momento de
                        realizar la compra. La devolución la realizará el banco y se verá reflejada en el Estado de Cuenta del 10 de Junio para Tarjetas Visa y 20 de Junio para
                        Tarjetas MasterCard.
                    </p>
                    <p>
                        El banco declara expresamente que actúa como intermediario, por lo que no tendrá responsabilidad legal por daños o perjuicios derivados de la idoneidad
                        legal de los productos o servicios ofrecidos por las empresas proveedoras que participan en la presente campaña.
                    </p>
                    <p>
                        Información brindada según Ley N° 28587 y su Reglamento. Tasas de interés, comisiones, gastos y penalidades publicados en el Tarifario de Oficinas de
                        Atención al Público y en <a href="https://www.bbvacontinental.pe" target="_blank">www.bbvacontinental.pe</a>. Para mayor información, comunícate al (01) 595-0000. ITF (0.005%) sujeto a variación.
                    </p>
                    <p>
                        <strong>Tarjeta de Débito: se le dará un bono de S/.20 por compras mayores a S/. 100</strong>
                    </p>
                    <p>
                        Términos y condiciones:
                    </p>
                    <p>
                        Promoción válida sólo para compras por Internet del 29/04/2014 hasta el 30/04/2014, siempre que se realice el pago total con Tarjetas de Débito del BBVA
                        Continental, que la compra se haya hecho efectiva (no válida para compras rechazadas por el establecimiento) y que la transacción se haya realizado en su
                        totalidad por internet en la misma página de los comercios señalados en el presente anuncio (no válida para reservas por internet, pagos en la banca por
                        internet ni compras por teléfono).
                    </p>
                    <p>
                        Promoción exclusiva para las Tarjetas de Débito Mundo Sueldo, VIP, Débito Compras del BBVA Continental. No participan las Tarjetas de Crédito, Capital de
                        Trabajo, ni Empresariales, ni Débito Empresarial.
                    </p>
                    <p>
                        El monto mínimo de compras acumuladas para acceder a la promoción es de S/. 100. El bono máximo por cliente es de S/. 20 durante toda la promoción, así
                        haya realizado sus compras con más de una tarjeta de débito. El monto del bono no es aplicado en el comercio al momento de realizar la compra. El banco es
                        responsable de realizar el depósito del bono, el cual se verá reflejado en la cuenta asociada a la Tarjeta de Débito el 10/06/2014. Se habilitará una
                        opción en banca por teléfono para cualquier consulta acerca de las campañas o afiliación a Verified by Visa, llamar al (01) 595-0000 opción 2,7.
                    </p>
                    <p>
                        Para participar de la campaña debes inscribirte en <a href="https://www.bbvacontinental.pe" target="_blank">www.bbvacontinental.pe</a>. La inscripción puede ser realizada como máximo hasta el 30/04/2014, aún después
                        de haber realizado los consumos.
                    </p>
                    <p>
                        No participan Tarjetas que se encuentren con bloqueo al momento de realizar la devolución. No válido para disposición de efectivo, subrogación de deuda,
                        consumos en casinos, ni pagos SUNAT, SAT y Universidades.
                    </p>
                    <p>
                        El banco declara expresamente que actúa como intermediario, por lo que no tendrá responsabilidad legal por daños o perjuicios derivados de la idoneidad
                        legal de los productos o servicios ofrecidos por las empresas proveedoras que participan en la presente campaña.
                    </p>
                    <p>
                        Información brindada según Ley N° 28587 y su Reglamento. Tasas de interés, comisiones, gastos y penalidades publicados en el Tarifario de Oficinas de
                        Atención al Público y en <a href="https://www.bbvacontinental.pe" target="_blank">www.bbvacontinental.pe</a>. Para mayor información, comunícate al (01) 595-0000. ITF (0.005%) sujeto a variación.
                    </p>
                    <p>
                        <strong>Tarjeta Prepago: se le dará un bono de S/.20 por compras mayores a S/. 100</strong>
                    </p>
                    <p>
                        Términos y condiciones:
                    </p>
                    <p>
                        Promoción válida sólo para compras por Internet del 29/04/2014 hasta el 30/04/2014, siempre que se realice el pago total con Tarjetas Prepago del BBVA
                        Continental, que la compra se haya hecho efectiva (no válida para compras rechazadas por el establecimiento) y que la transacción se haya realizado en su
                        totalidad por internet en la misma página de los comercios señalados en el presente anuncio (no válida para reservas por internet, pagos en la banca por
                        internet ni compras por teléfono).
                    </p>
                    <p>
                        Promoción exclusiva para las Tarjetas Prepago del BBVA Continental. No participan las Tarjetas Mistura.
                    </p>
                    <p>
                        El monto mínimo de compras acumuladas para acceder a la promoción es de S/. 100. El monto máximo de devolución es de S/. 20 por Tarjeta Prepago durante
                        toda la promoción. El monto del bono no es aplicado en el comercio al momento de realizar la compra. El banco es responsable de realizar el depósito del
                        bono, el cual se verá reflejado el 10/06/2014.
                    </p>
                    <p>
                        Para participar de la campaña debes inscribirte en <a href="https://www.bbvacontinental.pe" target="_blank">www.bbvacontinental.pe</a>. La inscripción puede ser realizada como máximo hasta el 30/04/14, aún después de
                        haber realizado los consumos. Se habilitará una opción en banca por teléfono para cualquier consulta acerca de las campañas o afiliación a Verified by
                        Visa, llamar al (01) 595-0000 opción 2,7.
                    </p>
                    <p>
                        No participan Tarjetas que se encuentren con bloqueo al momento de realizar la devolución. No válido para disposición de efectivo, subrogación de deuda,
                        consumos en casinos, ni pagos SUNAT, SAT y Universidades.
                    </p>
                    <p>
                        El banco declara expresamente que actúa como intermediario, por lo que no tendrá responsabilidad legal por daños o perjuicios derivados de la idoneidad
                        legal de los productos o servicios ofrecidos por las empresas proveedoras que participan en la presente campaña.
                    </p>
                    <p>
                        Información brindada según Ley N° 28587 y su Reglamento. Tasas de interés, comisiones, gastos y penalidades publicados en el Tarifario de Oficinas de
                        Atención al Público y en <a href="https://www.bbvacontinental.pe" target="_blank">www.bbvacontinental.pe</a>. Para mayor información, comunícate al (01) 595-0000. ITF (0.005%) sujeto a variación.
                    </p>
                    <p>
                        <strong>BASES DE LA PROMOCIÓN DEVOLUCIÓN SHOPIN-PAGOEFECTIVO</strong>
                    </p>
                    <p>
                        Para revisar las condiciones de esta promoción ingresa a este    <a href="http://rebueno.e3.pe/legal/201405-shopin-pagoefectivo.html?v=201405283213133"><u> link</u></a>
                    </p>
                    <p>
                        <strong>BASES DE LA PROMOCIÓN: 35% DE DEVOLUCIÓN PAGANDO A TRAVÉS DE PAGO EFECTIVO EN LOS DÍAS TOP</strong>
                    </p>
                    <p>
                        Para revisar las condiciones de esta promoción ingresa a este link:    <a href="http://rebueno.e3.pe/legal/20140515_legal_devolucion_diastop.html"><u>http://rebueno.e3.pe/legal/20140515_legal_devolucion_diastop.html</u></a>
                    </p>
                    <p>
                        <strong>BASES DE LA PROMOCIÓN: "PORQUE TU ERES EL PAPÁ QUE YO QUIERO SER"</strong>
                    </p>
                    <p>
                        Para revisar las condiciones de esta promoción ingresa a este    <a href="http://rebueno.e3.pe/legal/2014_legal_porquetuereselpapaqueyoquieroser.html?uniq=201406031258"><u>link</u></a>
                    </p>
                    <p>
                        <strong>BASES DE LA PROMOCIÓN: "35% DE DEVOLUCIÓN PAGANDO CON PAGO EFECTIVO - VENTA NOCTURNA (16 Y 17 DE JUNIO)"</strong>
                    </p>
                    <p>
                        Para revisar las condiciones de esta promoción ingresa a este    <a href="http://rebueno.e3.pe/legal/201406_devolucion_pe_ventanocturna.html?uniq=201406161753"><u>link</u></a>
                    </p>
                    <p>
                        <a name="_GoBack"></a>
                        <br/>
                        <br/>
                    </p>
                    <p>
                        .<strong>BASES DE LA PROMOCIÓN BBVA CYBERPERUDAY 2014</strong>
                    </p>
                    <p>
                        Promoción del 20% de devolución por compras acumuladas mayores a S/.150, válida sólo para compras por Internet en cualquier comercio online
                        del 15/07/2014 hasta el 16/07/2014, siempre que se realice el pago total con Tarjetas de Crédito del BBVA Continental (ver tarjetas participantes), que la
                        compra se haya hecho efectiva dentro del plazo de vigencia de la presente campaña (no válida para compras rechazadas por el establecimiento) y
                        que la transacción se haya realizado en su totalidad en la misma página del comercio por internet (no válida para reservas por internet, pagos en la banca
                        por internet, compras por teléfono ni compras contra entrega).
                    </p>
                    <p>
                        El monto máximo de devolución por las compras acumuladas es de S/. 100 por cliente durante toda la promoción, así haya realizado compras con más de
                        una tarjeta de crédito. Sólo se realizará la devolución a una Tarjeta de Crédito
                    </p>
                    <p>
                        Para participar de la campaña debes inscribirte en bbvacontinental.pe. La inscripción puede ser realizada como máximo hasta el 16/07/201, incluso
                        después de haber realizado los consumos.
                    </p>
                    <p>
                        Promoción exclusiva para las Tarjetas de Crédito del BBVA Continental Visa: Repsol, Clásica, Oro, Platinum, Signature; y, MasterCard: Clásica, Oro,
                        Platinum y Black. No participan Tarjetas de Crédito Nacional, Zero, Capital de Trabajo, Empresariales.
                    </p>
                    <p>
                        No participan Tarjetas que se encuentren bloqueadas por mora o sobregiro, al momento de realizar la devolución. No válido para disposición de efectivo,
                        subrogación de deuda, consumos en casinos, ni pagos SUNAT, SAT o
                    </p>
                    <p>
                        El porcentaje de devolución no es aplicado en el comercio al momento de realizar la compra. La devolución se verá reflejada en el Estado de Cuenta
                        del 10 de Setiembre para Tarjetas Visa y 20 de Setiembre para Tarjetas
                    </p>
                    <p>
                        Información brindada según Ley N° 28587 y su Reglamento. Tasas de interés, comisiones, gastos y penalidades publicados en el Tarifario de Oficinas de
                        Atención al Público y en <a href="https://www.bbvacontinental.pe" target="_blank">www.bbvacontinental.pe</a>. Para mayor información, comunícate al (01) 595-0000. ITF (0.005%) sujeto a variación.
                    </p>


                    <p><strong>BASES DE LA PROMOCIÓN 35% DE DEVOLUCIÓN PAGANDO CON  PAGO EFECTIVO – REDISEÑO ECUADOR.COM (18 Y 19 DE AGOSTO DE 2014)</strong></p>
                    <p>La devolución aplica a todas las compras realizadas a través de Pago Efectivo desde el 18 de agosto de 2014 a las 00 horas, hasta el 19 de agosto de 2014 a las 23:59 horas.</p>
                    <p>Monto máximo de devolución por cada compra: S/. 50.00
                        Promoción válida solo hasta agotar el fondo de la promoción de S/. 10,000
                        Si la compra se realizó cuando la oferta se hubiese terminado, no procederá la devolución.</p>
                    <p>Solo se devolverá los pedidos generados y pagados durante los dos días. Los pedidos cancelados (pagados) luego del 19 de agosto de 2014 no serán considerados.
                        Participan solo compras pagadas al 100% a través de Pago Efectivo.
                        La devolución del 35% en crédito Rebueno se efectuará sobre el importe pagado a través de Pago Efectivo.
                        No participan compras pagadas de forma mixta, ya sea con créditos Rebueno + Pago Efectivo, o con tarjetas de crédito o débito + Pago Efectivo.
                        El crédito Rebueno solo podrá ser usado para compras en la página <a href="http://www.rebueno.ec">www.rebueno.ec</a> dentro de los 30 días posteriores luego de realizado el abono de los mismos en la cuenta del cliente registrada en Rebueno.
                        Luego de pasados los 30 días, el crédito no consumido se eliminará automáticamente y no será sujeto a reposición ni devolución.
                        El crédito Rebueno no podrá ser cambiado por dinero en efectivo.</p>
                    <p>La devolución en crédito se depositará en la cuenta Rebueno del cliente dentro de los 10 días útiles después de realizada la compra.
                        La devolución del 35% en crédito Rebueno para pagos con Pago Efectivo no es acumulable con otras promociones.
                        Rebueno y Pago Efectivo se reservan el derecho de darle de baja a la promoción en cualquier momento de la campaña.
                        Para verificar la validación del crédito ingresa a tu cuenta en <a href="http://www.rebueno.ec">www.rebueno.ec</a></p>

                    <!-- TERMINA REEMPLAZO -->
                </div>
            </div>
        </section>
    </div>
</div>