<div class="container">
    <div class="box_center box_rebueno_information">
        <section>
            <div class="accordion">
                <div class="header">
                    <h2>Términos y condiciones generales</h2><span></span>
                </div>
                <hr class="medium">
            </div>
            <div class="container">
                <div class="content">
                    <p align="CENTER">
                        <strong>Términos y Condiciones de Uso</strong>
                    </p>
                    <p class="justificado">
                        Este es el Portal <a href="http://www.rebueno.ec/">www.rebueno.ec</a> de propiedad de ECUADOR.COM, con domicilio en Sauces II Mz. F111 Solar 108, Guayaquil, (en adelante ECUADOR.COM), y los
                        siguientes son los Términos y Condiciones de Uso que regulan el acceso y uso de este Portal (en adelante “el sitio”) y, en general, la relación entre
                        ECUADOR.COM y los USUARIOS del sitio, sin perjuicio de otras condiciones e instrucciones particulares o específicas que ECUADOR.COM comunique adecuadamente a los
                        usuarios.
                    </p>
                    <p class="justificado">
                        La utilización del sitio atribuye la condición de USUARIO del mismo, e implica la aceptación plena y sin reservas de todas y cada una de las disposiciones
                        incluidas en estos Términos y Condiciones, siendo obligación del USUARIO leer atentamente los Términos y Condiciones antes de hacer uso del sitio y de su
                        contenido.
                    </p>
                    <p class="justificado">
                        Al comunicarte con este sitio Web, las políticas y normas detalladas a continuación, se consideran aceptadas.
                    </p>
                    <p class="justificado">
                        <strong>1.</strong>
                        En la página web <a href="http://www.rebueno.ec/">www.rebueno.ec</a> se ofrecen cupones sobre prestaciones o sobre mercancías de otras empresas (“Los socios”). Emitentes de los cupones y
                        deudores de las prestaciones o mercancías indicadas en los cupones son exclusivamente los respectivos socios, los cuales realizan esas prestaciones con
                        arreglo a sus respectivas Condiciones Generales de Contratación. ECUADOR.COM misma no adeuda la realización de las prestaciones indicadas en los cupones ni la
                        entrega de las mercancías indicadas en los mismos, sino que el cupón le concede al usuario únicamente un derecho a que el socio o los socios realicen la
                        prestación. Para la utilización del servicio de ECUADOR.COM rigen única y exclusivamente los siguientes términos y condiciones de uso. Los cupones vendidos por
                        ECUADOR.COM no están dirigidos a una prestación concreta (cupón de acontecimiento) ni a una mercancía concreta (cupón de mercancía) ni a un valor de prestación
                        o mercancía concretos (cupón de valor). En caso que el socio o los socios hubieran fijado sus propios términos y condiciones para los actos y contratos que
                        realice en este sitio, ellas aparecerán en esta página señalada con un link o indicada como parte de la promoción de sus ofertas y promociones y se
                        entenderán como complementarias a estas.
                        <br/>
                        <br/>
                        <strong>2.</strong>
                        La página web <a href="http://www.rebueno.ec/">www.rebueno.ec</a> así como el sistema de venta de cupones en dicha página son gestionados por:
                    </p>
                    <p  class="justificado">
                        ECUADOR.COM
                        <br/>
                        Sauces II Mz. F111 Solar 108
                        <br/>
                        Guayaquil – Ecuador
                        <br/>
                        Teléfono: (04) 5049416
                        <br/>
                        E-mail: <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a>
                        <br/>
                        <br/>
                        <strong>3.</strong>
                        Ya sea mediante confirmación del correspondiente campo en el proceso de pedido, o bien si el usuario hace uso efectivo del servicio, quedarán aceptadas las
                        condiciones de uso de ECUADOR.COM. En tal caso, Usted reconoce que nosotros - ECUADOR.COM - consideremos el uso de nuestro servicio como reconocimiento de las
                        condiciones de uso. Estas condiciones de uso podrán ser consultadas, impresas o grabadas localmente en cualquier momento bajo
                        <a href="http://www.rebueno.ec/interes/terminos-y-condiciones">www.rebueno.ec/interes/terminos-y-condiciones</a>.
                    </p>
                    <p  class="justificado">
                        4. Los cupones sólo están disponibles para personas que tengan capacidad legal para contratar (mayores de 18 años de edad según la ley ecuatoriana). No podrán
                        adquirir los cupones las personas que no tengan esa capacidad y los menores de edad. Los actos que éstos realicen en el sitio serán responsabilidad de sus
                        padres, tutores, encargados o apoderados, y por tanto se considerarán realizados por éstos en ejercicio de la representación legal con la que cuentan.
                        <br/>
                        <br/>
                        <strong>5. </strong>
                        Para adquirir los cupones ofrecidos en el sitio, los usuarios registrados deberán facilitar determinados datos de carácter personal. Su información
                        personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica.
                    </p>
                    <p class="justificado">
                        ECUADOR.COM garantiza la confidencialidad de los datos suministrados por los usuarios de acuerdo con las normas legales aplicables e informa acerca del uso que
                        ECUADOR.COM hará de los datos de carácter personal que proporcionen los usuarios, para que los mismos determinen libre y voluntariamente si desean suministrar
                        a la ECUADOR.COM sus datos personales, en cualquier forma y a través de cualquier medio.
                    </p>
                    <p class="justificado">
                        De conformidad con la Ley de Comercio Electrónico del Ecuador, desde el momento de su ingreso y/o utilización al sitio el usuario da expresamente su consentimiento para el tratamiento 
                        de los datos personales que por el sean facilitados o que se faciliten a través de su ingreso al portal o por cualquier medio. Asimismo, el usuario consiente expresamente que ECUADOR.COM pueda ceder los datos personales, a terceros en los términos y 
                        condiciones señalados en esta página.
                    </p>
                    <p class="justificado">
                        Los datos personales serán incorporados a la base de datos de titularidad de ECUADOR.COM. Estos datos serán utilizados en la gestión administrativa y comercial
                        de la petición de los usuarios.
                    </p>
                    <p class="justificado">
                        Los datos se mantendrán en la base de datos mientras se consideren útiles con el fin que ECUADOR.COM pueda prestar y ofrecer sus servicios y darles trámite,
                        enviarle información y publicidad sobre las ofertas, promociones y recomendaciones de ECUADOR.COM.
                    </p>
                    <p class="justificado">
                        En cuanto entre en vigencia las disposiciones pertinentes de la Ley de Comercio Electrónico del Ecuador, al usuario le asiste de 
                        ejercer los derechos de acceso, rectificación, oposición y cancelación de los datos personales, los cuales podrá ejercer mediante la 
                        opción de contacto que ponemos a su disposición en esta página.
                    </p>
                    <p class="justificado">
                        El titular de la cuenta es responsable de no mantener su sesión activa en un dispositivo al cual otro usuario podría tener acceso.
                        <br/>
                        <strong>
                            <br/>
                            6.
                        </strong>
                        ECUADOR.COM podrá modificar estos términos y condiciones de uso, por ejemplo, para poner en práctica cambios en la legislación ecuatoriana o tener en cuenta
                        modificaciones sobre su funcionamiento o sobre políticas de atención. El usuario encontrará las condiciones de uso vigentes en cada momento bajo
                        <a href="http://www.rebueno.ec/interes/terminos-y-condiciones">http://www.rebueno.ec/interes/terminos-y-condiciones</a>. En caso de que no estuviera de acuerdo con las modificaciones de nuestras condiciones de uso, el usuario
                        podrá optar por no hacer uso de nuestro servicio.
                        <br/>
                        <br/>
                        <strong>7.</strong>
                        Para la compra de un cupón en <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>, el usuario deberá:
                        <br/>
                        <br/>
                        <strong>7.1.</strong>
                        Confirmar el botón "comprar" en la página inicial.
                        <br/>
                        <strong>7.2.</strong>
                        Elija el número deseado de cupones.
                        <br/>
                        <strong>7.3.</strong>
                        Introduzca su nombre y su email, así como los datos de su tarjeta de crédito.
                        <br/>
                        <strong>7.4.</strong>
                        Su declaración de voluntad de compra queda emitida mediante la confirmación de las condiciones de uso y presión del botón "comprar". La aceptación del
                        contrato de compraventa por parte de ECUADOR.COM tiene lugar con la confirmación en forma de envío de un código del cupón.
                        <br/>
                        <strong>7.5. </strong>
                        Imprima el cupón y hágalo efectivo en el correspondiente establecimiento del socio o, en su caso, ante dicho socio.
                        <br/>
                        <strong>7.6.</strong>
                        El pago por parte del usuario será automático, así como la remisión del cupón adquirido, no siendo necesario que transcurra el período del descuento y/o se
                        alcance el número mínimo de participantes.
                        <br/>
                        <strong>7.7.</strong>
                        La venta del cupón no se produce hasta que ECUADOR.COM no haya registrado con éxito el cobro. En caso de no tener éxito con el primer intento de cobro (por ej.
                        porque no exista la cuenta indicada o no disponga de saldo suficiente, el número de la tarjeta de crédito sea erróneo o la misma esté al límite) tampoco se
                        producirá la venta del cupón.
                        <br/>
                        <strong>7.8.</strong>
                        Todos los cupones están dotados de un claro números de código, que deberá validarse en el sistema aprobado por ECUADOR.COM y del cual el socio dispone, cuando
                        se presentan los cupones para hacerlos efectivos. El cupón es transmisible. No se autoriza la reproducción, edición o manipulación de los cupones. En caso
                        de sospecha fundada de reproducción ilícita, ECUADOR.COM se reserva el derecho de transmitir los datos archivados al socio respectivo e iniciar las acciones
                        legales pertinentes.
                        <br/>
                        <strong>7.9.</strong>
                        En la medida en que no se indique lo contrario, el cupón no concede un derecho a hacer uso de prestaciones o a la adquisición de mercancías en un momento
                        concreto. Por ello, el usuario debe acordar individual y directamente con el socio el momento de realización de la prestación.
                        <br/>
                        <strong>7.10.</strong>
                        En caso de que en el cupón figure un período de vigencia, el cupón sólo podrá hacerse efectivo frente al socio dentro de ese período de vigencia. Una vez
                        transcurrido el período de vigencia, el cupón pierde su validez y no podrá hacerse efectivo bajo ninguna circunstancia.
                        <br/>
                        <strong>7.11.</strong>
                        El stock es limitado. Todo pago realizado luego de agotado el stock no se considerará válido y sera reembolsado al cliente en su totalidad. Ejemplo: Si
                        el stock es de 10 unidades y 20 personas han accedido a la promoción( hacen click en la opción de compra y son redirigidos a nuestras pasarelas de pago, 
                        solamente los 10 primeros cobros serán considerados como beneficiarios de la oferta. A los 10 restantes, por haberse agotado el
                        stock, se les reembolsara su dinero.
                        <br/>
                        <br/>
                        <strong>8. </strong>
                        Información sobre el derecho de revocación
                        <br/>
                        <strong>8.1.</strong>
                        Si el usuario es consumidor, podrá revocar la declaración contractual de compra del cupón en el plazo de dos (02) semanas sin necesidad de indicar las
                        causas, comunicándolo por escrito (correo electrónico) o mediante el reenvío del cupón. El plazo comienza tras la recepción de cupón por el
                        destinatario, nunca antes de la recepción del mismo. Para que se considere cumplido el plazo de revocación bastará que el envío de la revocación y/o del
                        cupón haya tenido su salida puntualmente dentro de dicho plazo.
                        <br/>
                        <strong>8.2. </strong>
                        Una vez hecho efectivo el cupón frente al SOCIO, ya no es posible la revocación.
                        <br/>
                        <strong>8.3.</strong>
                        La revocación debe dirigirse a la dirección electrónica: <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a>
                        <br/>
                        <strong>8.4.</strong>
                        Consecuencias de la revocación:
                        <br/>
                        En el caso de una revocación eficaz, se han de restituir las prestaciones recibidas por ambas partes y, en su caso, entregar los frutos o utilidades
                        percibidos (ej. ventajas de uso). Las obligaciones de devolución de pagos han de cumplirse en el plazo máximo de treinta (30) días. El plazo comienza para
                        el usuario con la salida del envío de su declaración de revocación o de su vale, y para ECUADOR.COM, con su recepción.
                    </p>
                    <p class="justificado">
                        Como una medida de protección a la seguridad de las transacciones, ECUADOR.COM se reserva el derecho de dejar sin efecto las compras que se realicen, en caso
                        los datos entregados por el cliente no coincidan con las bases de datos disponibles de ECUADOR.COM o aquellas en las que el Banco emisor registre como
                        transacción no reconocida por el dueño de la tarjeta de crédito. ECUADOR.COM podrá contactar al titular de la cuenta, y comunicar este hecho; en caso de no
                        obtener respuesta al respecto, se comunicará al Banco emisor sobre la tarjeta de crédito utilizada por el consumidor al momento de enviar su solicitud de
                        compra. El Banco emisor de la tarjeta de crédito que se utilizó para realizar la compra en el sitio, deberá proceder con la devolución del importe de
                        acuerdo con sus Políticas. ECUADOR.COM no se responsabiliza en ningún caso por la no devolución de dinero utilizado a través de tarjetas de crédito en las
                        situaciones antes mencionada.
                        <br/>
                        Adicionalmente, en cumplimiento a las normas de prevención del lavado de activos y cuando lo estime conveniente, ECUADOR.COM podrá solicitar al Usuario
                        diversos documentos e información adicional, respecto a su identificación y/o datos personales.
                    </p>
                    <p class="justificado">
                        <strong>9. </strong>
                        Atención de reclamos
                        <br/>
                        Todo <strong>reclamo</strong> será atendido dentro de los <strong>30 días calendario</strong> de presentado. Dicho plazo será extendido por otro
                        igual si el reclamo lo justifican, previa comunicación al cliente antes de la culminación del plazo inicial. El reclamo será atendido a
                        través del correo electrónico: <a href="mailito:solicitudes@rebueno.ec"><u>solicitudes@rebueno.ec</u></a>
                    </p>
                    <p class="justificado">
                        <strong>10. </strong>
                        Créditos
                        <br/>
                        El <strong>crédito a favor</strong> del cliente en Rebueno podrá utilizarse:
                    </p>
                    <ul>
                        <li>
                            <p>
                                Para compras de montos menores, quedando el saldo disponible para futuras compras.
                            </p>
                        </li>
                        <li>
                            <p>
                                Para compras de montos iguales.
                            </p>
                        </li>
                        <li>
                            <p class="justificado">
                                Para compras de montos mayores, pagando la diferencia a través de cualquier medio de pago, salvo que este se encuentre fijado a ciertas condiciones
                                y restricciones que serán previamente comunicadas al cliente.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>11.</strong>
                        Reservas en los establecimientos:
                    </p>
                    <ul>
                        <li>
                            <p class="justificado">
                                Los clientes deben sujetarse a las condiciones y restricciones de la promoción, sea de productos o servicios (paquetes turísticos, pasajes aéreos,
                                etc.) indicadas en el cupón.
                            </p>
                        </li>
                        <li>
                            <p class="justificado">
                        <u>
                            Todo cambio o reprogramación de fechas, horarios, destinos, etc. de las reservaciones de paquetes turísticos y/o pasajes aéreos deberán
                            realizarse con la debida anticipación y coordinarse directamente con el establecimiento o empresa señalada en el cupón. Estos cambios serán de
                            entera responsabilidad de los clientes por lo que Rebueno no se responsabiliza por los cambios realizados al respecto.
                        </u>
                        </p>
                        </li>
                        <li>
                            <p class="justificado">
                                La cancelación de las reservas deberán realizarse según las especificaciones de cada oferta en particular, caso contrario el establecimiento y
                                Rebueno se reservan el derecho de invalidar ese cupón para uso posterior. Rebueno no participa de los acuerdos futuros entre el cliente y el
                                establecimiento ni se responsabiliza por ello.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>12.</strong>
                        Sobre las <strong>devoluciones y compensación a los clientes</strong>:
                        <br/>
                        <br/>
                    </p>
                    <p class="justificado">
                        <strong>Todas las devoluciones o compensaciones a los clientes se realizarán en créditos Rebueno </strong>
                        <em><strong>(revisar políticas de Ofertas Específicas).</strong></em>
                    </p>
                    <p class="justificado">
                        La vigencia para utilizar estos créditos es de <u>90 días calendario</u> desde la fecha de su activación.
                    <br/>
                    <br/>
                    </p>
                    <p class="justificado">
                        Las devoluciones y compensaciones se aplican en los siguientes casos:
                    </p>
                    <ul>
                        <li>
                            <p class="justificado">
                                Por responsabilidad de Rebueno: devolución del 100% del monto pagado en Crédito Rebueno.
                            </p>
                        </li>
                        <li>
                            <p class="justificado">
                                Por responsabilidad del establecimiento: devolución del 100% del monto pagado en crédito Rebueno.
                            </p>
                        </li>
                        <li>
                            <p class="justificado">
                                Por imposibilidad del cliente (cancelación del cupón): mientras el cupón esté vigente se devuelve el 50% en Crédito Rebueno.
                            </p>
                        </li>
                    </ul>
                    <p>
                        <strong>
                            El cliente es responsable del uso del cupón dentro del plazo de vigencia indicado en el mismo.
                            <br/>
                            Después de la fecha de vencimiento del cupón no hay posibilidad de reclamo ni devolución alguna.
                        </strong>
                    </p>
                    <p class="justificado">
                        <strong>13.</strong>
                        Ofertas específicas:
                    </p>
                    <p class="justificado">
                        <strong>13.1</strong>
                        Cupones de Eventos: Las compras sobre ofertas de eventos (cine, teatro, espectáculos, conciertos, tours, etc.) no tienen derecho a devolución en ningún
                        caso. Todo cupón de eventos comprado será validado inmediatamente y el no uso del cupón por parte del cliente hace que pierda su dinero sin derecho a
                        reclamo.
                    </p>
                    <p class="justificado">
                        <strong>13.2</strong>
                        Cupones de Viajes: Las compras sobre ofertas de viajes y/o paquetes turísticos no son reembolsables en caso de cancelación por parte del cliente. Todo
                        cambio o reprogramación de fechas, horarios, destinos, etc. de viajes y/o paquetes turísticos deberán realizarse con la debida anticipación y coordinarse
                        directamente con el establecimiento o empresa señalado en el cupón. Estos cambios serán de entera responsabilidad de los clientes por lo que Rebueno no se
                        responsabiliza por los cambios realizados al respecto.
                    </p>
                    <p class="justificado">
                        <strong>13.3</strong>
                        Pagos extras al establecimiento: Todos aquellos pagos adicionales al cupón Rebueno que el cliente realice en el establecimiento, serán coordinados entre el
                        establecimiento y el cliente. Rebueno no se responsabilizará por estos pagos extras.
                    </p>
                    <p class="justificado">
                        <strong>13.4</strong>
                        Rebueno Productos: Todas las compras de Rebueno Productos no están sujetas a devoluciones ni cancelaciones por parte del cliente.
                        <br/>
                        Los productos adquiridos a través de la web Rebueno se sujetarán a las condiciones de despacho y entrega estipuladas en el cupón (entre 4 a 10 días útiles
                        según corresponda).
                        <br/>
                        Tratándose de productos ECUADOR.COM los cuales por sus características tengan fecha de vencimiento, se entregarán sólo en el plazo de 30 días calendario desde
                        la fecha en que se estuvo publicada la oferta en <a href="http://www.rebueno.ec/"><u>www.rebueno.ec</u></a>. Transcurrido dicho lapso de tiempo, el cliente
                        pierde el derecho a reclamar el producto y la devolución del dinero.
                        <br/>
                        Respecto a los demás productos, el cliente podrá recogerlo hasta la fecha de vencimiento estipulada en cada oferta. Caso contrario, al igual que en la
                        situación anterior, se perderá el derecho a reclamar y/o solicitar la devolución del dinero.
                        <br/>
                        Podrás gestionar la garantía del producto directamente con Rebueno, siempre y cuando sea dentro de los 07 días útiles después de haber recogido el producto
                        y previa evaluación de Rebueno. En este caso, nosotros nos encargaremos de contactar al proveedor y supervisar el cumplimiento de la misma, en caso se
                        requiera algún cambio o devolución. Para realizar la entrega de productos para la garantía es necesario dejar el mismo en su empaque original, incluyendo
                        todos los accesorios entregados en perfecto estado, con la boleta de venta y dentro del plazo fijado (hasta 07 días útiles después de haber recogido su
                        producto).
                        <br/>
                        Transcurrido este plazo, podrás gestionar la garantía directamente con el proveedor. Podrás solicitar los datos del mismo a Rebueno.
                        <br/>
                        Todo cambio de producto está sujeto a stock disponible. En caso no haya stock para el cambio, Rebueno te devolverá el íntegro de tu dinero, previa
                        evaluación de cada caso.
                        <br/>
                        Cuando existan productos ECUADOR.COM que incluyan delivery, la información del lugar de envío es de exclusiva responsabilidad del USUARIO. Los plazos elegidos
                        para el despacho y entrega, se cuentan desde que se ingresaron los datos a la web de delivery, y se consideran días hábiles(útiles) para el cumplimiento de
                        dicho plazo.
                    </p>
                    <p class="justificado">
                        <strong>14.</strong>
                        La duración de la promoción de un cupón está limitada temporalmente, estableciéndose de forma individual para cada descuento por parte de ECUADOR.COM.
                        Transcurrido el período de duración y/o unidades disponibles ya no es posible la compra, dándose por concluida la promoción. En ese sentido, los usuarios
                        se sujetan a las condiciones y restricciones de cada promoción, sea de productos o servicios indicadas en el cupón respectivo.
                    </p>
                    <p class="justificado">
                        <strong>15.</strong>
                        En la medida en que no se indique lo contrario, podrá hacerse uso de cada cupón una sola vez, haciéndolo efectivo frente al socio acudiendo al
                        establecimiento correspondiente o participando en cualquier otro acontecimiento (o percibiendo cualquier otra mercancía). En caso de que no se consumiera
                        totalmente el valor del cupón o no se hiciera uso de toda la prestación, dentro del plazo establecido, caduca la diferencia no utilizada. No es posible el
                        reembolso en estos casos.
                    </p>
                    <p class="justificado">
                        <strong>16.</strong>
                        ECUADOR.COM garantiza que el socio realizará las prestaciones con arreglo a las condiciones certificadas en el cupón, siempre y cuando el usuario presente el
                        cupón conforme a los términos y condiciones indicadas en el mismo y antes del inicio de la realización de la prestación. ECUADOR.COM no está obligada a
                        realizar reembolsos y/o indemnizaciones por daños y perjuicios derivados de la negligencia del usuario para recibir las prestaciones del cupón. ECUADOR.COM no
                        asume garantía alguna por los productos o servicios del socio adquiridos por el usuario. El socio respectivo realiza la prestación certificada en el cupón
                        en nombre propio y por cuenta propia frente al usuario, por lo que ECUADOR.COM no responde frente al usuario por incumplimiento de obligaciones del socio en el
                        momento de realizar la prestación. En caso de que surgieran problemas a la hora de hacer efectivo el cupón o de realizar la prestación, ECUADOR.COM intervendrá
                        como conciliador entre el socio y el usuario para encontrar una solución. En tal caso, los usuarios deberán comunicarse al correo: <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a> o
                        contactarse con ECUADOR.COM por vía telefónica.
                        <br/>
                        <br/>
                        <strong>17.</strong>
                        ECUADOR.COM se reserva el derecho de modificar en cualquier momento el alcance y las funciones de su página web, o de limitarlas o cancelarlas. Aunque nos
                        esforzamos por ofrecer nuestro servicio sin molestias técnicas, en particular, los trabajos de mantenimiento, la continuación del desarrollo y/o fallas
                        técnicas pueden limitar y/o parcialmente interrumpir las posibilidades de uso. Bajo determinadas circunstancias se pueden producir aquí pérdidas de datos.
                        ECUADOR.COM no asume por ello garantía alguna sobre la disponibilidad del servicio o la presencia de fallas técnicas o pérdidas de datos y en particular, no
                        tiene responsabilidad por:
                    </p>
                    <p class="justificado">
                        17.1 El uso o falta de acceso a la página, las fallas, errores, omisiones o continuidad en el funcionamiento, utilidad y fiabilidad de los servicios y de
                        la página; la alteración de la privacidad y seguridad en la utilización y contenidos de la página y de los servicios por terceros ajenos a los mismos de
                        acuerdo con el régimen legal vigente; la presencia de virus o a la presencia de otros elementos falsos en los servicios ofrecidos por terceros a través de
                        la página que puedan producir alteraciones en el sistema informático (hardware y software); la falta de veracidad, exactitud, exhaustividad y actualidad de
                        los contenidos ofrecidos en la página; la información, contenidos y servicios alojados fuera de la página, aunque fueran accesibles desde esta;
                        <br/>
                        17.2 La falta de disponibilidad y continuidad en el funcionamiento, utilidad y fiabilidad de los servicios y de la página de terceros colaboradores de
                        ECUADOR.COM.
                        <br/>
                        <br/>
                        <strong>18.</strong>
                        ECUADOR.COM y los socios se reservan todos los derechos de Propiedad Intelectual y demás derechos sobre el servicio así como sobre los contenidos publicados,
                        informaciones, imágenes, videos y bancos de datos (a continuación denominada "propiedad protegida"). Por ello, está expresamente prohibida cualquier
                        modificación, reproducción, publicación, transmisión a terceros y/o demás uso o explotación de la propiedad protegida sin el consentimiento previo por
                        escrito de ECUADOR.COM o del socio respectivamente afectado.
                        <br/>
                        <br/>
                        <strong>19.</strong>
                        No está permitida ninguna acción o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de ECUADOR.COM como
                        en las ofertas, descripciones, cuentas o bases de datos de ECUADOR.COM. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre
                        derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes,
                        así como lo hará responsable de indemnizar los daños ocasionados.
                        <br/>
                        <br/>
                        <strong>20.</strong>
                        En caso de que disposiciones concretas de estas Condiciones Generales de Contratación o del contrato concluido con la parte contratante fueran ineficaces
                        en todo o en parte, ello no afectará a la eficacia del resto del contrato.
                        <br/>
                        <br/>
                        <strong>21.</strong>
                        Estos Términos y Condiciones se rigen por la ley ecuatorian, y cualquier divergencia o discrepancia derivada de su interpretación, aplicación y ejecución será
                        sometida a un arbitraje de derecho, llevada a cabo por árbitro único, siendo el respectivo laudo definitivo e inapelable. Dicho arbitraje será efectuado
                        por el ente correspondiente en la ciudad de Guayaquil y se regirá por los reglamentos arbitrales de dicha institución, cuyas normas y condiciones las
                        partes declaran conocer y someterse de manera expresa e incondicional, para lo cual renuncian expresamente a su propio fuero.
                        <br/>
                    </p>
                    <p align="CENTER">
                        <strong>POLITICAS ECUADOR.COM DELIVERY</strong>
                    </p>
                    <p class="justificado">
                        1. Los horarios para el delivery de productos Rebueno son de lunes a viernes de 10:00 a.m. a 5:00 p.m.
                    </p>
                    <p class="justificado">
                        No se efectuarán entregas los días feriados. Las entregas de campañas especiales tienen los siguientes horarios: de 10:00 a.m a 3:00 p.m. Estos horarios y las campañas para las que aplican se comunicarán oportunamente y se indicarán en cada una de las ofertas que participe en la campaña en cuestión.
                        <br/>
                        <br/>
                        2. Para acceder al servicio de delivery, el cliente deberá ingresar sus datos requeridos en el momento de comprar. De no ingresar los datos no permitirá realizar le servicio de manera correcta.
                        <br/>
                        <br/>
                        3. Para el servicio de delivery el cliente deberá facilitar la información necesaria para realizar la entrega. La dirección de envío y las referencias
                        registradas por el usuario <u>serán de exclusiva responsabilidad del mismo. </u>Cualquier error de ingreso de datos por parte del cliente, ocasionará que
                    el Delivery no pueda ser concretado.
                    <br/>
                    <br/>
                    4. Las entregas se realizarán dentro del área urbana de Guayaquil. Salvo, casos especiales que serán indicados dentro de las condiciones de la oferta. <br/><br/>
                    Las zonas establecidas son: Samborondón (km 10), Vía a la Costa (Km 10), Ceibos, Alborada, El Cóndor,
                    Kennedy, Miraflores, Urdesa, Urdenor, Acuarelas del Rio, Brizas del Rio, La Atarazana, La Fae, La Garzota, Los Sauces, Guayacanes, 
                    Samanes, Huancavilca, Malecón, Cerro Santa Ana, Simón Bolívar, Las Orquídeas, Los Vergeles, Bellavista, San Eduardo, Los Esteros, 
                    La Fragata, La Pradera, La Saiba, Barrio Centenario y IETEL.


                    <br/>
                    <br/>
                    5.     La entrega del producto se realizará  de acuerdo al plazo establecido en la misma oferta, contando días útiles, a partir de que el cliente realice su compra y registre sus datos de Envío. De no haberse cumplido con el registro correcto de los datos del cliente, Rebueno se reserva el derecho de suspender el servicio de delivery. Si el cliente no logró acceder a registrar sus datos en un plazo no mayor a 48 horas deberá escribir a <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a> para reportar el hecho y recibir asistencia. Esto deberá realizarse en no más de 48 horas luego de haber realizado su compra.
                    <br/>
                    <br/>
                    6.   El envío no es nominativo y cualquier persona, mayor de 18 años y debidamente documentada (Cédula de Identidad), podrá recibirlo. Para recibir el producto es obligatorio contar con el cupón de Rebueno impreso y copia de la Cédula de Identidad si no es el titular. Esta a su vez deberá firmar en señal de conformidad la Guía de Entrega correspondiente. No se entregará el producto a personas que se nieguen a firmar esta Guía o que no cuenten con la Cédula de Identidad al momento de la entrega. La recepción del producto indica conformidad del estado.
                    <br/>
                    <br/>
                    7.   El servicio de delivery se realizará en un solo intento. De no poder realizarse la entrega, el cliente deberá escribir un correo electrónico a <a href="mailto:clientes@rebueno.ec"><u>clientes@rebueno.ec</u></a> y coordinar el recojo del producto en en Sauces II Mz. F111 Solar 108 en los horarios de lunes
                    a viernes de 10:00 a.m. a 5:00 p.m. El producto estará sujeto a disponibilidad. En ningún caso el servicio de delivery podrá ser reprogramado y tampoco <u>se podrán aplicar devoluciones asociadas al pago del delivery.</u>
                    <br/>
                    <br/>
                    8.     Los productos Rebueno no están sujetos a devoluciones. En caso de fallas en el producto, el cliente deberá <u>(en un plazo de 07 días útiles desde la fecha en que se registra la entrega del producto)</u> comunicarse con Rebueno y hacer la solicitud del mismo. En ningún caso, la empresa de delivery realiza cambios de productos, este servicio sólo entregará el producto sellado y cerrado.
                    </p>

                </div>
            </div>

        </section>
    </div>
</div>