<?php echo $this->form()->openTag($this->form); ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Registro de Hospedaje</h4>
    </div>
    <div class="panel-body">
        <div class="form-group">
            <label for="descripcion_hospedaje" class="col-lg-3 control-label">Nombre de Hospedaje :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('descripcion_hospedaje')); ?>
                <?php echo $this->formRow($this->form->get('id_hospedaje')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="id_tipo" class="col-lg-3 control-label">Tipo Hospedaje :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('id_tipo')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="id_pais" class="col-lg-3 control-label">Pais :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('id_pais')); ?>
            </div>
        </div>
        <div class="form-group" id="contenido-departamento">
            <label for="id_departamento" class="col-lg-3 control-label">Ciudad :</label>
            <div class="col-lg-7"> 
                <?php echo $this->formRow($this->form->get('id_departamento')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="categoria_hospedaje" class="col-lg-3 control-label">Categoría de Hospedaje :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('categoria_hospedaje')); ?>
            </div>
        </div>
        
        <div class="form-group">
            <label for="direccion_hospedaje" class="col-lg-3 control-label">Dirección Hospedaje :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('direccion_hospedaje')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="telefono_hospedaje" class="col-lg-3 control-label">Teléfono Hospedaje :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('telefono_hospedaje')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="telefono_hospedaje" class="col-lg-3 control-label">Adicionales Comunes :</label>
            <div class="col-lg-7">
                <?php $contador = 0;
                      foreach ($adicionalesHospedaje as $adicionalHos) {
                        $contador++; ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="id_adicionales_hospedaje[]" id="id_adicionales_hospedaje[]" value="<?php echo $adicionalHos['id_adicionales']; ?>" <?php if($adicionalHos['seleccionado'] != '0') { ?>checked<?php } ?>> <?php echo $adicionalHos['descripcion_adicionales']; ?>
                            </label>
                        </div>
                <?php } ?>    
            </div>
        </div>
        <div class="form-group">
            <label for="fecha_validez" class="col-lg-3 control-label">Tipos de Habitaciones:</label>
            <div class="col-lg-7" >
                <div class="well">
                
                <div class="table-responsive">
                    <table class="table table-hover table-bordered" id="js-tabla-opciones">
                        <thead >
                            <tr class="btn-danger">
                                <th>#</th>
                                <th>Descripción</th>
                                <th>Precio</th>
                                <th>Adicionales</th>
                                <th></th>
                            </tr>
                        </thead>
                        
                    </table>
                </div>
                    <div class="btn btn-warning" onclick="javascript:nuevaOpcion()" title='Nueva opción de venta'><samp class=" glyphicon glyphicon-file"></samp> Nueva Opción de venta</div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-7">
                <?php echo $this->formRow($this->form->get('submit')); ?>&nbsp;&nbsp;&nbsp;&nbsp;
                <?php echo $this->formRow($this->form->get('btn-regresar')); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<div class="modal fade" id="modalEditor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Opción - Campaña</h4>
            </div>
            <div class="modal-body" style="height:580px">
                <form>
                    <div class="form-group">
                        <label for="id_categoria" class="col-lg-4 control-label">Tipo Habitación :</label>
                        <div class="col-xs-9"> 
                            <input type="hidden" class="form-control" name="id_hospedaje_categoria" id="id_hospedaje_categoria" value="">
                            <select class="form-control input-sm" name="id_categoria" id="id_categoria">
                                <option value="0">Seleccione Tipo Habitación</option>
                                <?php foreach ($categoriaHabitacion as $categoria) { ?>
                                    <option value="<?php echo $categoria->id_categoria; ?>"><?php echo $categoria->descripcion_categoria; ?></option>
                                <?php } ?>
                            </select>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="importe_habitacion" class="col-lg-4 control-label">Precio Habitación :</label>
                        <div class="col-xs-9"> 
                            <input type="text" class="form-control" name="importe_habitacion" id="importe_habitacion" value="">
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                <button class="btn btn-primary" onclick="javascript:grabaOpcion();"> &nbsp; Ok &nbsp; </button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        // Delete button popover confirmation
        $('#hospedajeForm').formValidation({
            message: 'El valor no es válido.',
            err: {
                container: 'tooltip'
            },
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh',
            },
            fields: {
                descripcion_hospedaje: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre el Nombre del Hospedaje.'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9ñáéíóúÑÁÉÍÓÚ& ,.-]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 150,
                            message: 'Este campo debe contener 150 caracteres como máximo.'
                        }
                    }
                },
                id_tipo: {
                    err: 'popover',
                    //icon: false,
                    validators: {
                        greaterThan: {
                            value: 1,
                            message: 'Por favor seleciione el Tipo de Hospedaje.'
                        }
                    }
                }
            }
        }).on('success.form.fv', function (e) {
            $("#modalConfirmacion").modal('show');
        });
        
        $('#id_pais').change(function(){
            var pais   = $('#id_pais').val();
            $.ajax({
                type: "POST",
                url: "/index/departamentos",
                data: {pais: pais},
                success: function (data) {
                    $('#contenido-departamento').html(data);
                }
            });
        });

        $("#modal-confirmacion-si").click(
            function (e) {
                $('button').removeClass('fv-hidden-submit disabled').addClass('fv-hidden-submit');
                $('.fv-hidden-submit').removeAttr('disabled');
                $("#modalConfirmacion").modal('hide');
                $('.fv-hidden-submit').click();
            }
        );

        $("#modal-confirmacion-no").click(
            function (e) {
                $('#submit').removeClass('btn btn-primary disabled').addClass('btn btn-primary');
                $('#submit').removeAttr('disabled');
                $("#modalConfirmacion").modal('hide');
            }
        );

        $("#btn-regresar").click(
            function (e) {
                $("#modalCancelacion").modal('show');
            }
        );

        $("#modal-cancelacion-si").click(
            function (e) {
                $(location).attr('href','/dashboard/hospedaje/list');
            }
        );

        $("#modal-cancelacion-no").click(
            function (e) {
                $("#modalCancelacion").modal('hide');
            }
        );


    });
    
    function nuevaOpcion() {
        $('#id_hospedaje_categoria').val($('#id_hospedaje').val());
        $('#id_categoria').val('0');
        $('#importe_habitacion').val('0.00');
        $('#modalEditor').modal('show');
    }
</script>