<br/>
<div class="container"><b>Firma de Contrato Rebueno</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-success btn-sm" id="refresca_documento"><span class="glyphicon glyphicon-user"></span> Registrar Firma</a></div>
<br/>
<div class="container">
    <iframe src='/empresa/ver-contrato-pdf?nombre_documento=<?php echo $nombre_documento;?>' class="container" style="height:600px"/>
</div>
<br/>
