<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>Documento PDF</title>
        <style type="text/css">
            body {
                font-family: Helvetica;
            }
            
            .letra-cupon{
                font-size: 16px;
                font-weight: bold;
                text-align: right;
            }

            .letra-cupon-min {
                font-size: 13px;
                font-weight: bold;
                text-align: right;

            }

            .borde-cupon-externo{
                border-style:solid;
                border-width: 4px;
                width: 100%;
                background-color: #ffffff;
                padding: 10px;;
            }

            .separacion-cupon{
                border-bottom-style:solid;
                border-bottom-width:2px;
                display: block;
                width: 100%;
                padding: 10px;
            }

            .separacion-empresa{
                display: block;
                width: 100%;
                padding: 10px;
            }

            .en-linea {
                display:inline-block;
            }

            .en-linea.logo-ofeta {
                width: 40%
            }

            .en-linea.texto {
                width: 59%
            }

            .en-linea.empresa {
                width: 70%
            }

            .en-linea.mapa {
                width: 29%;
                vertical-align: top;
            }
            
            .logo-fijo {
                width: 100px; 
                height: 35px;
                background-image: url('<?php echo $localhost; ?>/img/logo_rebueno_cupon.png');
            }
            
        </style>
    </head>
    <body>
    <div>
    <div class="borde-cupon-externo">
        <div class="separacion-cupon">
            <div class="en-linea logo-ofeta"><div class="logo-fijo"></div></div>
            <div class="en-linea texto"><p class="letra-cupon">Número de Cupón: <?php echo $codigo_cupon;?><br>Válido por 1 cupón</p></div>
        </div>
        <div class="separacion-cupon">
            <div class="en-linea logo-ofeta"><img src="<?php echo $localhost; ?>/img/<?php echo $id_campana; ?>/small2/image1.jpg"></div>
            <div class="en-linea texto"><p class="letra-cupon">Tu compra en Rebueno:<br><?php echo $campana_descripcion;?></p>
                    <p class="letra-cupon-min">Fecha Compra : <?php echo $fecha_compra;?></p>
                    <?php if( !empty($fecha_validez) ) { ?>
                    <p class="letra-cupon-min">Fecha Válidez : <?php echo $fecha_validez;?></p>
                    <?php } ?>
            </div>
        </div>
        <div class="separacion-cupon">
            <div><p><b>La oferta incluye:</b><br><?php echo $sobre_campana;?></p></div>
        </div>
        <div class="separacion-empresa">
            <div><p><b>Nuestro Proveedor:</b></div>
            <div><?php echo $razon_social; ?></div>
            <div>
                <div class="en-linea empresa">
                    <div><?php echo $descripcion_empresa; ?></div>
                    <div><b>Sitio Web:</b></div>
                    <div><?php echo $web_site; ?></div>
                    <div><b>Dirección:</b></div>
                    <div><?php echo $direccion; ?></div>
                    <div><b>Horario:</b></div>
                    <div><?php echo $horario; ?></div>
                </div>
                <div class="en-linea mapa"><img id="companyMap" src="<?php echo $ubicacion_gps; ?>"></div>
            </div>
        </div>
    </div>
    
</div>
    </body>
</html>
