<div class="container">
    <div class="borde-cupon-externo">
        <div class="separacion-banco">
            <div class="en-linea logo-oferta"><div class="logo-fijo-cupon"></div></div>
            <div class="en-linea texto"><p class="letra-cupon">Error Payme</p></div>
            <div><p>Transacción: <?php echo $orden;?></p></div>
            <div><p>Mensaje: <?php echo $mensaje;?></p></div>
        </div>
    </div>
</div>
