<div class="container">
<form name="frmpago" role="form" action="/campana/pago" method="POST" data-parsley-validate>
    <div class="section_payment">
        <?php if (($fl != null && $fl == '2') || isset($user_session->username) ) { ?>
            <h3>Tus Datos</h3>
            <?php if($user_session->facebook == 'S') {?>
            <div class="form-group">
                <label class="col-lg-2 control-label"></label>
                <div class="col-xs-7">
                <input type="hidden" class="form-control" name="facebook" id="facebook" value="<?php echo $user_session->facebook;?>">
                <input type="hidden" class="form-control" name="email" id="email" value="<?php echo $user_session->username;?>">
                <input type="hidden" class="form-control" name="nombre" id="email" value="<?php echo $user_session->nombre;?>">
                <input type="hidden" class="form-control" name="apellido" id="email" value="<?php echo $user_session->apellido;?>">
                <div class="cfacebook">Conectado con Facebook</div>
                </div>
            </div>
            <div class="form-group">
                <label for="nombre" class="col-lg-2 control-label">Nombres:</label>
                <div class="col-xs-7"> 
                    <input type="text" class="form-control" name="nombres" id="nombres" value="<?php echo $user_session->nombres;?>"  disabled>
                    
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <?php } else { ?>
            <div class="form-group">
                <label for="nombres" class="col-lg-2 control-label">Nombres:</label>
                <div class="col-xs-7"> 
                    <input type="hidden" class="form-control" name="email" id="email" value="<?php echo $user_session->username;?>">
                    <input type="hidden" class="form-control" name="nombre" id="email" value="<?php echo $user_session->nombre;?>">
                    <input type="hidden" class="form-control" name="apellido" id="email" value="<?php echo $user_session->apellido;?>">
                    <input type="text" class="form-control" name="nombres" id="nombres" value="<?php echo $user_session->nombre;?>" disabled>
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="apellidos" class="col-lg-2 control-label">Apellidos:</label>
                <div class="col-xs-7">
                    <input type="text" class="form-control" name="apellidos" id="apellidos" maxlength="50" pattern="^[A-z-ñáéíóúÑÁÉÍÓÚ ]+$" data-error="Solo letras, espacios y guiones (-)."  required  value="<?php echo $user_session->apellido;?>" disabled>
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="tpdoc" class="col-lg-2 control-label">Tipo de documento:</label>
                <div class="col-xs-7">
                    <select class="form-control" name="tipdoc" id="tipdoc" data-error="Seleccione una opción." required disabled>
                        <option value="DNI" label="DNI">DNI</option>
                        <option value="RUC" label="RUC">RUC</option>
                        <option value="PAS" label="Pasaporte">Pasaporte</option>
                        <option value="CEX" label="Carnét de Extranjería">Carnét de Extranjería</option>
                    </select>
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="numdoc" class="col-lg-2 control-label">Número de documento:</label>
                <div class="col-xs-7">
                    <input type="text" class="form-control" name="numdoc" id="numdoc" pattern="^[A-z0-9-ñáéíóúÑÁÉÍÓÚ]+$" data-error="Solo letras, números y guiones (-)." required  value="<?php echo $user_session->numdoc;?>" disabled>
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="telefono" class="col-lg-2 control-label">Teléfono:</label>
                <div class="col-xs-7">
                    <input type="text" class="form-control"  name="telefono" id="telefono" pattern="^[0-9-]+$" data-error="Solo números y guiones (-)." required  value="<?php echo $user_session->telefono;?>" disabled>            
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="celular" class="col-lg-2 control-label">Celular:</label>
                <div class="col-xs-7">
                    <input type="text" class="form-control" name="celular" id="celular" pattern="^[0-9-]+$" data-error="Solo números y guiones (-)." required  value="<?php echo $user_session->celular;?>" disabled>            
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="genero" class="col-lg-2 control-label">Género:</label>
                <div class="col-xs-7">
                    <div class="radio" >
                        <label><input type="radio" name="genero" id="genero" value="M" required checked disabled>Masculino</label>
                    </div>
                    <div class="radio" >
                        <label><input type="radio" name="genero" id="genero" value="F" required disabled>Femenino</label>
                    </div>
                </div>
            </div>
            <?php } ?>
        <?php } else { ?>
            <div class="title">
                <h3><?php if ($fl != null) { ?>Ingresa a tu cuenta<?php } else { ?>Regístrate<?php } ?></h3>
                <?php if ($fl == null) { ?>
                    <a class="already_registered" title="Ya tengo una cuenta" href="javascript:postfunction('../campana','formulariopago','<?php echo base64_encode($id); ?>','<?php echo base64_encode($op); ?>','<?php echo base64_encode('1') ?>');">Ya tengo una cuenta</a>
                <?php } ?>
            </div>
            <!--div class="fb-login-button" data-max-rows="1" data-size="large" data-show-faces="false" data-auto-logout-link="false" onlogin="checkLoginState();">Conectar con Facebook</div-->
            <a class="btn btn-block btn-social btn-facebook" href="javascript:loginFacebook();">
                                        <i class="fa fa-facebook"></i> Conectar con Facebook
                                    </a>
            <br>
            <hr class="special">
            <br>
            <div class="form-group">
                <label for="email" class="col-lg-2 control-label"><span class="required">* </span>Email:</label>
                <div class="col-xs-7">
                    <input type="email" class="form-control" name="email" id="email" value="" maxlength="50" required>
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="clave" class="col-lg-2 control-label"><span class="required">* </span>Contraseña:</label>
                <div class="col-xs-7">
                    <input type="password" class="form-control" name="clave" id="clave" value="" maxlength="20" required>
                    <span class="help-block with-errors"></span>
                </div>
            </div>
            <?php if ($fl != null) { ?>
                <div class="form-group">
                    <div class="btn-group-justified">
                        <div class="col-xs-5">
                            <button type="button" class="btn btn-primary" id="valida_cancelar">Cancelar</button>
                        </div>
                        <div class="col-xs-5">
                            <button type="button" class="btn btn-danger"  id="valida_ingreso">Ingresar</button>
                        </div>
                    </div>
                </div>
            <?php } else { ?>
                <div class="form-group">
                    <label for="clave2" class="col-lg-2 control-label"><span class="required">* </span>Repetir Contraseña:</label>
                    <div class="col-xs-7">
                        <input type="password" class="form-control" name="clave2" id="clave2" value="" required>
                        <span class="help-block with-errors"></span>
                    </div>
                </div>
                <hr class="normal">
                <h3>Tus Datos</h3>
                <div class="form-group">
                    <label for="nombre" class="col-lg-2 control-label"><span class="required">* </span>Nombres:</label>
                    <div class="col-xs-7">
                        <input type="text" class="form-control" name="nombre" id="nombre" maxlength="50" pattern="^[A-z-ñáéíóúÑÁÉÍÓÚ ]+$" data-error="Solo letras, espacios y guiones (-)."  required>
                        <span class="help-block with-errors"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="apellido" class="col-lg-2 control-label"><span class="required">* </span>Apellidos:</label>
                    <div class="col-xs-7">
                        <input type="text" class="form-control" name="apellido" id="apellido" maxlength="50" pattern="^[A-z-ñáéíóúÑÁÉÍÓÚ ]+$" data-error="Solo letras, espacios y guiones (-)."  required>
                        <span class="help-block with-errors"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="tpdoc" class="col-lg-2 control-label"><span class="required">* </span>Tipo de documento:</label>
                    <div class="col-xs-7">
                        <select class="form-control" name="tipdoc" id="tipdoc" data-error="Seleccione una opción." required>
                            <option value="DNI" label="DNI">DNI</option>
                            <option value="RUC" label="RUC">RUC</option>
                            <option value="PAS" label="Pasaporte">Pasaporte</option>
                            <option value="CEX" label="Carnét de Extranjería">Carnét de Extranjería</option>
                        </select>
                        <span class="help-block with-errors"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="numdoc" class="col-lg-2 control-label"><span class="required">* </span>Número de documento:</label>
                    <div class="col-xs-7">
                        <input type="text" class="form-control" name="numdoc" id="numdoc" pattern="^[A-z0-9-ñáéíóúÑÁÉÍÓÚ]+$" data-error="Solo letras, números y guiones (-)." required>
                        <span class="help-block with-errors"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="telefono" class="col-lg-2 control-label"><span class="required">* </span>Teléfono:</label>
                    <div class="col-xs-7">
                        <input type="text" class="form-control"  name="telefono" id="telefono" pattern="^[0-9-]+$" data-error="Solo números y guiones (-)." required >            
                        <span class="help-block with-errors"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="celular" class="col-lg-2 control-label"><span class="required">* </span>Celular:</label>
                    <div class="col-xs-7">
                        <input type="text" class="form-control" name="celular" id="celular" pattern="^[0-9-]+$" data-error="Solo números y guiones (-)." required >            
                        <span class="help-block with-errors"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="genero" class="col-lg-2 control-label"><span class="required">* </span>Género:</label>
                    <div class="col-xs-7">
                        <div class="radio" >
                            <label><input type="radio" name="genero" id="genero" value="M" required checked>Masculino</label>
                        </div>
                        <div class="radio" >
                            <label><input type="radio" name="genero" id="genero" value="F" required>Femenino</label>
                        </div>
                    </div>
                </div>
                <?php
            }
        }
        ?>
    </div>
    <?php foreach ($data_o as $dato) { ?>
        <div class="section_payment">
            <h3>Confirma tu pedido</h3>
            <div class="box_payment">
                <h4 class="titulo_negro">Producto</h4>
                <div class="box_center_info">
                    <img class="img_container_pago" src="/img/<?php echo $id; ?>/small2/image1.jpg">
                    <span><?php echo $dato['descripcion']; ?></span>
                </div>
                <div class="box_quantity">
                    <span class="quantity">
                        <input type="hidden" name="IdCampana" id="IdCampana" value="<?php echo base64_encode($id); ?>">
                        <input type="hidden" name="IdOpcion" id="IdOpcion" value="<?php echo base64_encode($op); ?>">
                        <input type="hidden" name="PriceUnit" id="PriceUnit" value="<?php echo $dato['precio_especial']; ?>">
                        <input type="hidden" name="PriceTotal" id="PriceTotal" value="<?php echo $dato['precio_especial']; ?>">
                        <span id="lblPriceUnit" class="price_subtotal"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_especial']; ?></span>
                        <span class="form_quantity">
                            <span>Cant: </span>
                            <input class="text_cantidad" type="text" name="cantidad" id="txtQuantity" value="1" required="" data-parsley-trigger="change focusin keyup" data-parsley-min="1" data-parsley-min-message="Debe comprar un mínimo de 1" data-parsley-max="10" data-parsley-max-message="Debe comprar un máximo de 10" maxlength="3" data-parsley-type="digits" data-parsley-required-message="Ingrese una cantidad." data-parsley-errors-container=".error_quantity">                </span>
                    </span><br><br>
                </div>
                <div id="boxStockError" class="box_info error hide">
                    <span class="ico_alert"></span>
                    <span class="error_quantity"></span>
                </div>
                <div class="subtotal"><br><b>Sub total: </b><span id="lblSubtotal" class="price_subtotal"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_especial']; ?></span></div>
                <div class="subtotal"><br><b>Total: </b><span id="lblTotal" class="price"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_especial']; ?></span>
                </div>
            </div>
        </div>
    <?php } ?>
    

    <div class="section_payment">
        <h3>Método de Pago</h3>
        <div class="box_payment">
            <h4 class="titulo_negro">Método de Pago </h4>
            <!-- P3_Comprar -->
            <div class="metodo_pago">
                <label for="radPayVisa" class="ioption">
                    <input id="radPayVisa" name="metodo" type="radio" value="001" checked><span><img src="/img/tarjetas/visa.jpg"></span>
                    <div class="cb">Paga con Tarjeta de Crédito Visa</div>
                </label>
            </div>
            <div class="metodo_pago">
                <label for="radPayPayme" class="ioption">
                    <input id="radPayPayme" name="metodo" type="radio" value="PAY" checked><span><img src="/img/tarjetas/visa.jpg"></span>
                    <div class="cb">Paga con Payme</div>
                </label>
            </div>
            <div class="metodo_pago">
                <label for="radPayBanco" class="ioption">
                    <input id="radPayBanco" name="metodo" type="radio" value="999"><span><img src="/img/tarjetas/banco.jpg"></span>
                    <div class="cb">Paga con transferencia o depósito Bancario</div>
                </label>
            </div>
            <div class="metodo_pago terminos">
                <input type="hidden" name="terminospay" value="0"><input type="checkbox" name="terminospay" id="chkTermsPay" value="1" checked="checked" required="" data-parsley-trigger="change" data-parsley-errors-container=".terms_error_pay">
                Acepto los <a href="/interes/terminosycondiciones" target="_blank" title="Términos y Condiciones">Términos y Condiciones</a>, y <a href="/interes/politicasdeprivacidad" title="Políticas de Privacidad" target="_blank">Políticas de Privacidad</a>
            </div>
            <div class="metodo_pago">
                <button type="submit" class="btn btn_buy_action">Pagar</button>
            </div>
        </div>
    </div>
</form>
</div>
<div id="status"></div>
<div id="fb-root"></div>
<script type="text/javascript">

    

    $(document).ready(function () {

        $("#txtQuantity").blur(function () {
            $cantidad = $("#txtQuantity").val();
            $precio = $("#PriceUnit").val();
            $total = $precio * $cantidad;
            $total_fixed = parseFloat($total).toFixed(2);
            $("#PriceTotal").val($total_fixed);
            $("#lblSubtotal").html('<?php echo $moneda['simbolo'];?> ' + $total_fixed);
            $("#lblTotal").html('<?php echo $moneda['simbolo'];?> ' + $total_fixed);
        });

        $("#valida_cancelar").click(function () {
            postfunction('campana','detalle', '<?php echo base64_encode($id); ?>');
        });

        $("#valida_ingreso").click(function () {

            var email = $("#email").val();
            var password = $("#clave").val();

            if (email != "" && password != "") {
                $.ajax({
                    type: "POST",
                    url: "/campana/cliente",
                    data: {email: email, password: password},
                    success: function (data) {
                        var cliente = $.parseJSON(data);
                        if (cliente[0]) {
                            if (cliente[0].validar == '1') {
                                postfunction('campana','formulariopago', '<?php echo base64_encode($id); ?>', '<?php echo base64_encode($op); ?>', '<?php echo base64_encode('2'); ?>', cliente[0].email);
                            } else {
                                if (cliente[0].validar == '2') {
                                    alert('Password no coincide.');
                                } else {
                                    alert('Usuario no registrado.');
                                }
                            }
                        } else {
                            alert('Tuvimos problemas para procesar su solicitud.');
                        }
                        //alert(data.email_cliente);
                    }
                });
            } else {
                alert('Ingrese usuario y password.');
            }
            ;

        });

        //alert('hola');

<?php if (isset($f1)) {
    if ($fl == '2') {
        ?>

                //alert('chau');
                $.ajax({
                    type: "POST",
                    url: "../../../../../campana/cliente",
                    data: {email: '<?php echo base64_encode($em); ?>', tipo: 'E'},
                    success: function (data) {
                        //alert(data);
                        var cliente = $.parseJSON(data);
                        if (cliente[0]) {
                            $("#email").val(cliente[0].email_cliente);
                            $("#nombre").val(cliente[0].nombres);
                            $("#apellido").val(cliente[0].apellidos);
                            $("#tipdoc").val(cliente[0].id_tipo_documento);
                            $("#numdoc").val(cliente[0].numero_documento);
                            $("#telefono").val(cliente[0].telefono);
                            $("#celular").val(cliente[0].celular);
                            $("input[name=genero][value=" + cliente[0].id_sexo + "]").prop("checked", true);
                        } else {
                            alert('Tuvimos problemas para procesar su solicitud.');
                        }
                        //alert(data.email_cliente);
                    }
                });
    <?php }
}
?>

    });
    
    function verifyUser(email, fname, lname, sex) {

        $.ajax({
            type: "POST",
            url: "/campana/cliente",
            data: {email: email, fname: fname, lname: lname, sex: sex, facebook: '1'},
            success: function (data) {
                var cliente = $.parseJSON(data);
                if (cliente[0]) {
                    if (cliente[0].validar == '1') {
                        var url = '/campana/formulariopago/<?php echo base64_encode($id); ?>/<?php echo base64_encode($op); ?>/<?php echo base64_encode('2'); ?>';
                        $(location).attr('href',url);
                    }
                }
            }
        });

    }

</script>