<div class="container">
    <div class="borde-cupon-externo">
        <div class="separacion-banco">
            <div class="en-linea logo-oferta"><img src="<?php echo $localhost;?>/img/logo_rebueno.png"></div>
            <div class="en-linea texto"><p class="letra-cupon">Gracias por tu preferencia...</p></div>
            <div><p>Estas a punto de obtener una oferta rebuena, tan s&oacute;lo debes de completar la compra del cup&oacute;n, realizando un dep&oacute;sito o Transferencia Bancaria en las siguiente cuenta:</p></div>
            <div>
                <div class="en-linea logo-banco"><img src="<?php echo $localhost;?>/img/bco_pichincha.png"></div>
                <div class="en-linea texto"><p class="letra-cupon">
                        Banco Pichincha<br>
                        Cuenta corriente en d&oacute;lares : 2100101289
                </div>
            </div>
            <div><p>Monto a D&eacute;positar: $ <?php echo $peciototal;?></p></div>
            <div><p>N&uacute;mero de Transacci&oacute;n Rebueno: <?php echo $operacion;?></p></div>
            <div><p>Una vez realizado el dep&oacute;sito o transferencia, env&iacute;anos un correo a clientes@rebueno.ec indic&acute;ndonos en el asunto la frase "N&uacute;mero de Transacci&oacute;n Rebueno <?php echo $operacion;?>" y en el contenido del mensaje, el n&uacute;mero de operaci&oacute;n que figure en el comprobante de pago o un escaneo del mismo.</p></div>
        </div>
    </div>
</div>
