<div class="container">
    <div class="borde-cupon-externo">
        <div class="separacion-banco">
            <div class="en-linea logo-oferta"><img src="<?php echo $localhost;?>/img/logo_rebueno.png"></div>
            <div class="en-linea texto"><p class="letra-cupon">Gracias por tu preferencia...</p></div>
            <div><p>Estas a punto de obtener una oferta rebuena, solo tiene que completar el pago respectivo con Dep&oacute;sito o Transferencia Bancaria en las siguientes cuentas:</p></div>
            <div>
                <div class="en-linea logo-banco"><img src="<?php echo $localhost;?>/img/bco_pichincha.png"></div>
                <div class="en-linea texto"><p class="letra-cupon">
                        Banco Pichincha<br>
                        Cuenta en D&oacute;lares : 667778888999999-0
                </div>
            </div>
            <div><p>N&uacute;mero de Transacci&oacute;n Rebueno: <?php echo $operacion;?></p></div>
            <div><p>Monto a D&eacute;positar: $ <?php echo $peciototal;?></p></div>
            <div><p>Cuando haga el dep&oacute;sito correspondiente enviemos un correo a clientes@rebueno.ec haciendo referencia N&uacute;mero de Transacci&oacute;n de Rebueno y adjuntando el n&uacute;mero de operaci&oacute;n de su Dep&oacute;sito o llamanos al <?php echo $telefono;?>.</p></div>
        </div>
    </div>
</div>
