<div class="container">
    <div class="box_center">
        <div class="box_center">
            <h2>¿Has olvidado tu contraseña?</h2>
            <hr>
            <span id="mensajeerror"></span>
            <form method="POST" id="frmrecuperar" name="frmrecuperar" validate>
                <p class="mb20">Por favor introduzca su email si desea recibir una nueva contraseña.</p>
                <div class="form_control col-xs-8">
                    <div class="form-group">
                        <label for="email" class="col-lg-1 control-label">Email:</label>
                        <div class="col-xs-6">
                            <input type="email" class="form-control" name="email" id="email" value="" maxlength="50" required>
                            <span class="help-block with-errors"></span>
                            <!--div name="enviar" id="enviar" class="btn btn-danger" onclick="javascript:recuperaPass();" >Enviar Contraseña</div-->
                            <input type="submit" class="btn btn-danger"  value="Enviar Contraseña">

                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("#frmrecuperar").submit(function (e) {
        e.preventDefault();
        var email = $('#email').val();
        $.ajax({
            type: "POST",
            url: "/cliente/emailclave",
            data: {email: email},
            success: function (data) {
                var cliente = $.parseJSON(data);

                if (cliente[0].validar == '1') {
                    var shtm = "<div class='alert alert-warning alert-dismissible' role='alert' style='display:'>";
                    shtm = shtm + "<button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>";
                    shtm = shtm + "<strong>Enviado!</strong> Se envio un e-mail con las instrucciones para la recuperación de su contraseña.</div>";
                    $('#mensajeerror').html(shtm);
                } else {
                    postfunction('/campana', 'registrar', '1');
                }

            }
        });
    });
</script>
