<?php echo $this->form()->openTag($this->form); ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Registro de Usuario</h4>
    </div>
    <div class="panel-body">
        <?php if (!empty($this->message)) { ?>
            <div class="form-group">
                <div class="alert alert-danger">
                    <?php echo $this->message; ?>
                </div>
            </div>
        <?php } ?>
        <div class="form-group">
            <label for="full_name" class="col-lg-2 control-label">Nombre :</label>
            <div class="col-lg-3">
                <?php echo $this->formRow($this->form->get('full_name')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="username" class="col-lg-2 control-label">Usuario :</label>
            <div class="col-lg-3">
                <?php echo $this->formRow($this->form->get('username')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-lg-2 control-label">Clave :</label>
            <div class="col-lg-3">
                <?php echo $this->formRow($this->form->get('password')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-lg-2 control-label">Email :</label>
            <div class="col-lg-3">
                <?php echo $this->formRow($this->form->get('email')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="role_id" class="col-lg-2 control-label">Role :</label>
            <div class="col-lg-3">
                <?php echo $this->formRow($this->form->get('role_id')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-7">
                <?php echo $this->formRow($this->form->get('submit')); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
