<?php echo $this->form()->openTag($this->form); ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Registro de Voucher de Hospedaje</h4>
    </div>
    <div class="panel-body">
        <div class="form-group">
            <label for="codigo_cupon" class="col-lg-3 control-label">Código Cupón :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('codigo_cupon')); ?>
                <?php echo $this->formRow($this->form->get('id_voucher')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="id_hospedaje" class="col-lg-3 control-label">Hospedaje :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('id_hospedaje')); ?>
            </div>
        </div>
        <div class="form-group" id="contenido-categoria">
            <label for="id_categoria" class="col-lg-3 control-label">Tipo Habitación :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('id_categoria')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="fecha_ingreso" class="col-lg-3 control-label">Check In :</label>
            <div class="col-lg-2">
                <div class="input-group date" id='fecha_ingreso'>
                    <?php echo $this->formRow($this->form->get('fecha_ingreso')); ?>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="fecha_salida" class="col-lg-3 control-label">Check Out :</label>
            <div class="col-lg-2">
                <div class="input-group date" id='fecha_salida'>
                    <?php echo $this->formRow($this->form->get('fecha_salida')); ?>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="numero_dias" class="col-lg-3 control-label">Número Noches :</label>
            <div class="col-lg-1">
                <?php echo $this->formRow($this->form->get('numero_dias')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="cantidad_adultos" class="col-lg-3 control-label">Cantidad Adultos :</label>
            <div class="col-lg-1">
                <?php echo $this->formRow($this->form->get('cantidad_adultos')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="cantidad_ninos" class="col-lg-3 control-label">Cantidad Niños :</label>
            <div class="col-lg-1">
                <?php echo $this->formRow($this->form->get('cantidad_ninos')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="cantidad_infantes" class="col-lg-3 control-label">Cantidad Infantes :</label>
            <div class="col-lg-1">
                <?php echo $this->formRow($this->form->get('cantidad_infantes')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="observacion" class="col-lg-3 control-label">Observación :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('observacion')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="nombre_pasajero" class="col-lg-3 control-label">Nombre Pasajero :</label>
            <div class="col-lg-4">
                <?php echo $this->formRow($this->form->get('nombre_pasajero')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="total_habitaciones" class="col-lg-3 control-label">Total Habitaciones :</label>
            <div class="col-lg-1">
                <?php echo $this->formRow($this->form->get('total_habitaciones')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="codigo_reserva" class="col-lg-3 control-label">Código Reserva :</label>
            <div class="col-lg-4">
                <?php echo $this->formRow($this->form->get('codigo_reserva')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-7">
                <?php echo $this->formRow($this->form->get('submit')); ?>&nbsp;&nbsp;&nbsp;&nbsp;
                <?php echo $this->formRow($this->form->get('btn-regresar')); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function () {

        // Delete button popover confirmation
        $('#tipohospedajeForm').formValidation({
            message: 'El valor no es válido.',
            err: {
                container: 'tooltip'
            },
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh',
            },
            fields: {
                descripcion_tipo: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre el Tipo de Hospedaje.'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9ñáéíóúÑÁÉÍÓÚ& ,.-]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 45,
                            message: 'Este campo debe contener 45 caracteres como máximo.'
                        }
                    }
                }    
            }
        }).on('success.form.fv', function (e) {
            $("#modalConfirmacion").modal('show');
        });

        $("#modal-confirmacion-si").click(
            function (e) {
                $('button').removeClass('fv-hidden-submit disabled').addClass('fv-hidden-submit');
                $('.fv-hidden-submit').removeAttr('disabled');
                $("#modalConfirmacion").modal('hide');
                $('.fv-hidden-submit').click();
            }
        );

        $("#modal-confirmacion-no").click(
            function (e) {
                $('#submit').removeClass('btn btn-primary disabled').addClass('btn btn-primary');
                $('#submit').removeAttr('disabled');
                $("#modalConfirmacion").modal('hide');
            }
        );

        $("#btn-regresar").click(
            function (e) {
                $("#modalCancelacion").modal('show');
            }
        );

        $("#modal-cancelacion-si").click(
            function (e) {
                $(location).attr('href','/dashboard/tipohospedaje/list');
            }
        );

        $("#modal-cancelacion-no").click(
            function (e) {
                $("#modalCancelacion").modal('hide');
            }
        );

        $('#fecha_ingreso,#fecha_salida').datetimepicker({
            format: 'yyyy-mm-dd',
            language: 'es',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 2,
            forceParse: 0

        });
        
        $('#id_hospedaje').change(function(){
            var hospedaje   = $('#id_hospedaje').val();
            $.ajax({
                type: "POST",
                url: "/dashboard/hospedaje/categoriashospedaje",
                data: {id_hospedaje: hospedaje},
                success: function (data) {
                    $('#contenido-categoria').html(data);
                }
            });
        });
    });
</script>