<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Ingreso') ?></h3>
            </div>
            <?php if (!empty($this->message)) { ?>
                <div class="alert alert-danger">
                    <?php echo $this->message; ?>
                </div>
            <?php } ?>
            <div class="panel-body">
                <?php echo $this->form()->openTag($this->form); ?>
                <div class="form-group">
                    <label for="username">Usuario :</label>
                    <?php echo $this->formRow($this->form->get('username'));?>
                </div>
                <div class="form-group">
                    <label for="password">Password :</label>
                    <?php echo $this->formRow($this->form->get('password'));?>
                </div>
                <?php echo $this->formRow($this->form->get('submit'));?>
                <div><span><br>Estás tratando de acceder a un lugar del sitio web que es válido únicamente para usuarios autorizados.</span></div>
                <?php echo $this->form()->closeTag(); ?>
                
            </div>
        </div>
    </div>
</div>
