<table>
    <tr>
        <td>Hola <?php echo $nombre;?></td>
    </tr>
    <tr>
        <td><p>Recibimos una alerta indicando que quieres cambiar tu contraseña Buenisimo.</p>
            <p>Para hacerlo por favor haz click en el siguiente enlace:</p></td>
    </tr>
    <tr><td>
            <a href="http://buenisimo.ec/cliente/recuperarclave?token=<?php echo $token;?>">Cambiar Contraseña</a>
        </td>
    </tr>
    <tr>
        <td><p>Si no solicitaste cambiar tu contraseña, por favor haz caso omiso a este correo. Si tienes alguna consulta no dudes en escribirnos a clientes@beunisimo.ec o llamarnos al 311 - 5115.</p></td>
    </tr>
    <tr>
        <td><p>El equipo Buenisimo.</p></td>
    </tr>
</table>
