<?php echo $this->doctype(); ?>

<?php

use Zend\Session\Container;

$user_session = new Container('user');

/*

  $serviceLocator = $this->getApplication()->getServiceManager();
  $campanaTable = $serviceLocator->get('Dashboard\Model\CupcampanaTable');
  $datos = $campanaTable->getMenu();

  var_dump($datos); */
?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        //->appendHttpEquiv('Pragma', 'no-cache')
        //->appendHttpEquiv('Expires', '-1')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/admin/cupon.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/admin/nr-476.min.js')
                ->prependFile($this->basePath() . '/js/admin/graphics-dashboard.js')
                ->prependFile($this->basePath() . '/js/admin/ga.js')
                ->prependFile($this->basePath() . '/js/admin/cupon.js')
                ->prependFile($this->basePath() . '/js/admin/highcharts-more.js')
                ->prependFile($this->basePath() . '/js/admin/highcharts.src.js')
                ->prependFile($this->basePath() . '/js/admin/bootstrap-dropdown.js')
                ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
                ->prependFile($this->basePath() . '/js/admin/jquery-ui.min.js')
                 ->prependFile($this->basePath() . '/js/admin/jquery.min.js')
                ->prependFile($this->basePath() . '/js/admin/html5.js')
               
        ;
        ?>
    </head>
    <body>
        
        <header>
  <div class="inner">
	<div class="leftContent">
	  <ul>
		  <li class="navButton gLogo"><a href="./Mi Groupon · Admin_files/Mi Groupon · Admin.html"><img src="./Mi Groupon · Admin_files/logo.png" alt="Groupon"></a></li>
		  <li class="navButton active"><a href="./Mi Groupon · Admin_files/Mi Groupon · Admin.html">Inicio</a></li>
		  			<li class="navButton "><a href="http://www.migroupon.com/admin/campaigns">Campañas</a></li>
		      </ul>
  </div>
    <ul class="login-content">
    	<li>
    		<a class="bttooltip" data-validate="one-validate" data-placement="left" data-original-title="Buscador de Groupones" id="searchCouponsHeader"><i class="iconSearch"></i></a>
    	</li>
    
	    	      <li class=""><a class="bttooltip adminUsers" data-placement="left" data-original-title="Administrador de usuarios" href="http://www.migroupon.com/admin/users"><i class="iconUsers"></i></a></li>
	    				  <li><a class="bttooltip" target="_blank" data-placement="left" data-original-title="Ver preguntas frecuentes" href="http://clande-img.s3.amazonaws.com/WK/WK_local_PE.pdf"><i class="icon-faq"></i></a></li>
		    <li><a class="bttooltip btn btn-mini btn-warning validateBtn" id="searchCouponsBatchHeader" data-original-title="Validar Groupones" data-placement="left" data-toggle="modal" data-validate="multi-validate"><i class="iconbarcode"></i></a></li>
    		<li class="logout">
		  <span></span>
		  			<a href="http://www.migroupon.com/logout">Salir <i class="icon-signout"></i></a>
		  		</li>
					  </ul>
  </div>
</header>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
        
    </body>
</html>
