<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><b><?php echo $this->translate('Gracias por confiar en nosotros') ?></b></h3>
            </div>
            <div class="panel-body">
                <p>Esta confianza nos sirve para seguir superándonos en calidad, servicio e imagen; en resumen, en nuestro buen hacer.</p>
                <p>Les hacemos recordar que estaremos atentos a cualquier sugerencia para la mejora de nuestro servicio.</p>
            </div>
        </div>
    </div>
</div>
