<?php
//echo $this->controllerName();
switch ($this->controllerName()) {
    case 'Dashboard\Controller\User' :
        $titulo = "Administración de Usuarios";
        $enlace = "Nuevo Usuario";
        break;
    case 'Dashboard\Controller\Role' :
        $titulo = "Administración de Roles";
        $enlace = "Nuevo Rol";
        break;
    case 'Dashboard\Controller\Campana' :
        $titulo = "Administración de Campañas";
        $enlace = "Nueva Campaña";
        break;
    case 'Dashboard\Controller\Empresa' :
        $titulo = "Administración de Empresas";
        $enlace = "Nueva Empresa";
        break;
    default :
        $titulo = "";
        break;
}
?>
<div class="panel panel-warning">
    <div class="panel-heading">
        <div>
            <div class="btn-group tabla-grilla">
                <span class="titulo-tabla-grilla">
                    <?php echo $titulo; ?>
                </span>
                <button class="btn btn-danger boton-nuevo-grilla" id="btnAdd" name="btnAdd" value="add"><span class="glyphicon glyphicon-open-file" aria-hidden="true"></span> <?php echo $enlace; ?>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade bs-example-modal-lg" id="modalPreview" tabindex="-1" role="dialog" aria-labelledby="modalPreviewLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalPreviewLabel">Preview Campaña</h4>
            </div>
            <div class="modal-body" id="bodyPreview">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalContrato" tabindex="-1" role="dialog" aria-labelledby="modalContratoLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modalContratoLabel">Generación de Contrato</h4>
            </div>
            <div class="modal-body" id="bodyContrato">
                <div class="container-fluid">
                    <form name="frmregistro_contrato" id="frmregistro_contrato" role="form">
                        <div class="form-group">
                            <label for="nombre" class="col-lg-5 control-label afiliacion">Nombre Contacto:</label>
                            <div class="col-xs-7 validacion"> 
                                <input type="hidden" class="form-control" name="id_empresa" id="id_empresa" value="" >
                                <input type="text" class="form-control" name="nombre" id="nombre" value="" >
                                <span class="help-block with-errors"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email" class="col-lg-5 control-label afiliacion">Email Contacto:</label>
                            <div class="col-xs-7 validacion"> 
                                <input type="text" class="form-control" name="email" id="email" value="" >
                                <span class="help-block with-errors"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12 total">
                                <button type="button" class="btn btn-rebueno" name="generar_contrato" id="generar_contrato" onclick="javascript:generarcontrato();">Generar Contrato</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">

    function visualizar(campana){
        $.ajax({
            type: "POST",
            url: "/campana/preview",
            data: {id: campana},
            success: function (data) {
                $('#bodyPreview').html(data);
                $('#modalPreview').modal('show');
            }
        });
    }
    
    function registrarcontrato(empresa){
        $.ajax({
            type: "POST",
            url: "/dashboard/campana/contrato",
            data: {id: empresa},
            success: function (data) {
                var contrato = $.parseJSON(data);
                if (contrato) {
                    if (contrato.id_contrato == -1) {
                        $('#id_empresa').val(empresa);
                        $('#modalContrato').modal('show');
                    } else {
                        var form = $('<form method="post" action="/dashboard/campana/editarcontrato">' +
                                     '<input type="hidden" name="id_contrato" value="' + contrato.id_contrato + '">' +
                                     '</form>');
                        $(form).submit();
                    }
                }
            }
        });
    }
    
    function generarcontrato(){
        var id_campana = $("#id_campana").val();
        var nombre = $("#nombre").val();
        var email = $("#email").val();

        $.ajax({
            type: "POST",
            url: "/dashboard/campana/registrarcontrato",
            data: {id_campana:id_campana, nombre:nombre, email:email},
            success: function (data) {
                var contrato = $.parseJSON(data);
                if (contrato) {
                    if (contrato.id_contrato == -1) {
                        $('#modalContrato').modal('hide');
                    } else {
                        var form = $('<form method="post" action="/dashboard/campana/editarcontrato">' +
                                     '<input type="hidden" name="id_contrato" value="' + contrato.id_contrato + '">' +
                                     '</form>');
                        $(form).submit();
                    }
                }
            }
        });
    } 
    
</script>