<div class="contenedor-carrusel">
    <div  class="container">
        <div id="slider-principal" class="carousel slide carrusel-principal" data-ride="carousel">
            <!-- Indicators -->
            <!--ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                <li data-target="#carousel-example-generic" data-slide-to="4"></li>
                <li data-target="#carousel-example-generic" data-slide-to="5"></li>
            </ol-->
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <div class="slider" style="background-image: url('img/banner/bnr_bg_bsi_1_1.jpg');"></div>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <div class="slider" style="background-image: url('img/banner/bnr_bg_bsi_1_2.jpg');"></div>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <div class="slider" style="background-image: url('img/banner/bnr_bg_bsi_1_3.jpg');"></div>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <div class="slider" style="background-image: url('img/banner/bnr_bg_bsi_1_4.jpg');"></div>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <div class="slider" style="background-image: url('img/banner/bnr_bg_bsi_1_5.jpg');"></div>
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <div class="slider" style="background-image: url('img/banner/bnr_bg_bsi_1_6.jpg');"></div>
                    <div class="carousel-caption"></div>
                </div>
                <a class="left carousel-control" href="#slider-principal" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#slider-principal" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div id="slider-secundario" class="carousel slide carrusel-secundario" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item derecha active">
                    <div class="slider" style="background-image: url('img/banner_derecha/bnr_bg_bsi_1_0.jpg');"></div>
                </div>
                <div class="item derecha">
                    <div class="slider" style="background-image: url('img/banner_derecha/bnr_bg_bsi_1_1.jpg');"></div>
                </div>
                <div class="item derecha">
                    <div class="slider" style="background-image: url('img/banner_derecha/bnr_bg_bsi_1_2.jpg');"></div>
                </div>
                <div class="item derecha">
                    <div class="slider" style="background-image: url('img/banner_derecha/bnr_bg_bsi_1_3.jpg');"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
<?php
$anterior = '';

function crearUrl($str_cadena) {
    $nueva_cadena = trim($str_cadena);
    $nueva_cadena = str_replace('-', ' ', $nueva_cadena);
    $nueva_cadena = str_replace(' ', '-', $nueva_cadena);
    return $nueva_cadena;
}
$contador = 0;
$ultimo   = 'uno';
foreach ($data as $dato) {
    if ($dato['categoria'] != $anterior) {
        ?>
        <section id="<?php echo base64_encode($dato['categoria']); ?>">
            <div class="box_center"><h2><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://ofertop.pe/ofertas/lima/nuevo" title="Ver Todos" >Ver Todos »</a></h2></div>
            <div class="box_center"><div>
                    <?php
                }
                $contador++;
                if( $ultimo == 'uno' ) {
                    if($contador > 3) {
                        $contador = 1;
                        $ultimo = 'dos';
                    }
                } else {
                    if($contador > 2) {
                        $contador = 1;
                        $ultimo = 'uno';
                    }
                }
                    
                ?>
                <div class="campana-stilo-<?php echo $ultimo;?>" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                            <span class=""></span>
                            <img  class="lazy campana-imgreferencia-<?php echo $ultimo;?>" data-original="img/<?php echo $dato['id_campana']; ?>/small2/image1.jpg" src="img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <span class="campana-texto-descuento-<?php echo $ultimo;?>">-<?php echo $dato['descuento']; ?>%</span>
                        </a>
                    </div>
                    <div class="campana-texto-detalle-<?php echo $ultimo;?>">
                        <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </div>
                    <div class="campana-tarifario-<?php echo $ultimo;?>">
                        <s><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_regular']; ?></s>        <span class="campana-precio-oferta-<?php echo $ultimo;?>"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_especial']; ?></span>
                        <a class="btn btn-ver-oferta-<?php echo $ultimo;?>" href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" title="Ver oferta">Ver oferta »</a>
                    </div>
                    <p class="campana-vendidos-<?php echo $ultimo;?>">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
            </div> 
        </div>
    </section>
    <?php
}

$anterior = '';
foreach ($dataG as $dato) {
    if ($dato['categoria'] != $anterior) {
        $contador = 0;
        if( $ultimo == 'uno' ) {
            $ultimo = 'dos';
        } else {
            $ultimo = 'uno';
        }
        
        if ($anterior != '') {
            ?>
            </div> 
            </div>
            </section>
        <?php } ?>
        <section id="<?php echo base64_encode($dato['categoria']); ?>">
            <div class="box_center"><h2><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/campana/categoria/<?php echo base64_encode($dato['id_categoria']); ?>" title="Ver Todos" >Ver Todos »</a></h2></div>
            <div class="box_center"><div>
                    <?php
                }
                $contador++;
                if( $ultimo == 'uno' ) {
                    if($contador > 3) {
                        $contador = 1;
                        $ultimo = 'dos';
                    }
                } else {
                    if($contador > 2) {
                        $contador = 1;
                        $ultimo = 'uno';
                    }
                }
                ?>
                <div class="campana-stilo-<?php echo $ultimo;?>" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html">
                            <span class=""></span>
                            <img  class="lazy campana-imgreferencia-<?php echo $ultimo;?>" data-original="img/<?php echo $dato['id_campana']; ?>/small2/image1.jpg" src="img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <span class="campana-texto-descuento-<?php echo $ultimo;?>">-<?php echo $dato['descuento']; ?>%</span>
                        </a>
                    </div>
                    <div class="campana-texto-detalle-<?php echo $ultimo;?>">
                        <a href="/campana/detalle/<?php echo crearUrl($dato['subtitulo']).'--'.base64_encode($dato['id_campana']); ?>.html" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </div>
                    <div class="campana-tarifario-<?php echo $ultimo;?>">
                        <s><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_regular']; ?></s><span class="campana-precio-oferta-<?php echo $ultimo;?>"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_especial']; ?></span>
                        <a class="btn btn-ver-oferta-<?php echo $ultimo;?>" href="/campana/detalle/crearUrl($dato['subtitulo']).'--'.<?php echo base64_encode($dato['id_campana']); ?>.html" title="Ver oferta">Ver oferta »</a>
                    </div>
                    <p class="campana-vendidos-<?php echo $ultimo;?>">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
            </div> 
        </div>
    </section>
    <?php
}
?>
</div>            
<script type="text/javascript">
    $(function () {
        $("img.lazy").lazyload();
    });
</script>