<?php
$anterior = '';
foreach ($data as $dato) {
    if ($dato['categoria'] != $anterior) {
        ?>
        <section id="<?php echo base64_encode($dato['categoria']); ?>">
            <div class="box_center"><h2><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://ofertop.pe/ofertas/lima/nuevo" title="Ver Todos" >Ver Todos »</a></h2></div>
            <div class="box_center"><div>
                    <?php
                }
                ?>
                <div class="campaign one_third" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>">
                            <span class=""></span>
                            <img  class="lazy promocion" data-original="img/<?php echo $dato['id_campana']; ?>/small2/image1.jpg" src="img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <span class="special_text">-<?php echo $dato['descuento']; ?>%</span>
                        </a>
                    </div>
                    <h3>
                        <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </h3>
                    <div class="tar">
                        <s><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_regular']; ?></s>        <span class="price"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_especial']; ?></span>
                        <a class="btn btn_small" href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>" title="Ver oferta">Ver oferta »</a>
                    </div>
                    <p class="sold_campaigns">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
            </div> 
        </div>
    </section>
    <?php
}

$anterior = '';
foreach ($dataG as $dato) {
    if ($dato['categoria'] != $anterior) {
        if ($anterior != '') {
            ?>
            </div> 
            </div>
            </section>
        <?php } ?>
        <section id="<?php echo base64_encode($dato['categoria']); ?>">
            <div class="box_center"><h2><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/campana/categoria/<?php echo base64_encode($dato['id_categoria']); ?>" title="Ver Todos" >Ver Todos »</a></h2></div>
            <div class="box_center"><div>
                    <?php
                }
                ?>
                <div class="campaign one_third" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>">
                            <span class=""></span>
                            <img  class="lazy promocion" data-original="img/<?php echo $dato['id_campana']; ?>/small2/image1.jpg" src="img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <span class="special_text">-<?php echo $dato['descuento']; ?>%</span>
                        </a>
                    </div>
                    <h3>
                        <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </h3>
                    <div class="tar">
                        <s><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_regular']; ?></s>        <span class="price"><?php echo $moneda['simbolo'];?> <?php echo $dato['precio_especial']; ?></span>
                        <a class="btn btn_small" href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>" title="Ver oferta">Ver oferta »</a>
                    </div>
                    <p class="sold_campaigns">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
            </div> 
        </div>
    </section>
    <?php
}
?>
            
<script type="text/javascript">
    $(function () {
        $("img.lazy").lazyload();
    });
</script>