
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style="width:745px">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        <li data-target="#carousel-example-generic" data-slide-to="5"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="img/banner/bnr_bg_bsi_1_1.jpg" alt="...">
            <div class="carousel-caption"></div>
        </div>
        <div class="item">
            <img src="img/banner/bnr_bg_bsi_1_2.jpg" alt="...">
            <div class="carousel-caption"></div>
        </div>
        <div class="item">
            <img src="img/banner/bnr_bg_bsi_1_3.jpg" alt="...">
            <div class="carousel-caption"></div>
        </div>
        <div class="item">
            <img src="img/banner/bnr_bg_bsi_1_4.jpg" alt="...">
            <div class="carousel-caption"></div>
        </div>
        <div class="item">
            <img src="img/banner/bnr_bg_bsi_1_5.jpg" alt="...">
            <div class="carousel-caption"></div>
        </div>
        <div class="item">
            <img src="img/banner/bnr_bg_bsi_1_6.jpg" alt="...">
            <div class="carousel-caption"></div>
        </div>
    </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<?php
$anterior = '';
foreach ($data as $dato) {
    if ($dato['categoria'] != $anterior) {
        ?>
        <section id="<?php echo base64_encode($dato['categoria']); ?>">
            <div class="box_center"><h2><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://ofertop.pe/ofertas/lima/nuevo" title="Ver Todos" >Ver Todos »</a></h2></div>
            <div class="box_center"><div>
                    <?php
                }
                ?>
                <div class="campaign one_third" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>">
                            <span class=""></span>
                            <img  class="lazy promocion" data-original="img/<?php echo $dato['id_campana']; ?>/small2/image1.jpg" src="img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <span class="special_text">-<?php echo $dato['descuento']; ?>%</span>
                        </a>
                    </div>
                    <h3>
                        <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </h3>
                    <div class="tar">
                        <s>S/. <?php echo $dato['precio_regular']; ?></s>        <span class="price">S/. <?php echo $dato['precio_especial']; ?></span>
                        <a class="btn btn_small" href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>" title="Ver oferta">Ver oferta »</a>
                    </div>
                    <p class="sold_campaigns">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
            </div> 
        </div>
    </section>
    <?php
}

$anterior = '';
foreach ($dataG as $dato) {
    if ($dato['categoria'] != $anterior) {
        if ($anterior != '') {
            ?>
            </div> 
            </div>
            </section>
        <?php } ?>
        <section id="<?php echo base64_encode($dato['categoria']); ?>">
            <div class="box_center"><h2><?php echo $dato['categoria']; ?>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/campana/categoria/<?php echo base64_encode($dato['id_categoria']); ?>" title="Ver Todos" >Ver Todos »</a></h2></div>
            <div class="box_center"><div>
                    <?php
                }
                ?>
                <div class="campaign one_third" data-id="<?php echo $dato['id_campana']; ?>">
                    <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>">
                        <span class=""></span>
                    </a>
                    <div class="img_container">
                        <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>">
                            <span class=""></span>
                            <img  class="lazy promocion" data-original="img/<?php echo $dato['id_campana']; ?>/small2/image1.jpg" src="img/buenisimo_placeholder.png" alt="<?php echo $dato['subtitulo']; ?>" />
                            <span class="special_text">-<?php echo $dato['descuento']; ?>%</span>
                        </a>
                    </div>
                    <h3>
                        <a href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>" target="_self" title="<?php echo $dato['subtitulo']; ?>" class="description"><?php echo $dato['subtitulo']; ?></a>
                    </h3>
                    <div class="tar">
                        <s>S/. <?php echo $dato['precio_regular']; ?></s>        <span class="price">S/. <?php echo $dato['precio_especial']; ?></span>
                        <a class="btn btn_small" href="/campana/detalle/<?php echo base64_encode($dato['id_campana']); ?>" title="Ver oferta">Ver oferta »</a>
                    </div>
                    <p class="sold_campaigns">Vendidos: <?php echo $dato['vendidos']; ?> ofertas</p>
                </div>
                <?php
                $anterior = $dato['categoria'];
            }
            if ($anterior != '') {
                ?>
            </div> 
        </div>
    </section>
    <?php
}
?>
            
<script type="text/javascript">
    $(function () {
        $("img.lazy").lazyload();
    });
</script>