<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <title>Documento PDF</title>
        <style type="text/css">
            body {
                font-family: Helvetica;
            }
            
            .letra-cupon{
                font-size: 16px;
                font-weight: bold;
                text-align: right;
            }

            .letra-cupon-cabecera{
                font-size: 16px;
                font-weight: bold;
                text-align: right;
             }
            
            .letra-cupon-min {
                font-size: 13px;
                font-weight: bold;
                text-align: right;

            }

            .separacion-cupon{
                border-bottom-style:solid;
                border-bottom-width:2px;
                display: block;
                width: 100%;
                padding: 10px;
            }
            
            .separacion-cupon.cabecera{
                height:100px;
            }

            .separacion-empresa{
                display: block;
                width: 100%;
                padding: 10px;
            }

            .en-linea {
                display:inline-block;
            }

            .en-linea.logo-oferta-cabecera {
                width: 15%
            }
            
            .en-linea.texto-cabecera {
                width: 25%;
            }
            
            .en-linea.codigo-barra {
                width: 40%;
            }
            
            .en-linea.logo-oferta {
                width: 40%
            }
            
            .en-linea.logo-oferta img {
                width: 316px;
                height: 179px;
            }

            .en-linea.texto {
                width: 59%
            }

            .en-linea.empresa {
                width: 70%
            }

            .en-linea.mapa {
                width: 29%;
                vertical-align: top;
            }
            
            .logo-fijo {
                width: 100px; 
                height: 35px;
                background-image: url('<?php echo $localhost; ?>/img/logo_rebueno_cupon.png');
            }
            
            .centrado {
                text-align:center;
            }
            
            .justificado {
                text-align:justify;
            }
            
            .vineta-numerado {
                //list-style-position: inside;
                list-style-type:none;
                position:relative;
                top:-50px;
            }
            
        </style>
    </head>
    <body>
    <div>
        <div><p class='centrado'><b>ACUERDO DE ALIANZA ESTRATEGICA</b></p>
             <p class='justificado'>Conste por el presente documento, el <b>ACUERDO DE ALIANZA ESTRATEGICA</b>, que celebran de una parte <b>ECUADORPUNTOCOM C.L.</b>, con RUC N° 0992917202001, con domicilio en Los Sauces II Numero SOLAR 108 Manzana 111F, debidamente representada para estos efectos por la señora <b>CAROLINA GRANDA BARZOLA</b>, con Cédula Nº 0920626959, a quien en adelante se le denominará <b>LA EMPRESA</b>; y de la otra parte <b><?php echo $razon;?></b>, con RUC N° <?php echo $ruc; ?>, con domicilio en <?php echo $direccion; ?>, debidamente representado para estos efectos por el señor (a) __________________________________, identificado con C. Nº _________________; a quien en adelante se le denominará el <b>ALIADO ESTRATÉGICO</b>; en los términos y condiciones siguientes:</p>
             <p><br></p>
             <p><b>PRIMERA: ANTECEDENTES</b></p>
             <p class='justificado'>1.1.
                    <ul class='vineta-numerado'>
                     <li><p class='justificado'>LA EMPRESA, es una sociedad ecuatoriana, dedicada a la prestación de servicios que ofrece ciertas ventajas y descuentos para usuarios de su marca REBUENO, respecto de los productos y servicios (los "Beneficios") ofrecidos por una amplia gama de comercios participantes y proveedores.</p></li>
                    </ul></p>
             <p class='justificado'>1.2.
                    <ul class='vineta-numerado'>
                     <li><p class='justificado'>El ALIADO ESTRATÉGICO: es una sociedad ecuatoriana, dedicada a la __________________________ ___________________________________ , está interesado en participar en las oportunidades de promoción que ofrece REBUENO para aumentar su notoriedad e incrementar su volumen de ventas, motivo por el cual emitirá cupones para el consumo de sus productos y/o servicios, con descuentos en el precio, a favor de clientes finales.</p></li>
                    </ul></p>
             <p class='justificado'>1.3.
                    <ul class='vineta-numerado'>
                     <li><p class='justificado'>El ALIADO ESTRATÉGICO emite documentos denominados “cupones”, concediendo un “derecho de opción” para que los adquirentes de tales cupones (“Optantes”), celebren contratos definitivos con el ALIADO ESTRATÉGICO para la venta de bienes y/o la prestación de servicios por parte del ALIADO ESTRATÉGICO a su favor, respecto de las prestaciones descritas en cada cupón. Cada cupón indica su correspondiente período de vigencia y eficacia.</p></li>
                    </ul></p>
SEGUNDA: OBJETO 
El objeto de la presente alianza es ofrecer descuentos y/o promociones de los productos y/o servicios del ALIADO ESTRATÉGICO, a favor de los usuarios de la marca de REBUENO, que pertenece a LA EMPRESA.

Cada una de las partes reconoce que el éxito de la alianza requerirá de una relación cooperativa basada en la buena comunicación. 

2.1 LA EMPRESA divulgará, a través de las páginas web que gestiona, los “cupones” indicados en la cláusula 1.3., con la finalidad de colocarlos en poder de los usuarios de la marca REBUENO, los cuales adquirirán la condición de “optantes”. De tal forma, LA EMPRESA proporciona al ALIADO ESTRATÉGICO con clientes en el marco de este acuerdo de Cooperación.
2.2 A estos fines, LA EMPRESA  podrá, a su discreción, ofertar los “cupones” emitidos por el ALIADO ESTRATÉGICO entre las ofertas publicitarias de la ciudad correspondiente, accesibles mediante el portal web www.rebueno.ec entre las diversas ofertas online (sea cual fuese su denominación) publicadas simultáneamente, de conformidad con lo establecido en la cláusula 4.1. La publicidad de los Cupones se hará durante, al menos, un día (mínimo 24 horas), no habiendo un plazo máximo para su publicidad. Para lo cual, las partes acuerdan que  LA EMPRESA  sea quien determine el plazo máximo en el cual se efectuará la publicidad de los Cupones.
2.3 Para tal efecto, el ALIADO ESTRATÉGICO deberá solicitar a LA EMPRESA, la realización de las actividades de difusión y promoción de los cupones indicados, de manera escrita. En atención a los trabajos preparatorios de la ejecución de la Campaña y la coordinación de las ofertas de otros aliados estratégicos, la petición de promoción por parte del ALIADO ESTRATÉGICO deberá remitirse con un plazo de antelación de al menos diez (10) días útiles a la fecha más cercana prevista por parte del ALIADO ESTRATÉGICO para la promoción. En dicha comunicación, el ALIADO ESTRATÉGICO deberá proporcionar todo el material gráfico y comercial requerido por LA EMPRESA para la publicación del aviso de los “cupones”.
2.4 El ALIADO ESTRATÉGICO autorizara a LA EMPRESA a otorgar los “cupones” a favor de los “optantes”, para que éstos celebren contratos definitivos con el ALIADO ESTRATÉGICO según los alcances indicados en cada cupón.
2.5 LA EMPRESA se encargará de cobrar, por cuenta del ALIADO ESTRATÉGICO, la contraprestación que pagarán los optantes por la celebración de los contratos definitivos a los cuales otorga derecho la opción.
2.6 LA EMPRESA deberá entregar el importe recaudado al ALIADO ESTRATÉGICO, previa deducción del importe de su contraprestación.

TERCERA: VIGENCIA
La alianza estratégica entrará en vigencia de acuerdo a lo indicado en el anexo 1. La alianza estratégica podrá ser renovada por mutuo acuerdo, la misma obligatoriamente debe constar por escrito, mediante una adenda suscrita por las partes contratantes, para que surja efecto.

CUARTA: OBLIGACIONES RECÍPROCAS
Las partes pacta las siguientes obligaciones reciprocas: 
4.1 Del ALIADO ESTRATÉGICO:
Permitirá a cualquier usuario de REBUENO disfrutar de los servicios y/o productos siempre y cuando el usuario presente el código exclusivo otorgado por LA EMPRESA. 
Dar un uso correcto, a las marcas y/o nombres, frase o slogans comerciales registrados como derechos de autor y de propiedad intelectual de LA EMPRESA, que sólo cede en uso estrictamente para el desarrollo y vigencia del presente acuerdo.
Autorizar a LA EMPRESA de hacer uso del logo del ALIADO ESTRATÉGICO en todo su material de marketing.
 Deberá emitir y entregar al Optante, en su calidad de cliente final, la respectiva factura por el total del producto o servicio contratado.
 Las prestaciones que se obliga a ejecutar a favor de los Optantes (adquirentes de los cupones) están descritas en el anverso de este Acuerdo de Cooperación.
Mientras no se sobrepase el stock máximo acordado con el ALIADO ESTRATÉGICO, REBUENO podrá seguir vendiendo cupones hasta treinta (30) días calendarios antes de la expiración de los mismos. Si el ALIADO ESTRATÉGICO no quisiera que sus cupones se vendan después de la publicación de la campaña, deberá así representarlo por escrito a LA EMPRESA antes de aceptar el presente contrato. Los cupones que LA EMPRESA venda en ejercicio de esta cláusula no excederán el equivalente a un 20% de la cantidad de cupones vendidos durante la campaña, en los casos de publicaciones en que no se hubiese definido una capacidad de cupones. En los casos en que si hubiese una capacidad definida, LA EMPRESA podrá seguir vendiendo los cupones hasta agotar el stock.
Garantiza a LA EMPRESA y a los Optantes que las Opciones adquiridas por estos últimos, mediante la adquisición de los cupones, podrán ser ejercidas en cualquier momento, previa reserva y/o cita con el ALIADO ESTRATÉGICO, dentro del período de vigencia de dichos cupones.
Asumirá la responsabilidad exclusiva de la ejecución exacta y oportuna de las prestaciones ofrecidas a los Optantes, quienes por la sola adquisición de los cupones gozarán del derecho de ejercer la Opción frente al ALIADO ESTRATÉGICO, para procurarse los bienes o servicios descritos en los cupones.
Libera a LA EMPRESA de todo reclamo de cualquier naturaleza (civil, penal, administrativa, en materia de protección al consumidor), presentado por los adquirentes de los cupones, referido a la ejecución o cumplimiento parcial, tardío o defectuoso de las prestaciones allí descritas, en tanto obligado y responsable exclusivo de éstas.
De igual forma, se obliga a mantener indemne a LA EMPRESA de toda pérdida económica (daño emergente, lucro cesante, pérdida de costo de oportunidad) o daño moral que sea consecuencia de imputaciones de responsabilidad de cualquier naturaleza (civil, penal, administrativa) por parte de los adquirentes de los cupones, de terceros o de entidades o autoridades públicas.
Todo desembolso que tuviera que efectuar LA EMPRESA por la infracción de las obligaciones asumidas en este numeral deberá ser reembolsada íntegramente por el ALIADO ESTRATÉGICO.
Deberá brindar a su exclusiva cuenta y costo toda la infraestructura y personal necesario para responder a las dudas y reclamos de los adquirentes de los cupones, mediante su propio servicio de atención al cliente y con arreglo a las normas del Código de Protección al consumidor aprobado mediante Ley 2000-21 (R.O. S 116: IO-jul-2000) 
Ello en tanto que el ALIADO ESTRATÉGICO califica como “proveedor” de las prestaciones ofrecidas a los Optantes (servicios y/o productos) según lo definido y previsto en el Código de Consumo, asistiéndole exclusivamente frente al Adquirente de los cupones (cliente-consumidor) los Deberes de Idoneidad, Información, Seguridad y demás obligaciones previstas en el referido Código.
En esa línea, si el adquirente del cupón tuviera alguna queja, reclamo por la idoneidad/seguridad del producto o servicio ofrecido por el ALIADO ESTRATÉGICO, ésta deberá ser dirigida exclusivamente a éste, pues en su condición de Proveedor del producto o servicio materia de venta a través de los cupones le asiste dichas obligaciones según lo previsto en el Código Consumo. Con lo cual, el ALIADO ESTRATÉGICO deberá cumplir con atender el reclamo del Adquirente del cupón según los plazos previstos en el Código de Consumo. Asimismo, si es que el Adquirente del cupón de manera errónea dirigiese su reclamo a LA EMPRESA, Rebueno  le informará que el mismo deberá ser dirigido al ALIADO ESTRATÉGICO a fin que pueda recibir la debida atención, debiendo el ALIADO ESTRATÉGICO dar la atención debida del reclamo según lo previsto en el Código de Consumo.
Reconoce que LA EMPRESA únicamente publicita y ofrece los cupones de descuento más no es responsable/garante por los servicios y/o mercancías vendidas, que son de exclusiva responsabilidad del ALIADO ESTRATÉGICO.

4.2 De  LA EMPRESA:

Autorizar al ALIADO ESTRATÉGICO, el uso de marcas, nombres o lemas comerciales registrados de derecho de autor y propiedad intelectual de LA EMPRESA para el desarrollo de las acciones señaladas en el presente acuerdo.

QUINTA: CONTRAPRESTACIÓN
5.1 LA EMPRESA recibirá una retribución por la organización del sistema de promoción y difusión para la colación de los “cupones”, la cual será determinada según lo dispuesto en la cláusula 5.2.
5.2 La retribución de LA EMPRESA asciende al porcentaje indicado en el anexo 1 del presente contrato. Dicho porcentaje incluye el IVA .
5.3 El derecho de LA EMPRESA a percibir la retribución se genera con ocasión del canje y la validación de los cupones.
5.4 Se entiende que un cupón ha sido “canjeado”, cuando el optante ejerció el derecho de opción contenido en el cupón, accediendo a los bienes y/o servicios descritos en el “cupón”.
5.5 Se entiende que un cupón ha sido “validado” cuando el ALIADO ESTRATÉGICO verifica la conformidad del cupón, a través del sistema de validación de cupones provisto por LA EMPRESA.
5.6 Los importes recaudados por LA EMPRESA, según lo dispuesto en la cláusula 2.5, a nombre y cuenta del ALIADO ESTRATÉGICO serán entregados por LA EMPRESA al ALIADO ESTRATÉGICO hasta los quince (15) días después de cierre semanal. Este proceso se realiza cada 7 días
5.7 LA EMPRESA generara el cobro de su retribución al ALIADO ESTRATÉGICO con cargo a los importes recaudados por LA EMPRESA, según lo indicado en la cláusula 5.6.
5.8 Los importes recaudados por LA EMPRESA por cupones no canjeados ni validos no serán devueltos al ALIADO ESTRATÉGICO. En tales casos, LA EMPRESA emitirá el comprobante de pago directamente al optante por los importes pagados por este.

SEXTA: INEXISTENCIA DE RELACIÓN LABORAL 
Queda expresamente establecido que el presente contrato es uno de naturaleza civil y por lo tanto, ni LA EMPRESA ni su personal mantienen relación laboral alguna con el ALIADO ESTRÁTEGICO y viceversa.

SEPTIMA: RESOLUCION 
La presente alianza quedará resuelto por las siguientes causas:
7.1. Por incumplimiento de las obligaciones estipuladas en la cláusula cuarta, de acuerdo a lo establecido por el Código Civil Ecuatoriano.Si la prestación no se cumple dentro del plazo señalado, el contrato se resuelve de pleno derecho, quedando a cargo del deudor la indemnización de daños y perjuicios, de conformidad con Código Civil Ecuatoriano
7.2. Si el ALIADO ESTRATEGICO incurre en falsedad en los documentos y/o información presentada a LA EMPRESA para la realización de la alianza.
Para esto, se deberá cursar carta notarial a la otra parte señalando que hará valer esta cláusula, con una anticipación de 30 días calendario. 
7.3. La resolución de la presente alianza no afectará la validez de los cupones que ya hubieren sido emitidos ni la retribución pactada en ellos.

OCTAVA: CONFIDENCIALIDAD 
Las partes convienen en que toda información que se genere y/o cruce entre ellas, respecto de las actividades de publicidad conjunta a desarrollarse para promoverse recíprocamente, será considerada como estrictamente confidencial, por lo que se obligan a no revelarla a terceras personas.

NOVENA: PROTECCIÓN DE DATOS PERSONALES 
9.1. El ALIADO ESTRATÉGICO declara expresamente conocer que en caso, en el marco de la relación contractual que origina esta alianza, tuviera acceso a datos: (i) de LA EMPRESA; (ii) del personal de LA EMPRESA; y/o, (iii) de los clientes de LA EMPRESA, se obliga a protegerlos aplicando las exigencias y requerimientos previstos en este Contrato.
9.2. En el supuesto del párrafo anterior, el ALIADO ESTRATÉGICO se obliga a adoptar las medidas de seguridad de protección de datos de los clientes, de acuerdo a la normatividad Ecuatoriana vigente, sin perjuicio de ello a LA EMPRESA. Así mismo el ALIADO ESTRATÉGICO se obliga a:
Implementar las condiciones de seguridad. 
No almacenar, transferir, procesar, tratar o usar los datos de LA EMPRESA, sus trabajadores o clientes de modo distinto del expresamente permitido por LA EMPRESA o del modo que resulte necesario para ejecutar este Contrato.
Cooperar con LA EMPRESA para satisfacer los requerimientos de la Autoridad Nacional de Protección de Datos Personales. 
En cualquier caso o supuesto de término o resolución de este Contrato, devolver a LA EMPRESA toda la información y datos que éste le haya proporcionado en un plazo máximo de diez (10) días hábiles, así como cualquier copia de la misma que pueda estar en su poder o de su personal, sus asesores o subcontratistas, o preparada por el ALIADO ESTRATÉGICO o su personal, sus asesores o subcontratistas en base a la información.

DÉCIMA: EXCLUSIVIDAD
10.1 El ALIADO ESTRATÉGICO gozará de exclusividad para las prestaciones descritas en la Cláusula 1. Por su parte, LA EMPRESA se abstendrá de incluir entre las ofertas publicitarias accesibles a través de su portal web alguna oferta similar para la misma ciudad y sector en el día o días en los que se oferte la campaña del ALIADO ESTRATÉGICO.
10.2 LA EMPRESA gozará de exclusividad frente al ALIADO ESTRATÉGICO en la medida en que, durante la vigencia de la presente alianza estratégica, este último se obliga a no colaborar con otros proveedores distintos de LA EMPRESA–de forma directa o indirecta– para la promoción online de la prestación de sus servicios, basada en cupones (como “bonos” “vales” o cualquier otro título habilitante similar) o la distribución offline de cupones (como “bonos”, “vales” u otros títulos habilitantes similares) a revendedores comerciales con el propósito de la distribución online.
10.3 Adicionalmente, el ALIADO ESTRATÉGICO se compromete a no otorgar ningún descuento de similares características al ofrecido mediante la plataforma de LA EMPRESA mientras éste se encuentre publicado en el sitio, y hasta el término de la vigencia del cupón. Esta obligación comprende el compromiso de no ofrecer a ningún cliente final mejores o iguales condiciones que las ofrecidas a través de LA EMPRESA durante el referido periodo de tiempo, por ningún canal, incluyendo los propios. El ALIADO ESTRATÉGICO queda autorizado para adoptar cualquier otra medida para la promoción de su negocio y/o de sus servicios.
10.4 El ALIADO ESTRATÉGICO se obliga no ofrecer ningún descuento de características similares en otros canales incluyendo los propios canales del ALIADO ESTRATÉGICO.
DÉCIMA PRIMERA: PROPIEDAD INTELECTUAL Y USO DE MARCA
11.1 Se deja expresa constancia que la propiedad intelectual, comercial e industrial de los sistemas, incluidos hardware y software, sobre los que versa este Alianza son de exclusiva titularidad y propiedad de LA EMPRESA. El Alianza no otorga al ALIADO ESTRATÉGICO licencia alguna, excepto el derecho de uso de los programas para el normal desarrollo de los servicios contratados.
11.2 Ninguna marca comercial, nombre, logo o producto asociado con LA EMPRESA, sus proveedores o terceras partes podrá ser usado sin la autorización previa por escrito de LA EMPRESA.
11.3 El ALIADO ESTRATÉGICO otorga a LA EMPRESA una licencia para utilizar sus marcas o derechos de propiedad industrial o comercial, atendiendo a que ello es necesario para la promoción de sus cupones durante la vigencia de la Alianza Estratégica.
DÉCIMA SEGUNDA: CONDICIONES GENERALES DE CONTRATACIÓN (CGC) DIVERGENTES
12.1 El ALIADO ESTRATÉGICO reconoce que toda la información otorgada por LA EMPRESA, es exclusivamente para permitir que el ALIADO ESTRATÉGICO pueda proveer los bienes o servicios a que se refieren de los Cupones a los Compradores de Cupones. Tanto el ALIADO ESTRATÉGICO como LA EMPRESA deberán cumplir con todas y cada una de las disposiciones aplicables en la Ley de Protección de Datos Personales.
12.2 Toda la información respecto a los Compradores de Cupones, incluyendo de manera enunciativa, más no limitativa dirección de correo electrónico, nombres, fechas de nacimiento y dirección proporcionada para la entrega del producto, será propiedad de LA EMPRESA y únicamente podrá ser utilizada por el ALIADO ESTRATÉGICO para proveer los bienes o servicios a que se refieren de los Cupones respecto de los cuales se proporciona dicha información.

DÉCIMA TERCERA: DERECHO APLICABLE Y JURISDICCIÓN Este Acuerdo está sujeto a las Leyes de la República del Ecuador. Todo litigio, controversia, desavenencia o reclamo resultante, relacionada o derivada del presente acuerdo o que guarde relación con él, incluidas las relativas a su validez, eficacia o terminación, serán resueltas ante los jueces de la ciudad de Guayaquil, renunciando a cualquier otra jurisdicción.

Las partes suscriben el presente documento en señal de conformidad con lo expresado en el presente acuerdo de alianza estratégica, en la ciudad de Guayaquil a los ______ días del mes de __________.del año 2015.





      
ECUADORPUNTOCOM C.L.                                     	              ALIADO ESTRATÉGICO
    </div>
    
</div>
    </body>
</html>
