<form class="form-horizontal" role="form" >
    <?php foreach($contrato as $contra) {?>
    <div class="panel panel-warning">
        <div class="panel-heading">
            <div>Anexo Contrato Nro. <?php echo $contra['nombre_documento'];?><div style="float:right;margin: 0px;padding: 0px; position: relative; top:-5px "><?php if($contra['id_estado'] != '2') { ?><a class="btn btn-danger btn-sm" id="refresca_documento"><span class="glyphicon glyphicon-refresh"></span> Actualizar Anexo Contrato</a>&nbsp;&nbsp;&nbsp;<?php } ?><a class="btn btn-primary btn-sm" id="descarga_documento"><span class="glyphicon glyphicon-download"></span> Descargar</a></div></div>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label for="nombre_contacto" class="col-lg-2 control-label">Nombre Contacto :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="nombre_contacto" id="nombre_contacto" value="<?php echo $contra['nombre_contacto'];?>" <?php if($contra['id_estado'] == '2') { ?>readonly<?php } ?>>
                </div>
            </div>
            <div class="form-group">
                <label for="email_contacto" class="col-lg-2 control-label">Email Contacto :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="email_contacto" id="email_contacto" value="<?php echo $contra['email_contacto'];?>" <?php if($contra['id_estado'] == '2') { ?>readonly<?php } ?>>
                </div>
            </div>
            <div class="form-group">
                <label for="fecha_registro" class="col-lg-2 control-label">Fecha Registro :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="fecha_registro" id="fecha_registro" value="<?php echo $contra['fecha_registro'];?>" <?php if($contra['id_estado'] == '2') { ?>readonly<?php } ?>>
                </div>
            </div>
            <?php if($contra['id_estado'] != '2') { ?>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-7">
                    <a class="btn btn-success btn-sm" id="enviar_contrato"><span class="glyphicon glyphicon-envelope"></span> Enviar Anexo Contrato para Firma</a>
                </div>
            </div>
            <?php } else { ?>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-7">
                    Contrato firmado por : <b><?php echo strtoupper($contra['firma_documento']);?></b> el <b><?php echo $contra['fecha_firma'];?></b>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-10 control-label">Arte de la Campaña</label>
            </div>
            <div class="form-group">
                <label for="nombre_contacto_arte" class="col-lg-2 control-label">Nombre Contacto :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="nombre_contacto_arte" id="nombre_contacto_arte" value="<?php echo $contra['nombre_contacto_arte'];?>" <?php if($contra['id_estado_arte'] == '3') { ?>readonly<?php } ?>>
                </div>
            </div>
            <div class="form-group">
                <label for="email_contacto_arte" class="col-lg-2 control-label">Email Contacto :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="email_contacto_arte" id="email_contacto_arte" value="<?php echo $contra['email_contacto_arte'];?>" <?php if($contra['id_estado_arte'] == '3') { ?>readonly<?php } ?>>
                </div>
            </div>
                <?php if($contra['id_estado_arte'] != '3') { ?>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-7">
                        <a class="btn btn-success btn-sm" id="enviar_arte"><span class="glyphicon glyphicon-envelope"></span> Enviar Arte para Aprobación</a>
                    </div>
                </div>
                <?php } else { ?>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-7">
                        Arte aprobado el <b><?php echo $contra['fecha_aceptacion_arte'];?></b>
                    </div>
                </div>
                <?php } ?>
            
            <?php } ?>
        </div>
    </div>
    <?php } ?>
</form>
<script>
    
    $('#descarga_documento').click(function() {
        var params = 'nombre_documento=<?php echo $contra['nombre_documento'];?>';

        window.open('/dashboard/empresa/obtener-pdf-contrato?' + params, '_blank');
    });
    
    $('#refresca_documento').click(function() {
        var params = 'id_contrato=<?php echo $contra['id_contrato'];?>&id_campana=<?php echo $contra['id_campana'];?>' ;
        
        window.open('/dashboard/empresa/actualiza-anexocontrato?' + params, '_blank');
    });
    
    $('#enviar_contrato').click(function() {
        var email_contacto;
        var nombre_contacto;
        var id_contrato = '<?php echo $contra['id_contrato'];?>';
        var id_campana = '<?php echo $contra['id_campana'];?>';
        
        email_contacto  = $('#email_contacto').val();
        nombre_contacto = $('#nombre_contacto').val();
        
        $.ajax({
            type: "POST",
            url: "/dashboard/empresa/enviar-anexocontrato",
            data: {email_contacto: email_contacto, nombre_contacto: nombre_contacto, id_contrato: id_contrato, id_campana: id_campana},
            success: function (data) {
                alert('Se envio el contrato correctamente.');
            }
        });
    });
    
    
    $('#enviar_arte').click(function() {
        var email_contacto_arte;
        var nombre_contacto_arte;
        var id_contrato = '<?php echo $contra['id_contrato'];?>';
        var id_campana = '<?php echo $contra['id_campana'];?>';
        
        email_contacto_arte  = $('#email_contacto_arte').val();
        nombre_contacto_arte = $('#nombre_contacto_arte').val();
        
        $.ajax({
            type: "POST",
            url: "/dashboard/empresa/enviar-arte",
            data: {email_contacto: email_contacto_arte, nombre_contacto: nombre_contacto_arte, id_contrato: id_contrato, id_campana: id_campana},
            success: function (data) {
                alert('Se envio el arte correctamente.');
            }
        });
    });
                                    
</script>
    