<?php echo $this->form()->openTag($this->form); ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Registrar Empresa</h4>
    </div>
    <div class="panel-body">
        <div class="form-group">
            <label for="razon_social" class="col-lg-3 control-label">Razón Social :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('razon_social')); ?>
                <?php echo $this->formRow($this->form->get('id_empresa')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="subtitulo" class="col-lg-3 control-label">Nombre Comercial :</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('nombre_comercial')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="registro_contribuyente" class="col-lg-3 control-label">Registro Contribuyente:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('registro_contribuyente')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="direccion_facturacion" class="col-lg-3 control-label">Dirección Facturación:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('direccion_facturacion')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="direccion_comercial" class="col-lg-3 control-label">Dirección Comercial:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('direccion_comercial')); ?>
            </div>
        </div>

        <div class="form-group">
            <label for="telefono" class="col-lg-3 control-label">Teléfonos:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('telefono')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="horario" class="col-lg-3 control-label">Horario Atención:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('horario')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="web_site" class="col-lg-3 control-label">Site:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('web_site')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="ubicacion_gps" class="col-lg-3 control-label">Ubicación GPS:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('ubicacion_gps')); ?>
                <span class="label"><a href="http://gmaps-samples.googlecode.com/svn/trunk/simplewizard/makestaticmap.html" target="_blank">Crear Mapa de Ubicación</a> Tamaño sugerido 200 x 200 pixeles</span>
            </div>
        </div>
        <div class="form-group">
            <label for="numero_cuenta" class="col-lg-3 control-label">Numero de cuenta:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('numero_cuenta')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="descripcion" class="col-lg-3 control-label">Descripción:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('descripcion')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="rubro" class="col-lg-3 control-label">Dedicada a:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('rubro')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="tipo_documento_representante" class="col-lg-3 control-label">Tipo Doc. Representante:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('tipo_documento_representante')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="documento_representante" class="col-lg-3 control-label">N° Doc. Representante:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('documento_representante')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="nombre_representante" class="col-lg-3 control-label">Nombre Representante:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('nombre_representante')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="persona_contacto" class="col-lg-3 control-label">Persona Contacto:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('persona_contacto')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="email_contacto" class="col-lg-3 control-label">Email Persona Contacto:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('email_contacto')); ?>
            </div>
        </div>
        
        <div class="form-group">
            <label for="titular_cuenta" class="col-lg-3 control-label">Titular de la Cuenta:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('titular_cuenta')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="ruc_titular" class="col-lg-3 control-label">RUC del Titular:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('ruc_titular')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="numero_cuenta" class="col-lg-3 control-label">Número de Cuenta:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('numero_cuenta')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="tipo_cuenta" class="col-lg-3 control-label">Tipo de Cuenta:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('tipo_cuenta')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="email_facturacion" class="col-lg-3 control-label">Email facturación:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('email_facturacion')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="banco_cuenta" class="col-lg-3 control-label">Banco de la Cuenta:</label>
            <div class="col-lg-7">
                <?php echo $this->formRow($this->form->get('banco_cuenta')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-3 col-lg-7">
                <?php echo $this->formRow($this->form->get('submit')); ?>&nbsp;&nbsp;&nbsp;&nbsp;
                <?php echo $this->formRow($this->form->get('btn-regresar')); ?>
            </div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
<script type="text/javascript">
    $(document).ready(function () {

        // Delete button popover confirmation
        $('#empresaForm').formValidation({
            message: 'El valor no es válido.',
            err: {
                container: 'tooltip'
            },
            icon: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh',
            },
            fields: {
                razon_social: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre la Razon Social.'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9ñáéíóúÑÁÉÍÓÚ& ,.-]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 150,
                            message: 'Este campo debe contener 150 caracteres como máximo.'
                        }
                    }
                },
                registro_contribuyente: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre el Registro del Contribuyente.'
                        },
                        regexp: {
                            regexp: /^[0-9]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 25,
                            message: 'Este campo debe contener 25 caracteres como máximo.'
                        }
                    }
                },
                direccion_facturacion: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre la Dirección de Facturación.'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9ñáéíóúÑÁÉÍÓÚ& ,.-]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 150,
                            message: 'Este campo debe contener 150 caracteres como máximo.'
                        }
                    }
                },
                telefono: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre uno o más teléfonos de Referencia.'
                        },
                        regexp: {
                            regexp: /^[0-9 -]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 100,
                            message: 'Este campo debe contener 100 caracteres como máximo.'
                        }
                    }
                },
                horario: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre el horario de atención.'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9ñáéíóúÑÁÉÍÓÚ& ,.:-]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 150,
                            message: 'Este campo debe contener 150 caracteres como máximo.'
                        }
                    }
                },
                numero_cuenta: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre el número de Cuenta Bancaria.'
                        },
                        regexp: {
                            regexp: /^[0-9 -]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 100,
                            message: 'Este campo debe contener 100 caracteres como máximo.'
                        }
                    }
                },
                descripcion: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre la Reseña de la Empresa.'
                        },
                        stringLength: {
                            min: 1,
                            max: 1000,
                            message: 'Este campo debe contener 1000 caracteres como máximo.'
                        }
                    }
                },
                tipo_documento_representante: {
                    err: 'popover',
                    //icon: false,
                    validators: {
                        notEmpty: {
                            message: 'Por favor seleciione el Tipo de Documento de Identidad del Representante Legal.'
                        }
                    }
                },
                documento_representante: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre el Número de Documento de Identidad del Representante Legal.'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 20,
                            message: 'Este campo debe contener 20 caracteres como máximo.'
                        }
                    }
                },
                nombre_representante: {
                    err: 'popover',
                    validators: {
                        notEmpty: {
                            message: 'Por favor registre el Nombre Completo del Representante Legal.'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9ñáéíóúÑÁÉÍÓÚ& ,.-]+$/
                        },
                        stringLength: {
                            min: 1,
                            max: 200,
                            message: 'Este campo debe contener 200 caracteres como máximo.'
                        }
                    }
                },
            }
        }).on('success.form.fv', function (e) {
            //$('.fv-hidden-submit').submit();
            //e.preventDefault();
            $("#modalConfirmacion").modal('show');
            //var $form = $(e.target);
            //$.post($form.attr('action'), $form.serialize(), function (data){});
        });

        $("#modal-confirmacion-si").click(
            function (e) {
                $('button').removeClass('fv-hidden-submit disabled').addClass('fv-hidden-submit');
                $('.fv-hidden-submit').removeAttr('disabled');
                $("#modalConfirmacion").modal('hide');
                $('.fv-hidden-submit').click();
            }
        );

        $("#modal-confirmacion-no").click(
            function (e) {
                $('#submit').removeClass('btn btn-primary disabled').addClass('btn btn-primary');
                $('#submit').removeAttr('disabled');
                $("#modalConfirmacion").modal('hide');
            }
        );

        $("#btn-regresar").click(
            function (e) {
                $("#modalCancelacion").modal('show');
            }
        );

        $("#modal-cancelacion-si").click(
            function (e) {
                $(location).attr('href','/dashboard/empresa/list');
            }
        );

        $("#modal-cancelacion-no").click(
            function (e) {
                $("#modalCancelacion").modal('hide');
            }
        );
    });
</script>