<div class="container-fluid">
    <form name="frmregistro_contrato" id="frmregistro_contrato" role="form">
        <div class="form-group">
            <label for="nombre" class="col-lg-5 control-label afiliacion">Nombre Contacto:</label>
            <div class="col-xs-7 validacion"> 
                <input type="hidden" class="form-control" name="id_campana" id="id_campana" value="<?php echo $id_campana;?>" >
                <input type="text" class="form-control" name="nombre" id="nombre" value="" >
                <span class="help-block with-errors"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-lg-5 control-label afiliacion">Email Contacto:</label>
            <div class="col-xs-7 validacion"> 
                <input type="text" class="form-control" name="email" id="email" value="" >
                <span class="help-block with-errors"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12 total">
                <button type="button" class="btn btn-rebueno" name="generar_contrato" id="generar_contrato" onclick="javascript:generarcontrato();">Generar Contrato</button>
            </div>
        </div>
    </form>
</div>
