<div class="container-fluid">
    <form name="frmregistro" role="form" action="/dashboard/campana/registrarcontrato" method="POST" data-parsley-validate>
        <div class="form-group">
            <label for="nombre" class="col-lg-5 control-label afiliacion">Nombre Contacto:</label>
            <div class="col-xs-7 validacion"> 
                <input type="hidden" class="form-control" name="id_campana" id="id_campana" value="<?php echo $id;?>" >
                <input type="text" class="form-control" name="nombre" id="nombre" value="" >
                <span class="help-block with-errors"></span>
            </div>
        </div>
        <div class="form-group">
            <label for="email" class="col-lg-5 control-label afiliacion">Email Contacto:</label>
            <div class="col-xs-7 validacion"> 
                <input type="text" class="form-control" name="email" id="email" value="" >
                <span class="help-block with-errors"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12 total">
                <button type="submit" class="btn btn-rebueno"  id="generar" >Generar Contrato</button>
            </div>
        </div>
    </form>
</div>
