<div class="modal fade" id="modalEditor" tabindex="-1" role="dialog" aria-labelledby="modalEditorLabel" aria-hidden="true">
    <div class="modal-body">
        <div id="divEditor"></div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button class="btn btn-primary" onclick="save()"> &nbsp; Ok &nbsp; </button>
    </div>
</div>