<form class="form-horizontal" role="form" >
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title">Contrato RE-<?php echo date('Y') ?>-</h4>
        </div>
        <?php foreach($contrato as $contra) {?>
        <div class="panel-body">
            <div class="form-group">
                <label for="nombre_contacto" class="col-lg-2 control-label">Nombre Contacto :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="nombre_contacto" id="nombre_contacto" value="<?php echo $contra['nombre_contacto'];?>">
                </div>
            </div>
            <div class="form-group">
                <label for="email_contacto" class="col-lg-2 control-label">Email Contacto :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="email_contacto" id="nombre_contacto" value="<?php echo $contra['email_contacto'];?>">
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-7">
                    
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</form>
<form class="form-horizontal" role="form" >
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title">Seguimiento de Contrato</h4>
        </div>
        <?php foreach($contrato as $contra) {?>
        <div class="panel-body">
            <div class="form-group">
                <label for="nombre_contacto" class="col-lg-2 control-label">Nombre Contacto :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="nombre_contacto" id="nombre_contacto" value="<?php echo $contra['nombre_contacto'];?>">
                </div>
            </div>
            <div class="form-group">
                <label for="email_contacto" class="col-lg-2 control-label">Email Contacto :</label>
                <div class="col-lg-8">
                    <input class="form-control input-sm" type="text" name="email_contacto" id="nombre_contacto" value="<?php echo $contra['email_contacto'];?>">
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-7">
                    
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
</form>